#!/usr/bin/env python3

import os, sys, json
import itertools, functools
from collections import defaultdict

from json_dumps_but_smaller import json_dump
from ap_data import (
    factorio_base_id,
    unrandomized_technologies,
    ap_item_names,
    trap_names,
    progressive_technology_stacks,
)

here = os.path.dirname(__file__)
informative_input = os.path.join(here, "ap-dump.json")
pruned_input = os.path.join(here, "ap-dump-pruned.json")
output_names_py = os.path.join(here, "generated_names.py")
output_ids_py = os.path.join(here, "generated_ids.py")

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("input", metavar="path/to/script-output/ap-dump.json", help=
        "See FactorioInformationExtractor for how to generate this.")
    args = parser.parse_args()

    process(args.input)

header = """\
#################################################
# This file is generated by ./import-ap-dump.py #
#################################################

"""

names_header = """\
# This file provides spell checking in the Python type system,
# for example catching the misspelling "metalurgic", which is common for me.
# Because item, plant, technology, etc. names are all mixed together,
# this doesn't give proper type checking, just spell checking;
# You're on you're own for remembering the difference between accumulator and electric_energy_accumulators.

"""

artificial_names_header = """\

# This next block of names comes from ap_data.py rather than from Factorio itself.
"""

ids_header = """\
# This file provides what is absolutely needed on apworld import.
# Other imports in this apworld are deferred until this apworld is actually being used for generation, client, etc.

"""

def process(input_path):
    # Import the json data and gzip it.
    with open(input_path, "rb") as f:
        the_data = json.load(f)
    with open(informative_input, "w") as f:
        json_dump(the_data, f)
    the_data = prune_data(the_data)
    with open(pruned_input, "w") as f:
        json_dump(the_data, f)

    the_data = derrive_info(the_data)

    generate_names(the_data)
    generate_ids(the_data)

def generate_names(the_data):
    # Generate spellchecking names.
    already_generated = {}
    builtin_name_lines = []
    for prototype_type, prototype_decls in the_data.items():
        for name in prototype_decls.keys():
            python_name = to_snake(name)
            line = "{} = {}".format(python_name, json.dumps(name))
            if python_name not in already_generated:
                builtin_name_lines.append(line + "\n")
                already_generated[python_name] = line
            else:
                assert already_generated[python_name] == line, "identifier collision: " + line
    builtin_name_lines.sort()

    artificial_name_lines = []
    for name in ap_item_names + trap_names:
        python_name = to_snake(name.lower().replace(" ", "_"))
        line = "{} = {}".format(python_name, json.dumps(name))
        assert python_name not in already_generated, "identifier collision: " + line
        already_generated[python_name] = line
        artificial_name_lines.append(line + "\n")
    for name, technology_names in progressive_technology_stacks.items():
        for technology_name in technology_names:
            assert technology_name in the_data["technology"].keys(), "technology not found: " + technology_name
        if name in the_data["technology"].keys():
            # Some of the progressive stacks are just the name of the infinite tech.
            continue
        python_name = to_snake(name)
        line = "{} = {}".format(python_name, json.dumps(name))
        assert python_name not in already_generated, "identifier collision: " + line
        already_generated[python_name] = line
        artificial_name_lines.append(line + "\n")

    with open(output_names_py, "w") as f:
        f.write(header)
        f.write(names_header)
        f.writelines(builtin_name_lines)
        f.write(artificial_names_header)
        f.writelines(artificial_name_lines)

def generate_ids(the_data):
    # Generate AP id numbers.
    factorio_base_id = 2 ** 17
    id_cursor = factorio_base_id
    def next_id():
        nonlocal id_cursor
        id_cursor += 1
        return id_cursor
    # Technology locations and items
    ap_location_name_to_id = {}
    ap_item_name_to_id = {}
    for technology_name, technology_data in sorted(the_data["technology"].items()):
        assert not "_" in technology_name, "that's the delimiter we use for our special suffixes: " + technology_name
        location_name = technology_name + "_location"
        ap_location_name_to_id[location_name] = next_id()
        if (
            technology_name not in unrandomized_technologies and
            technology_data.get("max_level", 1) != "infinite" and
            "unit" in technology_data # Researched with science packs, not a trigger.
        ):
            second_location_name = technology_name + "_other_location"
            ap_location_name_to_id[second_location_name] = next_id()
        ap_item_name_to_id[technology_name] = next_id()
    # Progressive pseudo items
    for progressive_technology_name in sorted(progressive_technology_stacks):
        if progressive_technology_name in ap_item_name_to_id:
            # Some of the progressive stacks are just the name of the infinite tech.
            continue
        ap_item_name_to_id[progressive_technology_name] = next_id()
    # New items
    for name in ap_item_names:
        ap_item_name_to_id[name] = next_id()
    # Traps
    for trap_name in trap_names:
        ap_item_name_to_id[trap_name] = next_id()

    with open(output_ids_py, "w") as f:
        f.write(header)
        f.write(ids_header)
        f.write("ap_location_name_to_id = {}\n".format(json.dumps(ap_location_name_to_id, indent=4)))
        f.write("\n")
        f.write("ap_item_name_to_id = {}\n".format(json.dumps(ap_item_name_to_id, indent=4)))

def to_snake(name):
    if name[0].isdigit():
        name = "_" + name
    return name.lower().replace("-", "_")

def derrive_info(the_data):
    thing_to_planets: dict[str, set[str]] = defaultdict(set)
    control_variable_to_planets: dict[str, set[str]] = defaultdict(set)
    planet_to_shadow_variable_defs: dict[str, dict[str, set[str]]] = {}
    for planet_name, data in the_data["planet"].items():
        for thing in itertools.chain.from_iterable(settings["settings"] for settings in data["map_gen_settings"]["autoplace_settings"].values()):
            thing_to_planets[thing].add(planet_name)
        for control_name in data["map_gen_settings"]["autoplace_controls"].keys():
            for subvariable in ["size", "frequency", "richness"]:
                control_variable_to_planets["control:{}:{}".format(control_name, subvariable)].add(planet_name)
        shadow_variable_defs = {}
        for variable_name, expr in data["map_gen_settings"]["property_expression_names"].items():
            shadow_variable_defs[variable_name] = parse_refs(expr)
        planet_to_shadow_variable_defs[planet_name] = shadow_variable_defs

    expr_to_refs: dict[str, set[str]] = {
        name: set() for name in the_data["noise-function"].keys()
    }
    for name, data in the_data["noise-expression"].items():
        expr_to_refs[name] = parse_refs_with_local_expressions(data["expression"], data.get("local_expressions", {}))

    @functools.lru_cache()
    def resolve_refs(ref: str) -> tuple[str, ...]:
        """get the unresolved refs recursively depended on by this set of refs."""
        try:
            indirect_refs = expr_to_refs[ref]
        except KeyError:
            return (ref,)
        result = set()
        for indirect_ref in indirect_refs:
            result.update(resolve_refs(indirect_ref))
        return tuple(sorted(result))

    planet_to_natural_thing: dict[str, set[str]] = {
        name: set() for name in the_data["planet"].keys()
    }
    for prototype_type in [
        "fish",
        "lightning-attractor",
        "plant",
        "simple-entity",
        "tile",
        "tree",
        "unit-spawner",
    ]:
        for name, data in the_data[prototype_type].items():
            if "autoplace" not in data:
                assert name not in thing_to_planets, "planet autoplacing something without autoplace specification: " + name
                continue
            which_planet_clues = set()
            if name in thing_to_planets:
                # The planet calls out this thing.
                which_planet_clues.add(tuple(sorted(thing_to_planets[name])))
            if "control" in data:
                # We should find corresponding controls in one of the planets.
                example_control_variable = "control:{}:size".format(data["control"])
                assert example_control_variable in control_variable_to_planets
                which_planet_clues.add(tuple(sorted(control_variable_to_planets)))

            refs = parse_refs_with_local_expressions(
                data["autoplace"]["probability_expression"],
                data["autoplace"].get("local_expressions", {}),
            )
            planet_variables = set(itertools.chain.from_iterable(resolve_refs(ref) for ref in refs))
            for variable in planet_variables:
                # The probability expression references control variables from some planets.
                assert variable in control_variable_to_planets, variable
                which_planet_clues.add(tuple(sorted(control_variable_to_planets[variable])))
            if len(which_planet_clues) == 0:
                # e.g. tree-plant has autoplace controls but doesn't actually auto place anywhere.
                continue
            #if len(which_planet_clues) > 1 and ("nauvis",) in which_planet_clues:
            #    # Apparently everyone refernces Nauvis's moisture functions and stuff, which is just ok and ignored??
            #    which_planet_clues.remove(("nauvis",))
            assert len(which_planet_clues) == 1, "unclear where this autoplaces: {} -> {}".format(name, repr(which_planet_clues))
            [which_planets] = which_planet_clues
            for planet_name in which_planets:
                planet_things = planet_to_natural_thing[planet_name]
                assert name not in planet_things, "name collision: " + name
                planet_things.add(name)

    # TODO: territory_settings.
    import pdb; pdb.set_trace()
    return {
        prototype_type: prototype_data for prototype_type, prototype_data in the_data.items()
        if prototype_type not in (
            "noise-expression",
            "noise-function",
            "projectile",
        )
    }

import re
token_re = re.compile(
    # Reference: https://lua-api.factorio.com/latest/types/NoiseExpression.html
    r'(?P<Whitespace>[ \n\r\t]+)|'
    r'(?P<Identifier>[a-zA-Z_][a-zA-Z0-9_:]*)|'
    r'(?P<Number>0x[0-9a-f]+|([0-9]+\.?[0-9]*|\.[0-9]+)(e-?[0-9]+)?)|'
    r'''(?P<String>"[^"]*"|'[^']*')|'''
    r'(?P<Operator>==|~=|!=|%%|<=|>=|[(){}=,^*/%+<>&~|-])|'
    r'(?P<Invalid>.)'
)
noise_expression_builtins = {
    # Reference: https://lua-api.factorio.com/latest/auxiliary/noise-expressions.html
    # Built-in variables
    "x",
    "y",
    # Built-in constants
    "true",
    "false",
    "e",
    "pi",
    "inf",
    "map_seed",
    "map_seed_small",
    "map_seed_normalized",
    "map_width",
    "map_height",
    "starting_area_radius",
    "cliff_elevation_0",
    "cliff_elevation_interval",
    "cliff_smoothing",
    "cliff_richness",
    "starting_positions",
    "starting_lake_positions",
    "peaceful_mode",
    "no_enemies_mode",
    "control:moisture:frequency",
    "control:moisture:bias",
    "control:aux:frequency",
    "control:aux:bias",
    "control:temperature:frequency",
    "control:temperature:bias",
    # Built-in functions
    "abs",
    "atan2",
    "basis_noise",
    "ceil",
    "clamp",
    "cos",
    "distance_from_nearest_point",
    "distance_from_nearest_point_x",
    "distance_from_nearest_point_y",
    "expression_in_range",
    "floor",
    "if",
    "log2",
    "max",
    "min",
    "multisample",
    "multioctave_noise",
    "noise_layer_id",
    "pow",
    "pow_precise",
    "quick_multioctave_noise",
    "random_penalty",
    "ridge",
    "sin",
    "spot_noise",
    "sqrt",
    "terrace",
    #"var", # Handled specially.
    "variable_persistence_multioctave_noise",
    "voronoi_spot_noise",
    "voronoi_facet_noise",
    "voronoi_pyramid_noise",
    "voronoi_cell_id",
}
def parse_refs(expr: str|bool|int) -> set[str]:
    if type(expr) != str: return set()
    refs = []
    var_function_state = 0
    for match in token_re.finditer(expr):
        if match.group("Whitespace"): continue
        if match.group("Invalid"):
            import pdb; pdb.set_trace()
            assert False, "invalid token in expr: {}: {}".format(repr(match.group()), repr(expr))
        if var_function_state == 0:
            if match.group("Identifier") == "var":
                var_function_state = 1
            elif match.group("Identifier"):
                refs.append(match.group("Identifier"))
            elif match.group("Operator") == "=":
                # We just thought a parameter name was a ref. Undo.
                refs.pop()
        elif var_function_state == 1:
            assert match.group("Operator") == "(", "expected var to be followed by ("
            var_function_state = 2
        elif var_function_state == 2:
            assert match.group("String"), "expected var( to be followed by string"
            refs.append(match.group("String")[1:-1])
            var_function_state = 3
        elif var_function_state == 3:
            assert match.group("Operator") == ")", "expected var('string' to be followed by )"
            var_function_state = 0
    return set(refs) - noise_expression_builtins

assert parse_refs("distance_from_nearest_point{x = x, y = y, points = starting_positions}") == set()
assert parse_refs("clamp(x, -1, 1)") == set()
assert parse_refs("clamp(sea_level_temperature + var('control:temperature:bias') + quick_multioctave_noise{x = x,y = y,seed0 = map_seed,seed1 = 5,octaves = 4,input_scale = var('control:temperature:frequency') / 32,output_scale = 1/20,offset_x = 40000 / var('control:temperature:frequency'),octave_output_scale_multiplier = 3,octave_input_scale_multiplier = 1/3},-20, 50)") == {"sea_level_temperature"}

def parse_refs_with_local_expressions(main_expr: str, local_expressions: dict[str, str]) -> set[str]:
    local_expr_to_refs: dict[str, set[str]] = {
        local_name: parse_refs(expr)
        for local_name, expr in local_expressions.items()
    }
    return set(itertools.chain(
        parse_refs(main_expr),
        *local_expr_to_refs.values(),
    )) - local_expr_to_refs.keys()

    

# These are the properties we care about in the randomizer logic.
Base = {
    "minable": {
        "results": [{"name": str}],
        "result": str,
    },
    # Does anything power this machine?
    "energy_source": {
        "type": str,
        "usage_priority": str, # for type=electric
        "fuel_categories": [str], # for type=burner
        # TODO: can't figure out how to get useful information out of type=heat.
    },
    # Steel furances cannot be build on space platforms, for example.
    "surface_conditions": [{
        "property": str,
        "min": float,
        "max": float,
    }],
    # Several entities and tiles get autoplaced in various ways. This is one of the ways.
    "autoplace": {
        "control": str,
        "probability_expression": object,
        "local_expressions": object,
        "tile_restriction": [str],
    },
    # If either of these are true, we probably don't care about this.
    # Exception: vehicle guns tell us that spidertron can fire capture robot rockets.
    "hidden": bool,
    "parameter": bool,
}

CraftingMachine = {**Base,
    "crafting_categories": [str],
    "fixed_recipe": str,
}

SpaceLocation = {**Base,
    "solar_power_in_space": float, # It's a percent, not a multiplier. Default is 1%.
    "asteroid_spawn_definitions": [{
        "asteroid": str,
    }],
}

Vehicle = {**Base,
    # Only logic relevant if the vehicle can fire capture robot rockets.
    "guns": [str],
}

keep_props = {
    "accumulator": {str: Base},
    "agricultural-tower": {str: Base},
    "ammo": {str: {
        "ammo_category": str,
        # This is interesting for capture-robot-rocket:
        "ammo_type": {
            "action": {"action_delivery": {"projectile": str }},
            "target_filter": [str],
        },
    }},
    "ammo-turret": {str: {**Base,
        "attack_parameters": {"ammo_category": str},
    }},
    "assembling-machine": {str: CraftingMachine},
    "asteroid": {str: {
        "dying_trigger_effect": [{
            "type": str,
            "asteroid_name": str, # for type=create-asteroid-chunk
            "entity_name": str, # for type=create-entity
        }],
        "max_health": float,
        "resistances": [{
            "type": str,
            "decrease": float,
            "percent": float,
        }],
    }},
    "asteroid-chunk": {str: Base},
    "asteroid-collector": {str: Base},
    "boiler": {str: {**Base,
        "target_temperature": float,
    }},
    "capture-robot": {str: {}},
    "car": {str: Vehicle},
    "cargo-landing-pad": {str: {}},
    "character": {str: {
        "crafting_categories": [str],
        "mining_categories": [str],
    }},
    "construction-robot": {str: Base},
    "electric-pole": {str: Base},
    "electric-turret": {str: Base}, # TODO: add attack_parameters if we care.
    "fish": {str: Base},
    "fluid": {str: Base},
    "fluid-turret": {str: Base}, # TODO: add attack_parameters if we care.
    "furnace": {str: CraftingMachine},
    "fusion-generator": {str: Base},
    "fusion-reactor": {str: Base},
    "generator": {str: {**Base,
        "maximum_temperature": float,
    }},
    "gun": {str: {**Base,
        "attack_parameters": {"ammo_category": str},
    }},
    "heat-pipe": {str: {}},
    "item": {str: {**Base,
        "place_result": str,
        "place_as_tile": {"result": str},
        "plant_result": str,
        "fuel_category": str,
        "burnt_result": str,
        "spoil_ticks": int,
        "spoil_result": str,
    }},
    "lab": {str: {**Base,
        "inputs": [str],
    }},
    "lightning-attractor": {str: Base},
    "logistic-container": {str: {**Base,
        "logistic_mode": str,
    }},
    "logistic-robot": {str: Base},
    "mining-drill": {str: {**Base,
        "resource_categories": [str],
        "input_fluid_box": {}, # Burner mining drill cannot mine uranium.
    }},
    "noise-expression": {str: {
        "expression": object,
        "local_expressions": object,
    }},
    "noise-function": {str: {}},
    "offshore-pump": {str: Base},
    "pipe": {str: Base},
    "pipe-to-ground": {str: Base},
    "planet": {str: {**SpaceLocation,
        "map_gen_settings": {
            # In addition to a tile/entity's own .autoplace spec, this also matters for placing entities somehow.
            "property_expression_names": {str: str},
            "autoplace_settings": {
                "tile": {"settings": {str: {}}},
                "entity": {"settings": {str: {}}},
            },
            "autoplace_controls": {str: {}},
            "territory_settings": {"units": [str]}, # Demolishers.
        },
        "surface_properties": {str: float},
        "lightning_properties": {},
        "entities_require_heating": bool,
    }},
    "plant": {str: Base},
    "projectile": {str: {
        "action": {"action_delivery": {"target_effects": [{
            "type": str,
            "damage": {"amount": float, "type": str},
            "entity_name": str, # Only interesting for capture-robot-rocket.
        }]}},
    }},
    "pump": {str: Base},
    "quality": {str: {**Base,
        "next": str,
    }},
    "reactor": {str: Base},
    "recipe": {str: {**Base,
        "category": str,
        "ingredients": [{
            "name": str,
            "amount": int,
            "ignored_by_stats": int,
            # ignoring temperature settings, as they are never used in vanilla.
        }],
        "energy_required": float,
        "results": [{
            "name": str,
            "amount": int,
            # ignoring amount_min and amount_max, as they are never used in vanilla.
            "probability": float,
            "ignored_by_stats": int,
            "extra_count_fraction": float,
            "temperature": float,
        }],
    }},
    "repair-tool": {str: {}},
    "resource": {str: {}},
    "roboport": {str: Base},
    "rocket-silo": {str: CraftingMachine},
    "segmented-unit": {str: {
        "corpse": str,
    }},
    "simple-entity": {str: Base},
    "solar-panel": {str: Base},
    "space-connection": {str: {**SpaceLocation,
        "from": str,
        "to": str,
    }},
    "space-location": {str: SpaceLocation},
    "spider-vehicle": {str: Vehicle},
    "storage-tank": {str: Base},
    "surface-property": {str: {
        "default_value": float,
    }},
    "technology": {str: {**Base,
        "research_trigger": {
            "type": str,
            "entity": str,
            "item": str,
            "fluid": str,
            "count": int,
        },
        "unit": {
            "count": int,
            "count_formula": str,
            "time": float,
            "ingredients": [(str, int)],
        },
        "ignore_tech_cost_multiplier": bool,
        "max_level": str, # Always "infinite" or omitted in vanilla.
        "prerequisites": [str],
        "effects": object, # Preserve verbatim.
    }},
    "thruster": {str: Base},
    "tile": {str: {**Base,
        "fluid": str,
    }},
    "tree": {str: Base},
    "unit-spawner": {str: {**Base,
        "loot": [{"item": str}],
    }},
    "wall": {str: Base},
}

def prune_data(data):
    def recurse(data, schema):
        if schema == object:
            return data
        if schema == str:
            assert type(data) == str, "expected str: " + repr(data)
            return data
        if schema == bool:
            assert type(data) == bool, "expected bool: " + repr(data)
            return data
        if schema == int:
            assert type(data) in (int, float), "expected number: " + repr(data)
            # Recipe product amounts are sometimes floats in the prototype data (example "speed-module-recycling").
            # They get truncated to int16 by the runtime phase.
            return int(data)
        if schema == float:
            assert type(data) in (int, float), "expected number: " + repr(data)
            return data
        if type(schema) == dict and schema.keys() == {str}:
            [v_schema] = schema.values()
            return {k: recurse(v, v_schema) for k, v in data.items()}
        if type(schema) == dict and all(type(k) == str for k in schema.keys()):
            return {k: recurse(data[k], v_schema) for k, v_schema in schema.items() if k in data}
        if type(schema) == list and len(schema) == 1:
            [v_schema] = schema
            if type(data) == list:
                return [recurse(v, v_schema) for v in data]
            else:
                return recurse(data, v_schema) # Fallback to guessing the list is instead a single item.
        if type(schema) == tuple:
            assert type(data) == list and len(schema) == len(data), "expected tuple of length {}: {}".format(len(schema), repr(data))
            return [recurse(v, v_schema) for v, v_schema in zip(data, schema)]
        assert False, "unrecognized schema: " + repr(schema)
    return recurse(data, keep_props)

if __name__ == "__main__":
    main()
