#!/usr/bin/env python3

import os, sys, json

here = os.path.dirname(__file__)
informative_input = os.path.join(here, "ap-dump.json")
output_py = os.path.join(here, "generated_names.py")

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("input", metavar="path/to/script-output/ap-dump.json", help=
        "See FactorioInformationExtractor for how to generate this.")
    args = parser.parse_args()

    process(args.input)

header = """\
#################################################
# This file is generated by ./import-ap-dump.py #
#################################################
"""

def process(input_path):
    # Import the json data and gzip it.
    with open(input_path, "rb") as in_f:
        the_data = json.load(in_f)
    with open(informative_input, "w") as out_f:
        json.dump(the_data, out_f, indent=2)

    # Generate constants for some things we might want to refer to.
    lines = []
    exports = []
    for group_name, items in the_data.items():
        group_title = to_title(group_name)
        lines.extend([
            "",
            "class {}:".format(group_title),
        ])
        exports.append(group_title)
        for name in items.keys():
            lines.append(
                "    {} = {}".format(to_snake(name), repr(name)),
            )

    with open(output_py, "w") as f:
        f.write(header)
        f.write("\n__all__ = {}\n".format(repr(exports)))
        f.writelines(line + "\n" for line in lines)

    # Run the next step of the generation, which uses the above generated_names.py.
    import _generate_data
    _generate_data.generate_everything(the_data)

def to_title(name):
    return sanitize(name.title().replace("_", "").replace("-", ""))
def to_snake(name):
    return sanitize(name.lower().replace("-", "_"))
def sanitize(name):
    if name[0].isdigit():
        name = "_" + name
    return name

if __name__ == "__main__":
    main()
