#!/usr/bin/env python3

import os, sys, json
from json_dumps_but_smaller import json_dump

here = os.path.dirname(__file__)
informative_input = os.path.join(here, "ap-dump.json")
pruned_input = os.path.join(here, "ap-dump-pruned.json")
output_py = os.path.join(here, "generated_names.py")

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("input", metavar="path/to/script-output/ap-dump.json", help=
        "See FactorioInformationExtractor for how to generate this.")
    args = parser.parse_args()

    process(args.input)

header = """\
#################################################
# This file is generated by ./import-ap-dump.py #
#################################################

# This file provides spell checking in the Python type system,
# for example catching the misspelling "metalurgic", which is common for me.
# Because item, plant, technology, etc. names are all mixed together,
# this doesn't function as proper type checking, just spell checking;
# You're on you're own for remembering the difference between accumulator and electric_energy_accumulators.

"""

def process(input_path):
    # Import the json data and gzip it.
    with open(input_path, "rb") as f:
        the_data = json.load(f)
    with open(informative_input, "w") as f:
        json_dump(the_data, f)
    the_data = prune_data(the_data)
    with open(pruned_input, "w") as f:
        json_dump(the_data, f)

    # Generate constants for some things we might want to refer to.
    already_generated = {}
    lines = []
    for prototype_type, prototype_decls in the_data.items():
        if prototype_type in (
            "noise-expression",
            "noise-function",
            "projectile",
        ): continue
        for name in prototype_decls.keys():
            python_name = to_snake(name)
            line = "{} = {}".format(python_name, json.dumps(name))
            if python_name not in already_generated:
                lines.append(line + "\n")
                already_generated[python_name] = line
            else:
                assert already_generated[python_name] == line, "identifier collision: " + line
    lines.sort()
    with open(output_py + ".tmp", "w") as f:
        f.write(header)
        f.writelines(lines)
    os.rename(output_py + ".tmp", output_py)

def to_snake(name):
    if name[0].isdigit():
        name = "_" + name
    return name.lower().replace("-", "_")

# These are the properties we care about in the randomizer logic.
Base = {
    "minable": {
        "results": [{"name": str}],
        "result": str,
    },
    # Does anything power this machine?
    "energy_source": {
        "type": str,
        "usage_priority": str, # for type=electric
        "fuel_categories": [str], # for type=burner
        # TODO: can't figure out how to get useful information out of type=heat.
    },
    # Steel furances cannot be build on space platforms, for example.
    "surface_conditions": [{
        "property": str,
        "min": float,
        "max": float,
    }],
    # If either of these are true, we probably don't care about this.
    # Exception: vehicle guns tell us that spidertron can fire capture robot rockets.
    "hidden": bool,
    "parameter": bool,
}

CraftingMachine = {**Base,
    "crafting_categories": [str],
    "fixed_recipe": str,
}

SpaceLocation = {**Base,
    "solar_power_in_space": float, # It's a percent, not a multiplier. Default is 1%.
    "asteroid_spawn_definitions": [{
        "asteroid": str,
    }],
}

Vehicle = {**Base,
    # Only logic relevant if the vehicle can fire capture robot rockets.
    "guns": [str],
}

AutoplaceSpecification = {
    "control": str,
    "probability_expression": object,
    "local_expressions": object,
    "tile_restriction": [str],
}

keep_props = {
    "accumulator": {str: Base},
    "agricultural-tower": {str: Base},
    "ammo": {str: {
        "ammo_category": str,
        # This is interesting for capture-robot-rocket:
        "ammo_type": {
            "action": {"action_delivery": {"projectile": str }},
            "target_filter": [str],
        },
    }},
    "ammo-turret": {str: {**Base,
        "attack_parameters": {"ammo_category": str},
    }},
    "assembling-machine": {str: CraftingMachine},
    "asteroid": {str: {
        "dying_trigger_effect": [{
            "type": str,
            "asteroid_name": str, # for type=create-asteroid-chunk
            "entity_name": str, # for type=create-entity
        }],
        "max_health": float,
        "resistances": [{
            "type": str,
            "decrease": float,
            "percent": float,
        }],
    }},
    "asteroid-chunk": {str: Base},
    "asteroid-collector": {str: Base},
    "boiler": {str: {**Base,
        "target_temperature": float,
    }},
    "capture-robot": {str: {}},
    "car": {str: Vehicle},
    "cargo-landing-pad": {str: {}},
    "character": {str: {
        "crafting_categories": [str],
        "mining_categories": [str],
    }},
    "construction-robot": {str: Base},
    "electric-pole": {str: Base},
    "electric-turret": {str: Base}, # TODO: add attack_parameters if we care.
    "fish": {str: Base},
    "fluid": {str: Base},
    "fluid-turret": {str: Base}, # TODO: add attack_parameters if we care.
    "furnace": {str: CraftingMachine},
    "fusion-generator": {str: Base},
    "fusion-reactor": {str: Base},
    "generator": {str: {**Base,
        "maximum_temperature": float,
    }},
    "gun": {str: {**Base,
        "attack_parameters": {"ammo_category": str},
    }},
    "heat-pipe": {str: {}},
    "item": {str: {**Base,
        "place_result": str,
        "place_as_tile": {"result": str},
        "plant_result": str,
        "fuel_category": str,
        "burnt_result": str,
        "spoil_ticks": int,
        "spoil_result": str,
    }},
    "lab": {str: {**Base,
        "inputs": [str],
    }},
    "lightning-attractor": {str: Base},
    "logistic-container": {str: {**Base,
        "logistic_mode": str,
    }},
    "logistic-robot": {str: Base},
    "mining-drill": {str: {**Base,
        "resource_categories": [str],
        "input_fluid_box": {}, # Burner mining drill cannot mine uranium.
    }},
    "noise-expression": {str: {
        "expression": object,
        "local_expressions": object,
    }},
    "noise-function": {str: {}},
    "offshore-pump": {str: Base},
    "pipe": {str: Base},
    "pipe-to-ground": {str: Base},
    "planet": {str: {**SpaceLocation,
        "map_gen_settings": {
            "autoplace_settings": {
                "tile": {"settings": {str: {}}},
                "entity": {"settings": {str: {}}},
            },
            "autoplace_controls": {str: {}},
            "territory_settings": {"units": [str]}, # Demolishers.
        },
        "surface_properties": {str: float},
        "lightning_properties": {},
        "entities_require_heating": bool,
    }},
    "plant": {str: {**Base,
        "autoplace": AutoplaceSpecification,
    }},
    "projectile": {str: {
        "action": {"action_delivery": {"target_effects": [{
            "type": str,
            "damage": {"amount": float, "type": str},
            "entity_name": str, # Only interesting for capture-robot-rocket.
        }]}},
    }},
    "pump": {str: Base},
    "quality": {str: {**Base,
        "next": str,
    }},
    "reactor": {str: Base},
    "recipe": {str: {**Base,
        "category": str,
        "ingredients": [{
            "name": str,
            "amount": int,
            "ignored_by_stats": int,
            # ignoring temperature settings, as they are never used in vanilla.
        }],
        "energy_required": float,
        "results": [{
            "name": str,
            "amount": int,
            # ignoring amount_min and amount_max, as they are never used in vanilla.
            "probability": float,
            "ignored_by_stats": int,
            "extra_count_fraction": float,
            "temperature": float,
        }],
    }},
    "repair-tool": {str: {}},
    "resource": {str: {}},
    "roboport": {str: Base},
    "rocket-silo": {str: CraftingMachine},
    "segmented-unit": {str: {
        "corpse": str,
    }},
    "simple-entity": {str: Base},
    "solar-panel": {str: Base},
    "space-connection": {str: {**SpaceLocation,
        "from": str,
        "to": str,
    }},
    "space-location": {str: SpaceLocation},
    "spider-vehicle": {str: Vehicle},
    "storage-tank": {str: Base},
    "surface-property": {str: {
        "default_value": float,
    }},
    "technology": {str: {**Base,
        "research_trigger": {
            "type": str,
            "entity": str,
            "item": str,
            "fluid": str,
            "count": int,
        },
        "unit": {
            "count": int,
            "count_formula": str,
            "time": float,
            "ingredients": [(str, int)],
        },
        "ignore_tech_cost_multiplier": bool,
        "max_level": str, # Always "infinite" or omitted in vanilla.
        "prerequisites": [str],
        "effects": object, # Preserve verbatim.
    }},
    "thruster": {str: Base},
    "tile": {str: {**Base,
        "fluid": str,
    }},
    "tree": {str: {**Base,
        "autoplace": AutoplaceSpecification,
    }},
    "unit-spawner": {str: {**Base,
        "autoplace": AutoplaceSpecification,
        "loot": [{"item": str}],
    }},
    "wall": {str: Base},
}

def prune_data(data):
    def recurse(data, schema):
        if schema == object:
            return data
        if schema == str:
            assert type(data) == str, "expected str: " + repr(data)
            return data
        if schema == bool:
            assert type(data) == bool, "expected bool: " + repr(data)
            return data
        if schema == int:
            assert type(data) in (int, float), "expected number: " + repr(data)
            # Recipe product amounts are sometimes floats in the prototype data (example "speed-module-recycling").
            # They get truncated to int16 by the runtime phase.
            return int(data)
        if schema == float:
            assert type(data) in (int, float), "expected number: " + repr(data)
            return data
        if type(schema) == dict and schema.keys() == {str}:
            [v_schema] = schema.values()
            return {k: recurse(v, v_schema) for k, v in data.items()}
        if type(schema) == dict and all(type(k) == str for k in schema.keys()):
            return {k: recurse(data[k], v_schema) for k, v_schema in schema.items() if k in data}
        if type(schema) == list and len(schema) == 1:
            [v_schema] = schema
            if type(data) == list:
                return [recurse(v, v_schema) for v in data]
            else:
                return recurse(data, v_schema) # Fallback to guessing the list is instead a single item.
        if type(schema) == tuple:
            assert type(data) == list and len(schema) == len(data), "expected tuple of length {}: {}".format(len(schema), repr(data))
            return [recurse(v, v_schema) for v, v_schema in zip(data, schema)]
        assert False, "unrecognized schema: " + repr(schema)
    return recurse(data, keep_props)

if __name__ == "__main__":
    main()
