name: Add a new world to the World Manager Index
description: Request a world
title: "Category: "
labels:
  - invalid
body:
  - type: markdown
    attributes:
      value: |
        You're in the wrong repo, please add an issue in [the Index repo](https://GitHub.com/silasary/apworlds) instead.
  - type: textarea
    id: feature
    attributes:
      label: Obligatory text box so the template works.