# CAS Kit names
throwback_fit = "Throwback Fit"
fashion_street = "Fashion Street"
incheon_arrivals = "Incheon Arrivals"
modern_menswear = "Modern Menswear"
carnaval_streetwear = "Carnaval Streetwear"
moonlight_chic = "Moonlight Chic"
first_fits = "First Fits"
simtimates_collection = "Simtimates Collection"
grunge_revival = "Grunge Revival"
poolside_splash = "Poolside Splash"
goth_galore = "Goth Galore"
urban_homage = "Urban Homage"
sweet_slumber_party = "Sweet Slumber Party"