# Expansion Names
get_to_work = "Get to Work"
get_together = "Get Together"
city_living = "City Living"
cats_and_dogs = "Cats and Dogs"
seasons = "Seasons"
get_famous = "Get Famous"
island_living = "Island Living"
discover_university = "Discover University"
eco_lifestyle = "Eco Lifestyle"
snowy_escape = "Snowy Escape"
high_school_years = "High School Years"
growing_together = "Growing Together"
horse_ranch = "Horse Ranch"
for_rent = "For Rent"
lovestruck = "Lovestruck"
life_and_death = "Life and Death"