location_name_groups: dict[str, set[str]] = {
    "Writing": {f"Writing Skill {i}" for i in range(2, 11)},
    "Charisma": {f"Charisma Skill {i}" for i in range(2, 11)},
    "Comedy": {f"Comedy Skill {i}" for i in range(2, 11)},
    "Cooking": {f"Cooking Skill {i}" for i in range(2, 11)},
    "Gourmet": {f"Gourmet Skill {i}" for i in range(2, 11)},
    "Fishing": {f"Fishing Skill {i}" for i in range(2, 11)},
    "Fitness": {f"Fitness Skill {i}" for i in range(2, 11)},
    "Gardening": {f"Gardening Skill {i}" for i in range(2, 11)},
    "Handiness": {f"Handiness Skill {i}" for i in range(2, 11)},
    "Logic": {f"Logic Skill {i}" for i in range(2, 11)},
    "Mischief": {f"Mischief Skill {i}" for i in range(2, 11)},
    "Mixology": {f"Mixology Skill {i}" for i in range(2, 11)},
    "Painting": {f"Painting Skill {i}" for i in range(2, 11)},
    "Piano": {f"Piano Skill {i}" for i in range(2, 11)},
    "Programming": {f"Programming Skill {i}" for i in range(2, 11)},
    "Rocket Science": {f"Rocket Science Skill {i}" for i in range(2, 11)},
    "Video Gaming": {f"Video Gaming Skill {i}" for i in range(2, 11)},
    "Violin": {f"Violin Skill {i}" for i in range(2, 11)},
    "Photography": {f"Photography Skill {i}" for i in range(2,6)},
    "Guitar": {f"Guitar Skill {i}" for i in range(2,11)},
    "Music": {f"{instrument} Skill {level}"
              for instrument in ["Piano", "Violin", "Guitar"]
              for level in range(2, 11)},
    "Food": {f"{skill} Skill {level}"
             for skill in ["Gourmet", "Cooking", "Mixology"]
             for level in range(2,11)},
    "Computer": {f"{skill} Skill {level}"
                 for skill in ["Programming", "Video Gaming"]
                 for level in range(2,11)},
    "Astronaut": {
        "Module Cleaner (Astronaut 2)",
        "Technician (Astronaut 3)",
        "Command Center Lead (Astronaut 4)",
        "Low-Orbit Specialist (Astronaut 5)",
        "Space Cadet (Astronaut 6)",
        "Astronaut (Astronaut 7)",
        "Planet Patrol (Astronaut / Space Ranger 8)",
        "Sheriff of the Stars (Astronaut / Space Ranger 9)",
        "Space Ranger (Astronaut / Space Ranger 10)",
        "Moon Mercenary (Astronaut / Interstellar Smuggler 8)",
        "Alien Goods Trader (Astronaut / Interstellar Smuggler 9)",
        "Interstellar Smuggler (Astronaut / Interstellar Smuggler 10)",
    },
    "Space Ranger": {
        "Planet Patrol (Astronaut / Space Ranger 8)",
        "Sheriff of the Stars (Astronaut / Space Ranger 9)",
        "Space Ranger (Astronaut / Space Ranger 10)",
    },
    "Interstellar Smuggler": {
        "Moon Mercenary (Astronaut / Interstellar Smuggler 8)",
        "Alien Goods Trader (Astronaut / Interstellar Smuggler 9)",
        "Interstellar Smuggler (Astronaut / Interstellar Smuggler 10)",
    },
    "Athlete": {
        "Locker Room Attendant (Athlete 2)",
        "Team Mascot (Athlete 3)",
        "Dance Team Captain (Athlete 4)",
        "Minor Leaguer (Athlete / Professional Athlete 5)",
        "Rookie (Athlete / Professional Athlete 6)",
        "Starter (Athlete / Professional Athlete 7)",
        "All-Star (Athlete / Professional Athlete 8)",
        "MVP (Athlete / Professional Athlete 9)",
        "Hall of Famer (Athlete / Professional Athlete 10)",
        "Personal Trainer (Athlete / Bodybuilder 5)",
        "Professional Bodybuilder (Athlete / Bodybuilder 6)",
        "Champion Bodybuilder (Athlete / Bodybuilder 7)",
        "Trainer to the Stars (Athlete / Bodybuilder 8)",
        "Celebrity Bodybuilder (Athlete / Bodybuilder 9)",
        "Mr. / Mrs. Solar System (Athlete / Bodybuilder 10)",
    },
    "Professional Athlete": {
        "Minor Leaguer (Athlete / Professional Athlete 5)",
        "Rookie (Athlete / Professional Athlete 6)",
        "Starter (Athlete / Professional Athlete 7)",
        "All-Star (Athlete / Professional Athlete 8)",
        "MVP (Athlete / Professional Athlete 9)",
        "Hall of Famer (Athlete / Professional Athlete 10)",
    },
    "Bodybuilder": {
        "Personal Trainer (Athlete / Bodybuilder 5)",
        "Professional Bodybuilder (Athlete / Bodybuilder 6)",
        "Champion Bodybuilder (Athlete / Bodybuilder 7)",
        "Trainer to the Stars (Athlete / Bodybuilder 8)",
        "Celebrity Bodybuilder (Athlete / Bodybuilder 9)",
        "Mr. / Mrs. Solar System (Athlete / Bodybuilder 10)",
    },
    "Business": {
        "Office Assistant (Business 2)",
        "Assistant to the Manager (Business 3)",
        "Assistant Manager (Business 4)",
        "Regional Manager (Business 5)",
        "Senior Manager (Business 6)",
        "Vice-President (Business / Management 7)",
        "President (Business / Management 8)",
        "CEO (Business / Management 9)",
        "Business Tycoon (Business / Management 10)",
        "Futures Trader (Business / Investor 7)",
        "Hedge Fund Manager (Business / Investor 8)",
        "Corporate Raider (Business / Investor 9)",
        "Angel Investor (Business / Investor 10)",
    },
    "Management": {
        "Vice-President (Business / Management 7)",
        "President (Business / Management 8)",
        "CEO (Business / Management 9)",
        "Business Tycoon (Business / Management 10)",
    },
    "Investor": {
        "Futures Trader (Business / Investor 7)",
        "Hedge Fund Manager (Business / Investor 8)",
        "Corporate Raider (Business / Investor 9)",
        "Angel Investor (Business / Investor 10)",
    },
    "Criminal": {
        "Petty Thief (Criminal 2)",
        "Ringleader (Criminal 3)",
        "Felonius Monk (Criminal 4)",
        "Minor Crimelord (Criminal 5)",
        "The Muscle (Criminal / Boss 6)",
        "Getaway Driver (Criminal / Boss 7)",
        "Safe Cracker (Criminal / Boss 8)",
        "The Brains (Criminal / Boss 9)",
        "The Boss (Criminal / Boss 10)",
        "DigiThief (Criminal / Oracle 6)",
        "Elite Hacker (Criminal / Oracle 7)",
        "An0nymous Ghost (Criminal / Oracle 8)",
        "Net Demon (Criminal / Oracle 9)",
        "The Oracle (Criminal / Oracle 10)",
    },
    "Boss": {
        "The Muscle (Criminal / Boss 6)",
        "Getaway Driver (Criminal / Boss 7)",
        "Safe Cracker (Criminal / Boss 8)",
        "The Brains (Criminal / Boss 9)",
        "The Boss (Criminal / Boss 10)",
    },
    "Oracle": {
        "DigiThief (Criminal / Oracle 6)",
        "Elite Hacker (Criminal / Oracle 7)",
        "An0nymous Ghost (Criminal / Oracle 8)",
        "Net Demon (Criminal / Oracle 9)",
        "The Oracle (Criminal / Oracle 10)",
    },
    "Culinary": {
        "Head Dishwasher (Culinary 2)",
        "Caterer (Culinary 3)",
        "Mixologist (Culinary 4)",
        "Line Cook (Culinary 5)",
        "Head Caterer (Culinary / Chef 6)",
        "Pastry Chef (Culinary / Chef 7)",
        "Sous Chef (Culinary / Chef 8)",
        "Executive Chef (Culinary / Chef 9)",
        "Celebrity Chef (Culinary / Chef 10)",
        "Head Mixologist (Culinary / Mixologist 6)",
        "Juice Boss (Culinary / Mixologist 7)",
        "Chief Drink Operator (Culinary / Mixologist 8)",
        "Drinkmaster (Culinary / Mixologist 9)",
        "Celebrity Mixologist (Culinary / Mixologist 10)",
    },
    "Chef": {
        "Head Caterer (Culinary / Chef 6)",
        "Pastry Chef (Culinary / Chef 7)",
        "Sous Chef (Culinary / Chef 8)",
        "Executive Chef (Culinary / Chef 9)",
        "Celebrity Chef (Culinary / Chef 10)",
    },
    "Mixologist": {
        "Head Mixologist (Culinary / Mixologist 6)",
        "Juice Boss (Culinary / Mixologist 7)",
        "Chief Drink Operator (Culinary / Mixologist 8)",
        "Drinkmaster (Culinary / Mixologist 9)",
        "Celebrity Mixologist (Culinary / Mixologist 10)",
    },
    "Entertainer": {
        "Open Mic Seeker (Entertainer 2)",
        "C-Lister (Entertainer 3)",
        "Opening Act (Entertainer 4)",
        "Jingle Jammer (Entertainer / Musician 5)",
        "Serious Musician (Entertainer / Musician 6)",
        "Professional Pianist (Entertainer / Musician 7)",
        "Symphonic String Player (Entertainer / Musician 8)",
        "Instrumental Wonder (Entertainer / Musician 9)",
         "Concert Virtuoso (Entertainer / Musician 10)",
        "Jokesmith (Entertainer / Comedian 5)",
        "Solid Storyteller (Entertainer / Comedian 6)",
        "Rising Comedian (Entertainer / Comedian 7)",
        "Roast Master (Entertainer / Comedian 8)",
        "Stand Up Star (Entertainer / Comedian 9)",
         "Show Stopper (Entertainer / Comedian 10)",
    },
    "Musician": {
        "Jingle Jammer (Entertainer / Musician 5)",
        "Serious Musician (Entertainer / Musician 6)",
        "Professional Pianist (Entertainer / Musician 7)",
        "Symphonic String Player (Entertainer / Musician 8)",
        "Instrumental Wonder (Entertainer / Musician 9)",
        "Concert Virtuoso (Entertainer / Musician 10)",
    },
    "Comedian": {
        "Jokesmith (Entertainer / Comedian 5)",
        "Solid Storyteller (Entertainer / Comedian 6)",
        "Rising Comedian (Entertainer / Comedian 7)",
        "Roast Master (Entertainer / Comedian 8)",
        "Stand Up Star (Entertainer / Comedian 9)",
        "Show Stopper (Entertainer / Comedian 10)",
    },
    "Painter": {
        "Art Book Collator (Painter 2)",
        "Hungry Artist (Painter 3)",
        "Watercolor Dabbler (Painter 4)",
        "Canvas Creator (Painter 5)",
        "Imaginative Imagist (Painter 6)",
        "Artist en Residence (Painter / Master of the Real 7)",
        "Professional Painter (Painter / Master of the Real 8)",
        "Illustrious Illustrator (Painter / Master of the Real 9)",
        "Master of the Real (Painter / Master of the Real 10)",
        "Color Theory Critic (Painter / Patron of the Arts 7)",
        "Fine-Art Aficionado (Painter / Patron of the Arts 8)",
        "Composition Curator (Painter / Patron of the Arts 9)",
        "Patron of the Arts (Painter / Patron of the Arts 10)",
    },
    "Master of the Real": {
        "Artist en Residence (Painter / Master of the Real 7)",
        "Professional Painter (Painter / Master of the Real 8)",
        "Illustrious Illustrator (Painter / Master of the Real 9)",
        "Master of the Real (Painter / Master of the Real 10)",
    },
    "Patron of the Arts": {
        "Color Theory Critic (Painter / Patron of the Arts 7)",
        "Fine-Art Aficionado (Painter / Patron of the Arts 8)",
        "Composition Curator (Painter / Patron of the Arts 9)",
        "Patron of the Arts (Painter / Patron of the Arts 10)",
    },
    "Secret Agent": {
        "Intelligence Researcher (Secret Agent 2)",
        "Agent Handler (Secret Agent 3)",
        "Field Agent (Secret Agent 4)",
        "Lead Detective (Secret Agent 5)",
        "Government Agent (Secret Agent 6)",
        "Secret Agent (Secret Agent 7)",
        "Spy Captain (Secret Agent / Diamond Agent 8)",
        "Shadow Agent (Secret Agent / Diamond Agent 9)",
        "Double Diamond Agent (Secret Agent / Diamond Agent 10)",
        "Double Agent (Secret Agent / Villain 8)",
        "[Redacted] (Secret Agent / Villain 9)",
        "Supreme Villain (Secret Agent / Villain 10)",
        "Triple Agent (Secret Agent / Villain 11)",
    },
    "Diamond Agent": {
        "Spy Captain (Secret Agent / Diamond Agent 8)",
        "Shadow Agent (Secret Agent / Diamond Agent 9)",
        "Double Diamond Agent (Secret Agent / Diamond Agent 10)",
    },
    "Villain": {
        "Double Agent (Secret Agent / Villain 8)",
        "[Redacted] (Secret Agent / Villain 9)",
        "Supreme Villain (Secret Agent / Villain 10)",
        "Triple Agent (Secret Agent / Villain 11)",
    },
    "Style Influencer": {
        "Consignment Commentator (Style Influencer 2)",
        "Wearable Wordsmith (Style Influencer 3)",
        "Ensemble Author (Style Influencer 4)",
        "Culture Columnist (Style Influencer 5)",
        "Dedicated Dresser (Style Influencer / Stylist 6)",
        "Textile Tactician (Style Influencer / Stylist 7)",
        "Wardrobe Wiz (Style Influencer / Stylist 8)",
        "Make-Over Miracle Worker (Style Influencer / Stylist 9)",
        "Persona Re-Imager (Style Influencer / Stylist 10)",
        "Posh Profiler (Style Influencer / Trend Setter 6)",
        "Fashion Figure (Style Influencer / Trend Setter 7)",
        "Best-Self-Helper (Style Influencer / Trend Setter 8)",
        "It Sim (Style Influencer / Trend Setter 9)",
        "Icon O'Class (Style Influencer / Trend Setter 10)",
    },
    "Stylist": {
        "Dedicated Dresser (Style Influencer / Stylist 6)",
        "Textile Tactician (Style Influencer / Stylist 7)",
        "Wardrobe Wiz (Style Influencer / Stylist 8)",
        "Make-Over Miracle Worker (Style Influencer / Stylist 9)",
        "Persona Re-Imager (Style Influencer / Stylist 10)",
    },
    "Trend Setter": {
        "Posh Profiler (Style Influencer / Trend Setter 6)",
        "Fashion Figure (Style Influencer / Trend Setter 7)",
        "Best-Self-Helper (Style Influencer / Trend Setter 8)",
        "It Sim (Style Influencer / Trend Setter 9)",
        "Icon O'Class (Style Influencer / Trend Setter 10)",
    },
    "Tech Guru": {
        "Quality Assurance (Tech Guru 2)",
        "Code Monkey (Tech Guru 3)",
        "Ace Engineer (Tech Guru 4)",
        "Project Manager (Tech Guru 5)",
        "Development Captain (Tech Guru 6)",
        "eSports Competitor (Tech Guru / eSport Gamer 7)",
        "Pro Gamer (Tech Guru / eSport Gamer 8)",
        "APM King / Queen (Tech Guru / eSport Gamer 9)",
        "Champion Gamer (Tech Guru / eSport Gamer 10)",
        "The Next Big Thing? (Tech Guru / Start-up Entrepreneur 7)",
        "Independent Consultant (Tech Guru / Start-up Entrepreneur 8)",
        "Dot-Com Pioneer (Tech Guru / Start-up Entrepreneur 9)",
        "Start-up Genius (Tech Guru / Start-up Entrepreneur 10)",
    },
    "eSport Gamer": {
        "eSports Competitor (Tech Guru / eSport Gamer 7)",
        "Pro Gamer (Tech Guru / eSport Gamer 8)",
        "APM King / Queen (Tech Guru / eSport Gamer 9)",
        "Champion Gamer (Tech Guru / eSport Gamer 10)",
    },
    "Start-up Entrepreneur": {
        "The Next Big Thing? (Tech Guru / Start-up Entrepreneur 7)",
        "Independent Consultant (Tech Guru / Start-up Entrepreneur 8)",
        "Dot-Com Pioneer (Tech Guru / Start-up Entrepreneur 9)",
        "Start-up Genius (Tech Guru / Start-up Entrepreneur 10)",
    },
    "Writer": {
        "Blogger (Writer 2)",
        "Freelance Article Writer (Writer 3)",
        "Advice Columnist (Writer 4)",
        "Regular Contributor (Writer 5)",
        "Short Story Writer (Writer / Author 6)",
        "Novelist (Writer / Author 7)",
        "Fan Favorite (Writer / Author 8)",
        "Bestselling Author (Writer / Author 9)",
        "Creator of Worlds (Writer / Author 10)",
        "Page Two Journalist (Writer / Journalist 6)",
        "Front Page Writer (Writer / Journalist 7)",
        "Investigative Journalist (Writer / Journalist 8)",
        "Editor-in-Chief (Writer / Journalist 9)",
        "Scribe of History (Writer / Journalist 10)",
    },
    "Author": {
        "Short Story Writer (Writer / Author 6)",
        "Novelist (Writer / Author 7)",
        "Fan Favorite (Writer / Author 8)",
        "Bestselling Author (Writer / Author 9)",
        "Creator of Worlds (Writer / Author 10)",
    },
    "Journalist": {
        "Page Two Journalist (Writer / Journalist 6)",
        "Front Page Writer (Writer / Journalist 7)",
        "Investigative Journalist (Writer / Journalist 8)",
        "Editor-in-Chief (Writer / Journalist 9)",
        "Scribe of History (Writer / Journalist 10)",
    }
}

item_name_groups: dict[str, set[str]] = {
    "Music": {
        "Guitar Skill",
        "Violin Skill",
        "Piano Skill",
    },
    "Food": {
        "Gourmet Skill",
        "Cooking Skill",
        "Mixology Skill",
    },
    "Computer": {
        "Programming Skill",
        "Video Gaming Skill"
    }
}