#!/usr/bin/env python3

import os, sys, json
import zlib

here = os.path.dirname(__file__)
output_gz = os.path.join(here, "ap-dump.json.gz")
output_py = os.path.join(here, "__init__.py")

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("input", metavar="path/to/script-output/ap-dump.json", help=
        "See FactorioInformationExtractor for how to generate this.")
    args = parser.parse_args()

    process(args.input)

header = """\
#################################################
# This file is generated by ./import-ap-dump.py #
#################################################

import functools
@functools.lru_cache()
def get_data():
    import os, zlib, json
    with open(os.path.join(os.path.dirname(__file__), 'ap-dump.json.gz'), 'rb') as f:
        data = json.loads(zlib.decompress(f.read(), wbits=31))
    return data
"""

def process(input_path):
    # Import the json data and gzip it.
    with open(input_path, "rb") as in_f:
        data = json.load(in_f)
        in_f.seek(0)
        with open(output_gz, "wb") as out_f:
            out_f.write(zlib.compress(in_f.read(), wbits=31))

    # Generate constants for some things we might want to refer to.
    lines = []
    exports = ["get_data"]
    for group_name, items in data.items():
        group_title = to_title(group_name)
        lines.extend([
            "",
            "class {}:".format(group_title),
        ])
        exports.append(group_title)
        for name in items.keys():
            lines.append(
                "    {} = {}".format(to_snake(name), repr(name)),
            )

    with open(output_py, "w") as f:
        f.write(header)
        f.write("\n__all__ = {}\n".format(repr(exports)))
        f.writelines(line + "\n" for line in lines)

    # Make there are no broken names.
    from __init__ import get_data
    assert get_data() == data

def to_title(name):
    return sanitize(name.title().replace("_", "").replace("-", ""))
def to_snake(name):
    return sanitize(name.lower().replace("-", "_"))
def sanitize(name):
    if name[0].isdigit():
        name = "_" + name
    return name

if __name__ == "__main__":
    main()
