"""
Big Arrays
"""

all_species: list[tuple[str, str, int]] = [
    ("SPECIES_BULBASAUR", "Bulbasaur", 1),
    ("SPECIES_IVYSAUR", "Ivysaur", 2),
    ("SPECIES_VENUSAUR", "Venusaur", 3),
    ("SPECIES_CHARMANDER", "Charmander", 4),
    ("SPECIES_CHARMELEON", "Charmeleon", 5),
    ("SPECIES_CHARIZARD", "Charizard", 6),
    ("SPECIES_SQUIRTLE", "Squirtle", 7),
    ("SPECIES_WARTORTLE", "Wartortle", 8),
    ("SPECIES_BLASTOISE", "Blastoise", 9),
    ("SPECIES_CATERPIE", "Caterpie", 10),
    ("SPECIES_METAPOD", "Metapod", 11),
    ("SPECIES_BUTTERFREE", "Butterfree", 12),
    ("SPECIES_WEEDLE", "Weedle", 13),
    ("SPECIES_KAKUNA", "Kakuna", 14),
    ("SPECIES_BEEDRILL", "Beedrill", 15),
    ("SPECIES_PIDGEY", "Pidgey", 16),
    ("SPECIES_PIDGEOTTO", "Pidgeotto", 17),
    ("SPECIES_PIDGEOT", "Pidgeot", 18),
    ("SPECIES_RATTATA", "Rattata", 19),
    ("SPECIES_RATICATE", "Raticate", 20),
    ("SPECIES_SPEAROW", "Spearow", 21),
    ("SPECIES_FEAROW", "Fearow", 22),
    ("SPECIES_EKANS", "Ekans", 23),
    ("SPECIES_ARBOK", "Arbok", 24),
    ("SPECIES_PIKACHU", "Pikachu", 25),
    ("SPECIES_RAICHU", "Raichu", 26),
    ("SPECIES_SANDSHREW", "Sandshrew", 27),
    ("SPECIES_SANDSLASH", "Sandslash", 28),
    ("SPECIES_NIDORAN_F", "Nidoran Female", 29),
    ("SPECIES_NIDORINA", "Nidorina", 30),
    ("SPECIES_NIDOQUEEN", "Nidoqueen", 31),
    ("SPECIES_NIDORAN_M", "Nidoran Male", 32),
    ("SPECIES_NIDORINO", "Nidorino", 33),
    ("SPECIES_NIDOKING", "Nidoking", 34),
    ("SPECIES_CLEFAIRY", "Clefairy", 35),
    ("SPECIES_CLEFABLE", "Clefable", 36),
    ("SPECIES_VULPIX", "Vulpix", 37),
    ("SPECIES_NINETALES", "Ninetales", 38),
    ("SPECIES_JIGGLYPUFF", "Jigglypuff", 39),
    ("SPECIES_WIGGLYTUFF", "Wigglytuff", 40),
    ("SPECIES_ZUBAT", "Zubat", 41),
    ("SPECIES_GOLBAT", "Golbat", 42),
    ("SPECIES_ODDISH", "Oddish", 43),
    ("SPECIES_GLOOM", "Gloom", 44),
    ("SPECIES_VILEPLUME", "Vileplume", 45),
    ("SPECIES_PARAS", "Paras", 46),
    ("SPECIES_PARASECT", "Parasect", 47),
    ("SPECIES_VENONAT", "Venonat", 48),
    ("SPECIES_VENOMOTH", "Venomoth", 49),
    ("SPECIES_DIGLETT", "Diglett", 50),
    ("SPECIES_DUGTRIO", "Dugtrio", 51),
    ("SPECIES_MEOWTH", "Meowth", 52),
    ("SPECIES_PERSIAN", "Persian", 53),
    ("SPECIES_PSYDUCK", "Psyduck", 54),
    ("SPECIES_GOLDUCK", "Golduck", 55),
    ("SPECIES_MANKEY", "Mankey", 56),
    ("SPECIES_PRIMEAPE", "Primeape", 57),
    ("SPECIES_GROWLITHE", "Growlithe", 58),
    ("SPECIES_ARCANINE", "Arcanine", 59),
    ("SPECIES_POLIWAG", "Poliwag", 60),
    ("SPECIES_POLIWHIRL", "Poliwhirl", 61),
    ("SPECIES_POLIWRATH", "Poliwrath", 62),
    ("SPECIES_ABRA", "Abra", 63),
    ("SPECIES_KADABRA", "Kadabra", 64),
    ("SPECIES_ALAKAZAM", "Alakazam", 65),
    ("SPECIES_MACHOP", "Machop", 66),
    ("SPECIES_MACHOKE", "Machoke", 67),
    ("SPECIES_MACHAMP", "Machamp", 68),
    ("SPECIES_BELLSPROUT", "Bellsprout", 69),
    ("SPECIES_WEEPINBELL", "Weepinbell", 70),
    ("SPECIES_VICTREEBEL", "Victreebel", 71),
    ("SPECIES_TENTACOOL", "Tentacool", 72),
    ("SPECIES_TENTACRUEL", "Tentacruel", 73),
    ("SPECIES_GEODUDE", "Geodude", 74),
    ("SPECIES_GRAVELER", "Graveler", 75),
    ("SPECIES_GOLEM", "Golem", 76),
    ("SPECIES_PONYTA", "Ponyta", 77),
    ("SPECIES_RAPIDASH", "Rapidash", 78),
    ("SPECIES_SLOWPOKE", "Slowpoke", 79),
    ("SPECIES_SLOWBRO", "Slowbro", 80),
    ("SPECIES_MAGNEMITE", "Magnemite", 81),
    ("SPECIES_MAGNETON", "Magneton", 82),
    ("SPECIES_FARFETCHD", "Farfetch'd", 83),
    ("SPECIES_DODUO", "Doduo", 84),
    ("SPECIES_DODRIO", "Dodrio", 85),
    ("SPECIES_SEEL", "Seel", 86),
    ("SPECIES_DEWGONG", "Dewgong", 87),
    ("SPECIES_GRIMER", "Grimer", 88),
    ("SPECIES_MUK", "Muk", 89),
    ("SPECIES_SHELLDER", "Shellder", 90),
    ("SPECIES_CLOYSTER", "Cloyster", 91),
    ("SPECIES_GASTLY", "Gastly", 92),
    ("SPECIES_HAUNTER", "Haunter", 93),
    ("SPECIES_GENGAR", "Gengar", 94),
    ("SPECIES_ONIX", "Onix", 95),
    ("SPECIES_DROWZEE", "Drowzee", 96),
    ("SPECIES_HYPNO", "Hypno", 97),
    ("SPECIES_KRABBY", "Krabby", 98),
    ("SPECIES_KINGLER", "Kingler", 99),
    ("SPECIES_VOLTORB", "Voltorb", 100),
    ("SPECIES_ELECTRODE", "Electrode", 101),
    ("SPECIES_EXEGGCUTE", "Exeggcute", 102),
    ("SPECIES_EXEGGUTOR", "Exeggutor", 103),
    ("SPECIES_CUBONE", "Cubone", 104),
    ("SPECIES_MAROWAK", "Marowak", 105),
    ("SPECIES_HITMONLEE", "Hitmonlee", 106),
    ("SPECIES_HITMONCHAN", "Hitmonchan", 107),
    ("SPECIES_LICKITUNG", "Lickitung", 108),
    ("SPECIES_KOFFING", "Koffing", 109),
    ("SPECIES_WEEZING", "Weezing", 110),
    ("SPECIES_RHYHORN", "Rhyhorn", 111),
    ("SPECIES_RHYDON", "Rhydon", 112),
    ("SPECIES_CHANSEY", "Chansey", 113),
    ("SPECIES_TANGELA", "Tangela", 114),
    ("SPECIES_KANGASKHAN", "Kangaskhan", 115),
    ("SPECIES_HORSEA", "Horsea", 116),
    ("SPECIES_SEADRA", "Seadra", 117),
    ("SPECIES_GOLDEEN", "Goldeen", 118),
    ("SPECIES_SEAKING", "Seaking", 119),
    ("SPECIES_STARYU", "Staryu", 120),
    ("SPECIES_STARMIE", "Starmie", 121),
    ("SPECIES_MR_MIME", "Mr. Mime", 122),
    ("SPECIES_SCYTHER", "Scyther", 123),
    ("SPECIES_JYNX", "Jynx", 124),
    ("SPECIES_ELECTABUZZ", "Electabuzz", 125),
    ("SPECIES_MAGMAR", "Magmar", 126),
    ("SPECIES_PINSIR", "Pinsir", 127),
    ("SPECIES_TAUROS", "Tauros", 128),
    ("SPECIES_MAGIKARP", "Magikarp", 129),
    ("SPECIES_GYARADOS", "Gyarados", 130),
    ("SPECIES_LAPRAS", "Lapras", 131),
    ("SPECIES_DITTO", "Ditto", 132),
    ("SPECIES_EEVEE", "Eevee", 133),
    ("SPECIES_VAPOREON", "Vaporeon", 134),
    ("SPECIES_JOLTEON", "Jolteon", 135),
    ("SPECIES_FLAREON", "Flareon", 136),
    ("SPECIES_PORYGON", "Porygon", 137),
    ("SPECIES_OMANYTE", "Omanyte", 138),
    ("SPECIES_OMASTAR", "Omastar", 139),
    ("SPECIES_KABUTO", "Kabuto", 140),
    ("SPECIES_KABUTOPS", "Kabutops", 141),
    ("SPECIES_AERODACTYL", "Aerodactyl", 142),
    ("SPECIES_SNORLAX", "Snorlax", 143),
    ("SPECIES_ARTICUNO", "Articuno", 144),
    ("SPECIES_ZAPDOS", "Zapdos", 145),
    ("SPECIES_MOLTRES", "Moltres", 146),
    ("SPECIES_DRATINI", "Dratini", 147),
    ("SPECIES_DRAGONAIR", "Dragonair", 148),
    ("SPECIES_DRAGONITE", "Dragonite", 149),
    ("SPECIES_MEWTWO", "Mewtwo", 150),
    ("SPECIES_MEW", "Mew", 151),
    ("SPECIES_CHIKORITA", "Chikorita", 152),
    ("SPECIES_BAYLEEF", "Bayleef", 153),
    ("SPECIES_MEGANIUM", "Meganium", 154),
    ("SPECIES_CYNDAQUIL", "Cyndaquil", 155),
    ("SPECIES_QUILAVA", "Quilava", 156),
    ("SPECIES_TYPHLOSION", "Typhlosion", 157),
    ("SPECIES_TOTODILE", "Totodile", 158),
    ("SPECIES_CROCONAW", "Croconaw", 159),
    ("SPECIES_FERALIGATR", "Feraligatr", 160),
    ("SPECIES_SENTRET", "Sentret", 161),
    ("SPECIES_FURRET", "Furret", 162),
    ("SPECIES_HOOTHOOT", "Hoothoot", 163),
    ("SPECIES_NOCTOWL", "Noctowl", 164),
    ("SPECIES_LEDYBA", "Ledyba", 165),
    ("SPECIES_LEDIAN", "Ledian", 166),
    ("SPECIES_SPINARAK", "Spinarak", 167),
    ("SPECIES_ARIADOS", "Ariados", 168),
    ("SPECIES_CROBAT", "Crobat", 169),
    ("SPECIES_CHINCHOU", "Chinchou", 170),
    ("SPECIES_LANTURN", "Lanturn", 171),
    ("SPECIES_PICHU", "Pichu", 172),
    ("SPECIES_CLEFFA", "Cleffa", 173),
    ("SPECIES_IGGLYBUFF", "Igglybuff", 174),
    ("SPECIES_TOGEPI", "Togepi", 175),
    ("SPECIES_TOGETIC", "Togetic", 176),
    ("SPECIES_NATU", "Natu", 177),
    ("SPECIES_XATU", "Xatu", 178),
    ("SPECIES_MAREEP", "Mareep", 179),
    ("SPECIES_FLAAFFY", "Flaaffy", 180),
    ("SPECIES_AMPHAROS", "Ampharos", 181),
    ("SPECIES_BELLOSSOM", "Bellossom", 182),
    ("SPECIES_MARILL", "Marill", 183),
    ("SPECIES_AZUMARILL", "Azumarill", 184),
    ("SPECIES_SUDOWOODO", "Sudowoodo", 185),
    ("SPECIES_POLITOED", "Politoed", 186),
    ("SPECIES_HOPPIP", "Hoppip", 187),
    ("SPECIES_SKIPLOOM", "Skiploom", 188),
    ("SPECIES_JUMPLUFF", "Jumpluff", 189),
    ("SPECIES_AIPOM", "Aipom", 190),
    ("SPECIES_SUNKERN", "Sunkern", 191),
    ("SPECIES_SUNFLORA", "Sunflora", 192),
    ("SPECIES_YANMA", "Yanma", 193),
    ("SPECIES_WOOPER", "Wooper", 194),
    ("SPECIES_QUAGSIRE", "Quagsire", 195),
    ("SPECIES_ESPEON", "Espeon", 196),
    ("SPECIES_UMBREON", "Umbreon", 197),
    ("SPECIES_MURKROW", "Murkrow", 198),
    ("SPECIES_SLOWKING", "Slowking", 199),
    ("SPECIES_MISDREAVUS", "Misdreavus", 200),
    ("SPECIES_UNOWN", "Unown", 201),
    ("SPECIES_WOBBUFFET", "Wobbuffet", 202),
    ("SPECIES_GIRAFARIG", "Girafarig", 203),
    ("SPECIES_PINECO", "Pineco", 204),
    ("SPECIES_FORRETRESS", "Forretress", 205),
    ("SPECIES_DUNSPARCE", "Dunsparce", 206),
    ("SPECIES_GLIGAR", "Gligar", 207),
    ("SPECIES_STEELIX", "Steelix", 208),
    ("SPECIES_SNUBBULL", "Snubbull", 209),
    ("SPECIES_GRANBULL", "Granbull", 210),
    ("SPECIES_QWILFISH", "Qwilfish", 211),
    ("SPECIES_SCIZOR", "Scizor", 212),
    ("SPECIES_SHUCKLE", "Shuckle", 213),
    ("SPECIES_HERACROSS", "Heracross", 214),
    ("SPECIES_SNEASEL", "Sneasel", 215),
    ("SPECIES_TEDDIURSA", "Teddiursa", 216),
    ("SPECIES_URSARING", "Ursaring", 217),
    ("SPECIES_SLUGMA", "Slugma", 218),
    ("SPECIES_MAGCARGO", "Magcargo", 219),
    ("SPECIES_SWINUB", "Swinub", 220),
    ("SPECIES_PILOSWINE", "Piloswine", 221),
    ("SPECIES_CORSOLA", "Corsola", 222),
    ("SPECIES_REMORAID", "Remoraid", 223),
    ("SPECIES_OCTILLERY", "Octillery", 224),
    ("SPECIES_DELIBIRD", "Delibird", 225),
    ("SPECIES_MANTINE", "Mantine", 226),
    ("SPECIES_SKARMORY", "Skarmory", 227),
    ("SPECIES_HOUNDOUR", "Houndour", 228),
    ("SPECIES_HOUNDOOM", "Houndoom", 229),
    ("SPECIES_KINGDRA", "Kingdra", 230),
    ("SPECIES_PHANPY", "Phanpy", 231),
    ("SPECIES_DONPHAN", "Donphan", 232),
    ("SPECIES_PORYGON2", "Porygon2", 233),
    ("SPECIES_STANTLER", "Stantler", 234),
    ("SPECIES_SMEARGLE", "Smeargle", 235),
    ("SPECIES_TYROGUE", "Tyrogue", 236),
    ("SPECIES_HITMONTOP", "Hitmontop", 237),
    ("SPECIES_SMOOCHUM", "Smoochum", 238),
    ("SPECIES_ELEKID", "Elekid", 239),
    ("SPECIES_MAGBY", "Magby", 240),
    ("SPECIES_MILTANK", "Miltank", 241),
    ("SPECIES_BLISSEY", "Blissey", 242),
    ("SPECIES_RAIKOU", "Raikou", 243),
    ("SPECIES_ENTEI", "Entei", 244),
    ("SPECIES_SUICUNE", "Suicune", 245),
    ("SPECIES_LARVITAR", "Larvitar", 246),
    ("SPECIES_PUPITAR", "Pupitar", 247),
    ("SPECIES_TYRANITAR", "Tyranitar", 248),
    ("SPECIES_LUGIA", "Lugia", 249),
    ("SPECIES_HO_OH", "Ho-Oh", 250),
    ("SPECIES_CELEBI", "Celebi", 251),
    ("SPECIES_TREECKO", "Treecko", 252),
    ("SPECIES_GROVYLE", "Grovyle", 253),
    ("SPECIES_SCEPTILE", "Sceptile", 254),
    ("SPECIES_TORCHIC", "Torchic", 255),
    ("SPECIES_COMBUSKEN", "Combusken", 256),
    ("SPECIES_BLAZIKEN", "Blaziken", 257),
    ("SPECIES_MUDKIP", "Mudkip", 258),
    ("SPECIES_MARSHTOMP", "Marshtomp", 259),
    ("SPECIES_SWAMPERT", "Swampert", 260),
    ("SPECIES_POOCHYENA", "Poochyena", 261),
    ("SPECIES_MIGHTYENA", "Mightyena", 262),
    ("SPECIES_ZIGZAGOON", "Zigzagoon", 263),
    ("SPECIES_LINOONE", "Linoone", 264),
    ("SPECIES_WURMPLE", "Wurmple", 265),
    ("SPECIES_SILCOON", "Silcoon", 266),
    ("SPECIES_BEAUTIFLY", "Beautifly", 267),
    ("SPECIES_CASCOON", "Cascoon", 268),
    ("SPECIES_DUSTOX", "Dustox", 269),
    ("SPECIES_LOTAD", "Lotad", 270),
    ("SPECIES_LOMBRE", "Lombre", 271),
    ("SPECIES_LUDICOLO", "Ludicolo", 272),
    ("SPECIES_SEEDOT", "Seedot", 273),
    ("SPECIES_NUZLEAF", "Nuzleaf", 274),
    ("SPECIES_SHIFTRY", "Shiftry", 275),
    ("SPECIES_TAILLOW", "Taillow", 276),
    ("SPECIES_SWELLOW", "Swellow", 277),
    ("SPECIES_WINGULL", "Wingull", 278),
    ("SPECIES_PELIPPER", "Pelipper", 279),
    ("SPECIES_RALTS", "Ralts", 280),
    ("SPECIES_KIRLIA", "Kirlia", 281),
    ("SPECIES_GARDEVOIR", "Gardevoir", 282),
    ("SPECIES_SURSKIT", "Surskit", 283),
    ("SPECIES_MASQUERAIN", "Masquerain", 284),
    ("SPECIES_SHROOMISH", "Shroomish", 285),
    ("SPECIES_BRELOOM", "Breloom", 286),
    ("SPECIES_SLAKOTH", "Slakoth", 287),
    ("SPECIES_VIGOROTH", "Vigoroth", 288),
    ("SPECIES_SLAKING", "Slaking", 289),
    ("SPECIES_NINCADA", "Nincada", 290),
    ("SPECIES_NINJASK", "Ninjask", 291),
    ("SPECIES_SHEDINJA", "Shedinja", 292),
    ("SPECIES_WHISMUR", "Whismur", 293),
    ("SPECIES_LOUDRED", "Loudred", 294),
    ("SPECIES_EXPLOUD", "Exploud", 295),
    ("SPECIES_MAKUHITA", "Makuhita", 296),
    ("SPECIES_HARIYAMA", "Hariyama", 297),
    ("SPECIES_AZURILL", "Azurill", 298),
    ("SPECIES_NOSEPASS", "Nosepass", 299),
    ("SPECIES_SKITTY", "Skitty", 300),
    ("SPECIES_DELCATTY", "Delcatty", 301),
    ("SPECIES_SABLEYE", "Sableye", 302),
    ("SPECIES_MAWILE", "Mawile", 303),
    ("SPECIES_ARON", "Aron", 304),
    ("SPECIES_LAIRON", "Lairon", 305),
    ("SPECIES_AGGRON", "Aggron", 306),
    ("SPECIES_MEDITITE", "Meditite", 307),
    ("SPECIES_MEDICHAM", "Medicham", 308),
    ("SPECIES_ELECTRIKE", "Electrike", 309),
    ("SPECIES_MANECTRIC", "Manectric", 310),
    ("SPECIES_PLUSLE", "Plusle", 311),
    ("SPECIES_MINUN", "Minun", 312),
    ("SPECIES_VOLBEAT", "Volbeat", 313),
    ("SPECIES_ILLUMISE", "Illumise", 314),
    ("SPECIES_ROSELIA", "Roselia", 315),
    ("SPECIES_GULPIN", "Gulpin", 316),
    ("SPECIES_SWALOT", "Swalot", 317),
    ("SPECIES_CARVANHA", "Carvanha", 318),
    ("SPECIES_SHARPEDO", "Sharpedo", 319),
    ("SPECIES_WAILMER", "Wailmer", 320),
    ("SPECIES_WAILORD", "Wailord", 321),
    ("SPECIES_NUMEL", "Numel", 322),
    ("SPECIES_CAMERUPT", "Camerupt", 323),
    ("SPECIES_TORKOAL", "Torkoal", 324),
    ("SPECIES_SPOINK", "Spoink", 325),
    ("SPECIES_GRUMPIG", "Grumpig", 326),
    ("SPECIES_SPINDA", "Spinda", 327),
    ("SPECIES_TRAPINCH", "Trapinch", 328),
    ("SPECIES_VIBRAVA", "Vibrava", 329),
    ("SPECIES_FLYGON", "Flygon", 330),
    ("SPECIES_CACNEA", "Cacnea", 331),
    ("SPECIES_CACTURNE", "Cacturne", 332),
    ("SPECIES_SWABLU", "Swablu", 333),
    ("SPECIES_ALTARIA", "Altaria", 334),
    ("SPECIES_ZANGOOSE", "Zangoose", 335),
    ("SPECIES_SEVIPER", "Seviper", 336),
    ("SPECIES_LUNATONE", "Lunatone", 337),
    ("SPECIES_SOLROCK", "Solrock", 338),
    ("SPECIES_BARBOACH", "Barboach", 339),
    ("SPECIES_WHISCASH", "Whiscash", 340),
    ("SPECIES_CORPHISH", "Corphish", 341),
    ("SPECIES_CRAWDAUNT", "Crawdaunt", 342),
    ("SPECIES_BALTOY", "Baltoy", 343),
    ("SPECIES_CLAYDOL", "Claydol", 344),
    ("SPECIES_LILEEP", "Lileep", 345),
    ("SPECIES_CRADILY", "Cradily", 346),
    ("SPECIES_ANORITH", "Anorith", 347),
    ("SPECIES_ARMALDO", "Armaldo", 348),
    ("SPECIES_FEEBAS", "Feebas", 349),
    ("SPECIES_MILOTIC", "Milotic", 350),
    ("SPECIES_CASTFORM", "Castform", 351),
    ("SPECIES_KECLEON", "Kecleon", 352),
    ("SPECIES_SHUPPET", "Shuppet", 353),
    ("SPECIES_BANETTE", "Banette", 354),
    ("SPECIES_DUSKULL", "Duskull", 355),
    ("SPECIES_DUSCLOPS", "Dusclops", 356),
    ("SPECIES_TROPIUS", "Tropius", 357),
    ("SPECIES_CHIMECHO", "Chimecho", 358),
    ("SPECIES_ABSOL", "Absol", 359),
    ("SPECIES_WYNAUT", "Wynaut", 360),
    ("SPECIES_SNORUNT", "Snorunt", 361),
    ("SPECIES_GLALIE", "Glalie", 362),
    ("SPECIES_SPHEAL", "Spheal", 363),
    ("SPECIES_SEALEO", "Sealeo", 364),
    ("SPECIES_WALREIN", "Walrein", 365),
    ("SPECIES_CLAMPERL", "Clamperl", 366),
    ("SPECIES_HUNTAIL", "Huntail", 367),
    ("SPECIES_GOREBYSS", "Gorebyss", 368),
    ("SPECIES_RELICANTH", "Relicanth", 369),
    ("SPECIES_LUVDISC", "Luvdisc", 370),
    ("SPECIES_BAGON", "Bagon", 371),
    ("SPECIES_SHELGON", "Shelgon", 372),
    ("SPECIES_SALAMENCE", "Salamence", 373),
    ("SPECIES_BELDUM", "Beldum", 374),
    ("SPECIES_METANG", "Metang", 375),
    ("SPECIES_METAGROSS", "Metagross", 376),
    ("SPECIES_REGIROCK", "Regirock", 377),
    ("SPECIES_REGICE", "Regice", 378),
    ("SPECIES_REGISTEEL", "Registeel", 379),
    ("SPECIES_LATIAS", "Latias", 380),
    ("SPECIES_LATIOS", "Latios", 381),
    ("SPECIES_KYOGRE", "Kyogre", 382),
    ("SPECIES_GROUDON", "Groudon", 383),
    ("SPECIES_RAYQUAZA", "Rayquaza", 384),
    ("SPECIES_JIRACHI", "Jirachi", 385),
    ("SPECIES_DEOXYS", "Deoxys", 386),
    ("SPECIES_TURTWIG", "Turtwig", 387),
    ("SPECIES_GROTLE", "Grotle", 388),
    ("SPECIES_TORTERRA", "Torterra", 389),
    ("SPECIES_CHIMCHAR", "Chimchar", 390),
    ("SPECIES_MONFERNO", "Monferno", 391),
    ("SPECIES_INFERNAPE", "Infernape", 392),
    ("SPECIES_PIPLUP", "Piplup", 393),
    ("SPECIES_PRINPLUP", "Prinplup", 394),
    ("SPECIES_EMPOLEON", "Empoleon", 395),
    ("SPECIES_STARLY", "Starly", 396),
    ("SPECIES_STARAVIA", "Staravia", 397),
    ("SPECIES_STARAPTOR", "Staraptor", 398),
    ("SPECIES_BIDOOF", "Bidoof", 399),
    ("SPECIES_BIBAREL", "Bibarel", 400),
    ("SPECIES_KRICKETOT", "Kricketot", 401),
    ("SPECIES_KRICKETUNE", "Kricketune", 402),
    ("SPECIES_SHINX", "Shinx", 403),
    ("SPECIES_LUXIO", "Luxio", 404),
    ("SPECIES_LUXRAY", "Luxray", 405),
    ("SPECIES_BUDEW", "Budew", 406),
    ("SPECIES_ROSERADE", "Roserade", 407),
    ("SPECIES_CRANIDOS", "Cranidos", 408),
    ("SPECIES_RAMPARDOS", "Rampardos", 409),
    ("SPECIES_SHIELDON", "Shieldon", 410),
    ("SPECIES_BASTIODON", "Bastiodon", 411),
    ("SPECIES_BURMY", "Burmy", 412),
    ("SPECIES_WORMADAM", "Wormadam", 413),
    ("SPECIES_MOTHIM", "Mothim", 414),
    ("SPECIES_COMBEE", "Combee", 415),
    ("SPECIES_VESPIQUEN", "Vespiquen", 416),
    ("SPECIES_PACHIRISU", "Pachirisu", 417),
    ("SPECIES_BUIZEL", "Buizel", 418),
    ("SPECIES_FLOATZEL", "Floatzel", 419),
    ("SPECIES_CHERUBI", "Cherubi", 420),
    ("SPECIES_CHERRIM", "Cherrim", 421),
    ("SPECIES_SHELLOS", "Shellos", 422),
    ("SPECIES_GASTRODON", "Gastrodon", 423),
    ("SPECIES_AMBIPOM", "Ambipom", 424),
    ("SPECIES_DRIFLOON", "Drifloon", 425),
    ("SPECIES_DRIFBLIM", "Drifblim", 426),
    ("SPECIES_BUNEARY", "Buneary", 427),
    ("SPECIES_LOPUNNY", "Lopunny", 428),
    ("SPECIES_MISMAGIUS", "Mismagius", 429),
    ("SPECIES_HONCHKROW", "Honchkrow", 430),
    ("SPECIES_GLAMEOW", "Glameow", 431),
    ("SPECIES_PURUGLY", "Purugly", 432),
    ("SPECIES_CHINGLING", "Chingling", 433),
    ("SPECIES_STUNKY", "Stunky", 434),
    ("SPECIES_SKUNTANK", "Skuntank", 435),
    ("SPECIES_BRONZOR", "Bronzor", 436),
    ("SPECIES_BRONZONG", "Bronzong", 437),
    ("SPECIES_BONSLY", "Bonsly", 438),
    ("SPECIES_MIME_JR", "Mime Jr", 439),
    ("SPECIES_HAPPINY", "Happiny", 440),
    ("SPECIES_CHATOT", "Chatot", 441),
    ("SPECIES_SPIRITOMB", "Spiritomb", 442),
    ("SPECIES_GIBLE", "Gible", 443),
    ("SPECIES_GABITE", "Gabite", 444),
    ("SPECIES_GARCHOMP", "Garchomp", 445),
    ("SPECIES_MUNCHLAX", "Munchlax", 446),
    ("SPECIES_RIOLU", "Riolu", 447),
    ("SPECIES_LUCARIO", "Lucario", 448),
    ("SPECIES_HIPPOPOTAS", "Hippopotas", 449),
    ("SPECIES_HIPPOWDON", "Hippowdon", 450),
    ("SPECIES_SKORUPI", "Skorupi", 451),
    ("SPECIES_DRAPION", "Drapion", 452),
    ("SPECIES_CROAGUNK", "Croagunk", 453),
    ("SPECIES_TOXICROAK", "Toxicroak", 454),
    ("SPECIES_CARNIVINE", "Carnivine", 455),
    ("SPECIES_FINNEON", "Finneon", 456),
    ("SPECIES_LUMINEON", "Lumineon", 457),
    ("SPECIES_MANTYKE", "Mantyke", 458),
    ("SPECIES_SNOVER", "Snover", 459),
    ("SPECIES_ABOMASNOW", "Abomasnow", 460),
    ("SPECIES_WEAVILE", "Weavile", 461),
    ("SPECIES_MAGNEZONE", "Magnezone", 462),
    ("SPECIES_LICKILICKY", "Lickilicky", 463),
    ("SPECIES_RHYPERIOR", "Rhyperior", 464),
    ("SPECIES_TANGROWTH", "Tangrowth", 465),
    ("SPECIES_ELECTIVIRE", "Electivire", 466),
    ("SPECIES_MAGMORTAR", "Magmortar", 467),
    ("SPECIES_TOGEKISS", "Togekiss", 468),
    ("SPECIES_YANMEGA", "Yanmega", 469),
    ("SPECIES_LEAFEON", "Leafeon", 470),
    ("SPECIES_GLACEON", "Glaceon", 471),
    ("SPECIES_GLISCOR", "Gliscor", 472),
    ("SPECIES_MAMOSWINE", "Mamoswine", 473),
    ("SPECIES_PORYGON_Z", "Porygon Z", 474),
    ("SPECIES_GALLADE", "Gallade", 475),
    ("SPECIES_PROBOPASS", "Probopass", 476),
    ("SPECIES_DUSKNOIR", "Dusknoir", 477),
    ("SPECIES_FROSLASS", "Froslass", 478),
    ("SPECIES_ROTOM", "Rotom", 479),
    ("SPECIES_UXIE", "Uxie", 480),
    ("SPECIES_MESPRIT", "Mesprit", 481),
    ("SPECIES_AZELF", "Azelf", 482),
    ("SPECIES_DIALGA", "Dialga", 483),
    ("SPECIES_PALKIA", "Palkia", 484),
    ("SPECIES_HEATRAN", "Heatran", 485),
    ("SPECIES_REGIGIGAS", "Regigigas", 486),
    ("SPECIES_GIRATINA", "Giratina", 487),
    ("SPECIES_CRESSELIA", "Cresselia", 488),
    ("SPECIES_PHIONE", "Phione", 489),
    ("SPECIES_MANAPHY", "Manaphy", 490),
    ("SPECIES_DARKRAI", "Darkrai", 491),
    ("SPECIES_SHAYMIN", "Shaymin", 492),
    ("SPECIES_ARCEUS", "Arceus", 493),
    ("SPECIES_VICTINI", "Victini", 494),
    ("SPECIES_SNIVY", "Snivy", 495),
    ("SPECIES_SERVINE", "Servine", 496),
    ("SPECIES_SERPERIOR", "Serperior", 497),
    ("SPECIES_TEPIG", "Tepig", 498),
    ("SPECIES_PIGNITE", "Pignite", 499),
    ("SPECIES_EMBOAR", "Emboar", 500),
    ("SPECIES_OSHAWOTT", "Oshawott", 501),
    ("SPECIES_DEWOTT", "Dewott", 502),
    ("SPECIES_SAMUROTT", "Samurott", 503),
    ("SPECIES_PATRAT", "Patrat", 504),
    ("SPECIES_WATCHOG", "Watchog", 505),
    ("SPECIES_LILLIPUP", "Lillipup", 506),
    ("SPECIES_HERDIER", "Herdier", 507),
    ("SPECIES_STOUTLAND", "Stoutland", 508),
    ("SPECIES_PURRLOIN", "Purrloin", 509),
    ("SPECIES_LIEPARD", "Liepard", 510),
    ("SPECIES_PANSAGE", "Pansage", 511),
    ("SPECIES_SIMISAGE", "Simisage", 512),
    ("SPECIES_PANSEAR", "Pansear", 513),
    ("SPECIES_SIMISEAR", "Simisear", 514),
    ("SPECIES_PANPOUR", "Panpour", 515),
    ("SPECIES_SIMIPOUR", "Simipour", 516),
    ("SPECIES_MUNNA", "Munna", 517),
    ("SPECIES_MUSHARNA", "Musharna", 518),
    ("SPECIES_PIDOVE", "Pidove", 519),
    ("SPECIES_TRANQUILL", "Tranquill", 520),
    ("SPECIES_UNFEZANT", "Unfezant", 521),
    ("SPECIES_BLITZLE", "Blitzle", 522),
    ("SPECIES_ZEBSTRIKA", "Zebstrika", 523),
    ("SPECIES_ROGGENROLA", "Roggenrola", 524),
    ("SPECIES_BOLDORE", "Boldore", 525),
    ("SPECIES_GIGALITH", "Gigalith", 526),
    ("SPECIES_WOOBAT", "Woobat", 527),
    ("SPECIES_SWOOBAT", "Swoobat", 528),
    ("SPECIES_DRILBUR", "Drilbur", 529),
    ("SPECIES_EXCADRILL", "Excadrill", 530),
    ("SPECIES_AUDINO", "Audino", 531),
    ("SPECIES_TIMBURR", "Timburr", 532),
    ("SPECIES_GURDURR", "Gurdurr", 533),
    ("SPECIES_CONKELDURR", "Conkeldurr", 534),
    ("SPECIES_TYMPOLE", "Tympole", 535),
    ("SPECIES_PALPITOAD", "Palpitoad", 536),
    ("SPECIES_SEISMITOAD", "Seismitoad", 537),
    ("SPECIES_THROH", "Throh", 538),
    ("SPECIES_SAWK", "Sawk", 539),
    ("SPECIES_SEWADDLE", "Sewaddle", 540),
    ("SPECIES_SWADLOON", "Swadloon", 541),
    ("SPECIES_LEAVANNY", "Leavanny", 542),
    ("SPECIES_VENIPEDE", "Venipede", 543),
    ("SPECIES_WHIRLIPEDE", "Whirlipede", 544),
    ("SPECIES_SCOLIPEDE", "Scolipede", 545),
    ("SPECIES_COTTONEE", "Cottonee", 546),
    ("SPECIES_WHIMSICOTT", "Whimsicott", 547),
    ("SPECIES_PETILIL", "Petilil", 548),
    ("SPECIES_LILLIGANT", "Lilligant", 549),
    ("SPECIES_BASCULIN", "Basculin", 550),
    ("SPECIES_SANDILE", "Sandile", 551),
    ("SPECIES_KROKOROK", "Krokorok", 552),
    ("SPECIES_KROOKODILE", "Krookodile", 553),
    ("SPECIES_DARUMAKA", "Darumaka", 554),
    ("SPECIES_DARMANITAN", "Darmanitan", 555),
    ("SPECIES_MARACTUS", "Maractus", 556),
    ("SPECIES_DWEBBLE", "Dwebble", 557),
    ("SPECIES_CRUSTLE", "Crustle", 558),
    ("SPECIES_SCRAGGY", "Scraggy", 559),
    ("SPECIES_SCRAFTY", "Scrafty", 560),
    ("SPECIES_SIGILYPH", "Sigilyph", 561),
    ("SPECIES_YAMASK", "Yamask", 562),
    ("SPECIES_COFAGRIGUS", "Cofagrigus", 563),
    ("SPECIES_TIRTOUGA", "Tirtouga", 564),
    ("SPECIES_CARRACOSTA", "Carracosta", 565),
    ("SPECIES_ARCHEN", "Archen", 566),
    ("SPECIES_ARCHEOPS", "Archeops", 567),
    ("SPECIES_TRUBBISH", "Trubbish", 568),
    ("SPECIES_GARBODOR", "Garbodor", 569),
    ("SPECIES_ZORUA", "Zorua", 570),
    ("SPECIES_ZOROARK", "Zoroark", 571),
    ("SPECIES_MINCCINO", "Minccino", 572),
    ("SPECIES_CINCCINO", "Cinccino", 573),
    ("SPECIES_GOTHITA", "Gothita", 574),
    ("SPECIES_GOTHORITA", "Gothorita", 575),
    ("SPECIES_GOTHITELLE", "Gothitelle", 576),
    ("SPECIES_SOLOSIS", "Solosis", 577),
    ("SPECIES_DUOSION", "Duosion", 578),
    ("SPECIES_REUNICLUS", "Reuniclus", 579),
    ("SPECIES_DUCKLETT", "Ducklett", 580),
    ("SPECIES_SWANNA", "Swanna", 581),
    ("SPECIES_VANILLITE", "Vanillite", 582),
    ("SPECIES_VANILLISH", "Vanillish", 583),
    ("SPECIES_VANILLUXE", "Vanilluxe", 584),
    ("SPECIES_DEERLING", "Deerling", 585),
    ("SPECIES_SAWSBUCK", "Sawsbuck", 586),
    ("SPECIES_EMOLGA", "Emolga", 587),
    ("SPECIES_KARRABLAST", "Karrablast", 588),
    ("SPECIES_ESCAVALIER", "Escavalier", 589),
    ("SPECIES_FOONGUS", "Foongus", 590),
    ("SPECIES_AMOONGUSS", "Amoonguss", 591),
    ("SPECIES_FRILLISH", "Frillish", 592),
    ("SPECIES_JELLICENT", "Jellicent", 593),
    ("SPECIES_ALOMOMOLA", "Alomomola", 594),
    ("SPECIES_JOLTIK", "Joltik", 595),
    ("SPECIES_GALVANTULA", "Galvantula", 596),
    ("SPECIES_FERROSEED", "Ferroseed", 597),
    ("SPECIES_FERROTHORN", "Ferrothorn", 598),
    ("SPECIES_KLINK", "Klink", 599),
    ("SPECIES_KLANG", "Klang", 600),
    ("SPECIES_KLINKLANG", "Klinklang", 601),
    ("SPECIES_TYNAMO", "Tynamo", 602),
    ("SPECIES_EELEKTRIK", "Eelektrik", 603),
    ("SPECIES_EELEKTROSS", "Eelektross", 604),
    ("SPECIES_ELGYEM", "Elgyem", 605),
    ("SPECIES_BEHEEYEM", "Beheeyem", 606),
    ("SPECIES_LITWICK", "Litwick", 607),
    ("SPECIES_LAMPENT", "Lampent", 608),
    ("SPECIES_CHANDELURE", "Chandelure", 609),
    ("SPECIES_AXEW", "Axew", 610),
    ("SPECIES_FRAXURE", "Fraxure", 611),
    ("SPECIES_HAXORUS", "Haxorus", 612),
    ("SPECIES_CUBCHOO", "Cubchoo", 613),
    ("SPECIES_BEARTIC", "Beartic", 614),
    ("SPECIES_CRYOGONAL", "Cryogonal", 615),
    ("SPECIES_SHELMET", "Shelmet", 616),
    ("SPECIES_ACCELGOR", "Accelgor", 617),
    ("SPECIES_STUNFISK", "Stunfisk", 618),
    ("SPECIES_MIENFOO", "Mienfoo", 619),
    ("SPECIES_MIENSHAO", "Mienshao", 620),
    ("SPECIES_DRUDDIGON", "Druddigon", 621),
    ("SPECIES_GOLETT", "Golett", 622),
    ("SPECIES_GOLURK", "Golurk", 623),
    ("SPECIES_PAWNIARD", "Pawniard", 624),
    ("SPECIES_BISHARP", "Bisharp", 625),
    ("SPECIES_BOUFFALANT", "Bouffalant", 626),
    ("SPECIES_RUFFLET", "Rufflet", 627),
    ("SPECIES_BRAVIARY", "Braviary", 628),
    ("SPECIES_VULLABY", "Vullaby", 629),
    ("SPECIES_MANDIBUZZ", "Mandibuzz", 630),
    ("SPECIES_HEATMOR", "Heatmor", 631),
    ("SPECIES_DURANT", "Durant", 632),
    ("SPECIES_DEINO", "Deino", 633),
    ("SPECIES_ZWEILOUS", "Zweilous", 634),
    ("SPECIES_HYDREIGON", "Hydreigon", 635),
    ("SPECIES_LARVESTA", "Larvesta", 636),
    ("SPECIES_VOLCARONA", "Volcarona", 637),
    ("SPECIES_COBALION", "Cobalion", 638),
    ("SPECIES_TERRAKION", "Terrakion", 639),
    ("SPECIES_VIRIZION", "Virizion", 640),
    ("SPECIES_TORNADUS", "Tornadus", 641),
    ("SPECIES_THUNDURUS", "Thundurus", 642),
    ("SPECIES_RESHIRAM", "Reshiram", 643),
    ("SPECIES_ZEKROM", "Zekrom", 644),
    ("SPECIES_LANDORUS", "Landorus", 645),
    ("SPECIES_KYUREM", "Kyurem", 646),
    ("SPECIES_KELDEO", "Keldeo", 647),
    ("SPECIES_MELOETTA", "Meloetta", 648),
    ("SPECIES_GENESECT", "Genesect", 649),
    ("SPECIES_CHESPIN", "Chespin", 650),
    ("SPECIES_QUILLADIN", "Quilladin", 651),
    ("SPECIES_CHESNAUGHT", "Chesnaught", 652),
    ("SPECIES_FENNEKIN", "Fennekin", 653),
    ("SPECIES_BRAIXEN", "Braixen", 654),
    ("SPECIES_DELPHOX", "Delphox", 655),
    ("SPECIES_FROAKIE", "Froakie", 656),
    ("SPECIES_FROGADIER", "Frogadier", 657),
    ("SPECIES_GRENINJA", "Greninja", 658),
    ("SPECIES_BUNNELBY", "Bunnelby", 659),
    ("SPECIES_DIGGERSBY", "Diggersby", 660),
    ("SPECIES_FLETCHLING", "Fletchling", 661),
    ("SPECIES_FLETCHINDER", "Fletchinder", 662),
    ("SPECIES_TALONFLAME", "Talonflame", 663),
    ("SPECIES_SCATTERBUG", "Scatterbug", 664),
    ("SPECIES_SPEWPA", "Spewpa", 665),
    ("SPECIES_VIVILLON", "Vivillon", 666),
    ("SPECIES_LITLEO", "Litleo", 667),
    ("SPECIES_PYROAR", "Pyroar", 668),
    ("SPECIES_FLABEBE", "Flabebe", 669),
    ("SPECIES_FLOETTE", "Floette", 670),
    ("SPECIES_FLORGES", "Florges", 671),
    ("SPECIES_SKIDDO", "Skiddo", 672),
    ("SPECIES_GOGOAT", "Gogoat", 673),
    ("SPECIES_PANCHAM", "Pancham", 674),
    ("SPECIES_PANGORO", "Pangoro", 675),
    ("SPECIES_FURFROU", "Furfrou", 676),
    ("SPECIES_ESPURR", "Espurr", 677),
    ("SPECIES_MEOWSTIC", "Meowstic", 678),
    ("SPECIES_HONEDGE", "Honedge", 679),
    ("SPECIES_DOUBLADE", "Doublade", 680),
    ("SPECIES_AEGISLASH", "Aegislash", 681),
    ("SPECIES_SPRITZEE", "Spritzee", 682),
    ("SPECIES_AROMATISSE", "Aromatisse", 683),
    ("SPECIES_SWIRLIX", "Swirlix", 684),
    ("SPECIES_SLURPUFF", "Slurpuff", 685),
    ("SPECIES_INKAY", "Inkay", 686),
    ("SPECIES_MALAMAR", "Malamar", 687),
    ("SPECIES_BINACLE", "Binacle", 688),
    ("SPECIES_BARBARACLE", "Barbaracle", 689),
    ("SPECIES_SKRELP", "Skrelp", 690),
    ("SPECIES_DRAGALGE", "Dragalge", 691),
    ("SPECIES_CLAUNCHER", "Clauncher", 692),
    ("SPECIES_CLAWITZER", "Clawitzer", 693),
    ("SPECIES_HELIOPTILE", "Helioptile", 694),
    ("SPECIES_HELIOLISK", "Heliolisk", 695),
    ("SPECIES_TYRUNT", "Tyrunt", 696),
    ("SPECIES_TYRANTRUM", "Tyrantrum", 697),
    ("SPECIES_AMAURA", "Amaura", 698),
    ("SPECIES_AURORUS", "Aurorus", 699),
    ("SPECIES_SYLVEON", "Sylveon", 700),
    ("SPECIES_HAWLUCHA", "Hawlucha", 701),
    ("SPECIES_DEDENNE", "Dedenne", 702),
    ("SPECIES_CARBINK", "Carbink", 703),
    ("SPECIES_GOOMY", "Goomy", 704),
    ("SPECIES_SLIGGOO", "Sliggoo", 705),
    ("SPECIES_GOODRA", "Goodra", 706),
    ("SPECIES_KLEFKI", "Klefki", 707),
    ("SPECIES_PHANTUMP", "Phantump", 708),
    ("SPECIES_TREVENANT", "Trevenant", 709),
    ("SPECIES_PUMPKABOO", "Pumpkaboo", 710),
    ("SPECIES_GOURGEIST", "Gourgeist", 711),
    ("SPECIES_BERGMITE", "Bergmite", 712),
    ("SPECIES_AVALUGG", "Avalugg", 713),
    ("SPECIES_NOIBAT", "Noibat", 714),
    ("SPECIES_NOIVERN", "Noivern", 715),
    ("SPECIES_XERNEAS", "Xerneas", 716),
    ("SPECIES_YVELTAL", "Yveltal", 717),
    ("SPECIES_ZYGARDE", "Zygarde", 718),
    ("SPECIES_DIANCIE", "Diancie", 719),
    ("SPECIES_HOOPA", "Hoopa", 720),
    ("SPECIES_VOLCANION", "Volcanion", 721),
    ("SPECIES_ROWLET", "Rowlet", 722),
    ("SPECIES_DARTRIX", "Dartrix", 723),
    ("SPECIES_DECIDUEYE", "Decidueye", 724),
    ("SPECIES_LITTEN", "Litten", 725),
    ("SPECIES_TORRACAT", "Torracat", 726),
    ("SPECIES_INCINEROAR", "Incineroar", 727),
    ("SPECIES_POPPLIO", "Popplio", 728),
    ("SPECIES_BRIONNE", "Brionne", 729),
    ("SPECIES_PRIMARINA", "Primarina", 730),
    ("SPECIES_PIKIPEK", "Pikipek", 731),
    ("SPECIES_TRUMBEAK", "Trumbeak", 732),
    ("SPECIES_TOUCANNON", "Toucannon", 733),
    ("SPECIES_YUNGOOS", "Yungoos", 734),
    ("SPECIES_GUMSHOOS", "Gumshoos", 735),
    ("SPECIES_GRUBBIN", "Grubbin", 736),
    ("SPECIES_CHARJABUG", "Charjabug", 737),
    ("SPECIES_VIKAVOLT", "Vikavolt", 738),
    ("SPECIES_CRABRAWLER", "Crabrawler", 739),
    ("SPECIES_CRABOMINABLE", "Crabominable", 740),
    ("SPECIES_ORICORIO", "Oricorio", 741),
    ("SPECIES_CUTIEFLY", "Cutiefly", 742),
    ("SPECIES_RIBOMBEE", "Ribombee", 743),
    ("SPECIES_ROCKRUFF", "Rockruff", 744),
    ("SPECIES_LYCANROC", "Lycanroc", 745),
    ("SPECIES_WISHIWASHI", "Wishiwashi", 746),
    ("SPECIES_MAREANIE", "Mareanie", 747),
    ("SPECIES_TOXAPEX", "Toxapex", 748),
    ("SPECIES_MUDBRAY", "Mudbray", 749),
    ("SPECIES_MUDSDALE", "Mudsdale", 750),
    ("SPECIES_DEWPIDER", "Dewpider", 751),
    ("SPECIES_ARAQUANID", "Araquanid", 752),
    ("SPECIES_FOMANTIS", "Fomantis", 753),
    ("SPECIES_LURANTIS", "Lurantis", 754),
    ("SPECIES_MORELULL", "Morelull", 755),
    ("SPECIES_SHIINOTIC", "Shiinotic", 756),
    ("SPECIES_SALANDIT", "Salandit", 757),
    ("SPECIES_SALAZZLE", "Salazzle", 758),
    ("SPECIES_STUFFUL", "Stufful", 759),
    ("SPECIES_BEWEAR", "Bewear", 760),
    ("SPECIES_BOUNSWEET", "Bounsweet", 761),
    ("SPECIES_STEENEE", "Steenee", 762),
    ("SPECIES_TSAREENA", "Tsareena", 763),
    ("SPECIES_COMFEY", "Comfey", 764),
    ("SPECIES_ORANGURU", "Oranguru", 765),
    ("SPECIES_PASSIMIAN", "Passimian", 766),
    ("SPECIES_WIMPOD", "Wimpod", 767),
    ("SPECIES_GOLISOPOD", "Golisopod", 768),
    ("SPECIES_SANDYGAST", "Sandygast", 769),
    ("SPECIES_PALOSSAND", "Palossand", 770),
    ("SPECIES_PYUKUMUKU", "Pyukumuku", 771),
    ("SPECIES_TYPE_NULL", "Type Null", 772),
    ("SPECIES_SILVALLY", "Silvally", 773),
    ("SPECIES_MINIOR", "Minior", 774),
    ("SPECIES_KOMALA", "Komala", 775),
    ("SPECIES_TURTONATOR", "Turtonator", 776),
    ("SPECIES_TOGEDEMARU", "Togedemaru", 777),
    ("SPECIES_MIMIKYU", "Mimikyu", 778),
    ("SPECIES_BRUXISH", "Bruxish", 779),
    ("SPECIES_DRAMPA", "Drampa", 780),
    ("SPECIES_DHELMISE", "Dhelmise", 781),
    ("SPECIES_JANGMO_O", "Jangmo O", 782),
    ("SPECIES_HAKAMO_O", "Hakamo O", 783),
    ("SPECIES_KOMMO_O", "Kommo O", 784),
    ("SPECIES_TAPU_KOKO", "Tapu Koko", 785),
    ("SPECIES_TAPU_LELE", "Tapu Lele", 786),
    ("SPECIES_TAPU_BULU", "Tapu Bulu", 787),
    ("SPECIES_TAPU_FINI", "Tapu Fini", 788),
    ("SPECIES_COSMOG", "Cosmog", 789),
    ("SPECIES_COSMOEM", "Cosmoem", 790),
    ("SPECIES_SOLGALEO", "Solgaleo", 791),
    ("SPECIES_LUNALA", "Lunala", 792),
    ("SPECIES_NIHILEGO", "Nihilego", 793),
    ("SPECIES_BUZZWOLE", "Buzzwole", 794),
    ("SPECIES_PHEROMOSA", "Pheromosa", 795),
    ("SPECIES_XURKITREE", "Xurkitree", 796),
    ("SPECIES_CELESTEELA", "Celesteela", 797),
    ("SPECIES_KARTANA", "Kartana", 798),
    ("SPECIES_GUZZLORD", "Guzzlord", 799),
    ("SPECIES_NECROZMA", "Necrozma", 800),
    ("SPECIES_MAGEARNA", "Magearna", 801),
    ("SPECIES_MARSHADOW", "Marshadow", 802),
    ("SPECIES_POIPOLE", "Poipole", 803),
    ("SPECIES_NAGANADEL", "Naganadel", 804),
    ("SPECIES_STAKATAKA", "Stakataka", 805),
    ("SPECIES_BLACEPHALON", "Blacephalon", 806),
    ("SPECIES_ZERAORA", "Zeraora", 807),
    ("SPECIES_MELTAN", "Meltan", 808),
    ("SPECIES_MELMETAL", "Melmetal", 809),
    ("SPECIES_GROOKEY", "Grookey", 810),
    ("SPECIES_THWACKEY", "Thwackey", 811),
    ("SPECIES_RILLABOOM", "Rillaboom", 812),
    ("SPECIES_SCORBUNNY", "Scorbunny", 813),
    ("SPECIES_RABOOT", "Raboot", 814),
    ("SPECIES_CINDERACE", "Cinderace", 815),
    ("SPECIES_SOBBLE", "Sobble", 816),
    ("SPECIES_DRIZZILE", "Drizzile", 817),
    ("SPECIES_INTELEON", "Inteleon", 818),
    ("SPECIES_SKWOVET", "Skwovet", 819),
    ("SPECIES_GREEDENT", "Greedent", 820),
    ("SPECIES_ROOKIDEE", "Rookidee", 821),
    ("SPECIES_CORVISQUIRE", "Corvisquire", 822),
    ("SPECIES_CORVIKNIGHT", "Corviknight", 823),
    ("SPECIES_BLIPBUG", "Blipbug", 824),
    ("SPECIES_DOTTLER", "Dottler", 825),
    ("SPECIES_ORBEETLE", "Orbeetle", 826),
    ("SPECIES_NICKIT", "Nickit", 827),
    ("SPECIES_THIEVUL", "Thievul", 828),
    ("SPECIES_GOSSIFLEUR", "Gossifleur", 829),
    ("SPECIES_ELDEGOSS", "Eldegoss", 830),
    ("SPECIES_WOOLOO", "Wooloo", 831),
    ("SPECIES_DUBWOOL", "Dubwool", 832),
    ("SPECIES_CHEWTLE", "Chewtle", 833),
    ("SPECIES_DREDNAW", "Drednaw", 834),
    ("SPECIES_YAMPER", "Yamper", 835),
    ("SPECIES_BOLTUND", "Boltund", 836),
    ("SPECIES_ROLYCOLY", "Rolycoly", 837),
    ("SPECIES_CARKOL", "Carkol", 838),
    ("SPECIES_COALOSSAL", "Coalossal", 839),
    ("SPECIES_APPLIN", "Applin", 840),
    ("SPECIES_FLAPPLE", "Flapple", 841),
    ("SPECIES_APPLETUN", "Appletun", 842),
    ("SPECIES_SILICOBRA", "Silicobra", 843),
    ("SPECIES_SANDACONDA", "Sandaconda", 844),
    ("SPECIES_CRAMORANT", "Cramorant", 845),
    ("SPECIES_ARROKUDA", "Arrokuda", 846),
    ("SPECIES_BARRASKEWDA", "Barraskewda", 847),
    ("SPECIES_TOXEL", "Toxel", 848),
    ("SPECIES_TOXTRICITY", "Toxtricity", 849),
    ("SPECIES_SIZZLIPEDE", "Sizzlipede", 850),
    ("SPECIES_CENTISKORCH", "Centiskorch", 851),
    ("SPECIES_CLOBBOPUS", "Clobbopus", 852),
    ("SPECIES_GRAPPLOCT", "Grapploct", 853),
    ("SPECIES_SINISTEA", "Sinistea", 854),
    ("SPECIES_POLTEAGEIST", "Polteageist", 855),
    ("SPECIES_HATENNA", "Hatenna", 856),
    ("SPECIES_HATTREM", "Hattrem", 857),
    ("SPECIES_HATTERENE", "Hatterene", 858),
    ("SPECIES_IMPIDIMP", "Impidimp", 859),
    ("SPECIES_MORGREM", "Morgrem", 860),
    ("SPECIES_GRIMMSNARL", "Grimmsnarl", 861),
    ("SPECIES_OBSTAGOON", "Obstagoon", 862),
    ("SPECIES_PERRSERKER", "Perrserker", 863),
    ("SPECIES_CURSOLA", "Cursola", 864),
    ("SPECIES_SIRFETCHD", "Sirfetchd", 865),
    ("SPECIES_MR_RIME", "Mr Rime", 866),
    ("SPECIES_RUNERIGUS", "Runerigus", 867),
    ("SPECIES_MILCERY", "Milcery", 868),
    ("SPECIES_ALCREMIE", "Alcremie", 869),
    ("SPECIES_FALINKS", "Falinks", 870),
    ("SPECIES_PINCURCHIN", "Pincurchin", 871),
    ("SPECIES_SNOM", "Snom", 872),
    ("SPECIES_FROSMOTH", "Frosmoth", 873),
    ("SPECIES_STONJOURNER", "Stonjourner", 874),
    ("SPECIES_EISCUE", "Eiscue", 875),
    ("SPECIES_INDEEDEE", "Indeedee", 876),
    ("SPECIES_MORPEKO", "Morpeko", 877),
    ("SPECIES_CUFANT", "Cufant", 878),
    ("SPECIES_COPPERAJAH", "Copperajah", 879),
    ("SPECIES_DRACOZOLT", "Dracozolt", 880),
    ("SPECIES_ARCTOZOLT", "Arctozolt", 881),
    ("SPECIES_DRACOVISH", "Dracovish", 882),
    ("SPECIES_ARCTOVISH", "Arctovish", 883),
    ("SPECIES_DURALUDON", "Duraludon", 884),
    ("SPECIES_DREEPY", "Dreepy", 885),
    ("SPECIES_DRAKLOAK", "Drakloak", 886),
    ("SPECIES_DRAGAPULT", "Dragapult", 887),
    ("SPECIES_ZACIAN", "Zacian", 888),
    ("SPECIES_ZAMAZENTA", "Zamazenta", 889),
    ("SPECIES_ETERNATUS", "Eternatus", 890),
    ("SPECIES_KUBFU", "Kubfu", 891),
    ("SPECIES_URSHIFU", "Urshifu", 892),
    ("SPECIES_ZARUDE", "Zarude", 893),
    ("SPECIES_REGIELEKI", "Regieleki", 894),
    ("SPECIES_REGIDRAGO", "Regidrago", 895),
    ("SPECIES_GLASTRIER", "Glastrier", 896),
    ("SPECIES_SPECTRIER", "Spectrier", 897),
    ("SPECIES_CALYREX", "Calyrex", 898),
    ("SPECIES_WYRDEER", "Wyrdeer", 899),
    ("SPECIES_KLEAVOR", "Kleavor", 900),
    ("SPECIES_URSALUNA", "Ursaluna", 901),
    ("SPECIES_BASCULEGION", "Basculegion", 902),
    ("SPECIES_SNEASLER", "Sneasler", 903),
    ("SPECIES_OVERQWIL", "Overqwil", 904),
    ("SPECIES_ENAMORUS", "Enamorus", 905),
    ("SPECIES_SPRIGATITO", "Sprigatito", 906),
    ("SPECIES_FLORAGATO", "Floragato", 907),
    ("SPECIES_MEOWSCARADA", "Meowscarada", 908),
    ("SPECIES_FUECOCO", "Fuecoco", 909),
    ("SPECIES_CROCALOR", "Crocalor", 910),
    ("SPECIES_SKELEDIRGE", "Skeledirge", 911),
    ("SPECIES_QUAXLY", "Quaxly", 912),
    ("SPECIES_QUAXWELL", "Quaxwell", 913),
    ("SPECIES_QUAQUAVAL", "Quaquaval", 914),
    ("SPECIES_LECHONK", "Lechonk", 915),
    ("SPECIES_OINKOLOGNE", "Oinkologne", 916),
    ("SPECIES_TAROUNTULA", "Tarountula", 917),
    ("SPECIES_SPIDOPS", "Spidops", 918),
    ("SPECIES_NYMBLE", "Nymble", 919),
    ("SPECIES_LOKIX", "Lokix", 920),
    ("SPECIES_PAWMI", "Pawmi", 921),
    ("SPECIES_PAWMO", "Pawmo", 922),
    ("SPECIES_PAWMOT", "Pawmot", 923),
    ("SPECIES_TANDEMAUS", "Tandemaus", 924),
    ("SPECIES_MAUSHOLD", "Maushold", 925),
    ("SPECIES_FIDOUGH", "Fidough", 926),
    ("SPECIES_DACHSBUN", "Dachsbun", 927),
    ("SPECIES_SMOLIV", "Smoliv", 928),
    ("SPECIES_DOLLIV", "Dolliv", 929),
    ("SPECIES_ARBOLIVA", "Arboliva", 930),
    ("SPECIES_SQUAWKABILLY", "Squawkabilly", 931),
    ("SPECIES_NACLI", "Nacli", 932),
    ("SPECIES_NACLSTACK", "Naclstack", 933),
    ("SPECIES_GARGANACL", "Garganacl", 934),
    ("SPECIES_CHARCADET", "Charcadet", 935),
    ("SPECIES_ARMAROUGE", "Armarouge", 936),
    ("SPECIES_CERULEDGE", "Ceruledge", 937),
    ("SPECIES_TADBULB", "Tadbulb", 938),
    ("SPECIES_BELLIBOLT", "Bellibolt", 939),
    ("SPECIES_WATTREL", "Wattrel", 940),
    ("SPECIES_KILOWATTREL", "Kilowattrel", 941),
    ("SPECIES_MASCHIFF", "Maschiff", 942),
    ("SPECIES_MABOSSTIFF", "Mabosstiff", 943),
    ("SPECIES_SHROODLE", "Shroodle", 944),
    ("SPECIES_GRAFAIAI", "Grafaiai", 945),
    ("SPECIES_BRAMBLIN", "Bramblin", 946),
    ("SPECIES_BRAMBLEGHAST", "Brambleghast", 947),
    ("SPECIES_TOEDSCOOL", "Toedscool", 948),
    ("SPECIES_TOEDSCRUEL", "Toedscruel", 949),
    ("SPECIES_KLAWF", "Klawf", 950),
    ("SPECIES_CAPSAKID", "Capsakid", 951),
    ("SPECIES_SCOVILLAIN", "Scovillain", 952),
    ("SPECIES_RELLOR", "Rellor", 953),
    ("SPECIES_RABSCA", "Rabsca", 954),
    ("SPECIES_FLITTLE", "Flittle", 955),
    ("SPECIES_ESPATHRA", "Espathra", 956),
    ("SPECIES_TINKATINK", "Tinkatink", 957),
    ("SPECIES_TINKATUFF", "Tinkatuff", 958),
    ("SPECIES_TINKATON", "Tinkaton", 959),
    ("SPECIES_WIGLETT", "Wiglett", 960),
    ("SPECIES_WUGTRIO", "Wugtrio", 961),
    ("SPECIES_BOMBIRDIER", "Bombirdier", 962),
    ("SPECIES_FINIZEN", "Finizen", 963),
    ("SPECIES_PALAFIN", "Palafin", 964),
    ("SPECIES_VAROOM", "Varoom", 965),
    ("SPECIES_REVAVROOM", "Revavroom", 966),
    ("SPECIES_CYCLIZAR", "Cyclizar", 967),
    ("SPECIES_ORTHWORM", "Orthworm", 968),
    ("SPECIES_GLIMMET", "Glimmet", 969),
    ("SPECIES_GLIMMORA", "Glimmora", 970),
    ("SPECIES_GREAVARD", "Greavard", 971),
    ("SPECIES_HOUNDSTONE", "Houndstone", 972),
    ("SPECIES_FLAMIGO", "Flamigo", 973),
    ("SPECIES_CETODDLE", "Cetoddle", 974),
    ("SPECIES_CETITAN", "Cetitan", 975),
    ("SPECIES_VELUZA", "Veluza", 976),
    ("SPECIES_DONDOZO", "Dondozo", 977),
    ("SPECIES_TATSUGIRI", "Tatsugiri", 978),
    ("SPECIES_ANNIHILAPE", "Annihilape", 979),
    ("SPECIES_CLODSIRE", "Clodsire", 980),
    ("SPECIES_FARIGIRAF", "Farigiraf", 981),
    ("SPECIES_DUDUNSPARCE", "Dudunsparce", 982),
    ("SPECIES_KINGAMBIT", "Kingambit", 983),
    ("SPECIES_GREAT_TUSK", "Great Tusk", 984),
    ("SPECIES_SCREAM_TAIL", "Scream Tail", 985),
    ("SPECIES_BRUTE_BONNET", "Brute Bonnet", 986),
    ("SPECIES_FLUTTER_MANE", "Flutter Mane", 987),
    ("SPECIES_SLITHER_WING", "Slither Wing", 988),
    ("SPECIES_SANDY_SHOCKS", "Sandy Shocks", 989),
    ("SPECIES_IRON_TREADS", "Iron Treads", 990),
    ("SPECIES_IRON_BUNDLE", "Iron Bundle", 991),
    ("SPECIES_IRON_HANDS", "Iron Hands", 992),
    ("SPECIES_IRON_JUGULIS", "Iron Jugulis", 993),
    ("SPECIES_IRON_MOTH", "Iron Moth", 994),
    ("SPECIES_IRON_THORNS", "Iron Thorns", 995),
    ("SPECIES_FRIGIBAX", "Frigibax", 996),
    ("SPECIES_ARCTIBAX", "Arctibax", 997),
    ("SPECIES_BAXCALIBUR", "Baxcalibur", 998),
    ("SPECIES_GIMMIGHOUL", "Gimmighoul", 999),
    ("SPECIES_GHOLDENGO", "Gholdengo", 1000),
    ("SPECIES_WO_CHIEN", "Wo Chien", 1001),
    ("SPECIES_CHIEN_PAO", "Chien Pao", 1002),
    ("SPECIES_TING_LU", "Ting Lu", 1003),
    ("SPECIES_CHI_YU", "Chi Yu", 1004),
    ("SPECIES_ROARING_MOON", "Roaring Moon", 1005),
    ("SPECIES_IRON_VALIANT", "Iron Valiant", 1006),
    ("SPECIES_KORAIDON", "Koraidon", 1007),
    ("SPECIES_MIRAIDON", "Miraidon", 1008),
    ("SPECIES_WALKING_WAKE", "Walking Wake", 1009),
    ("SPECIES_IRON_LEAVES", "Iron Leaves", 1010),
    ("SPECIES_DIPPLIN", "Dipplin", 1011),
    ("SPECIES_POLTCHAGEIST", "Poltchageist", 1012),
    ("SPECIES_SINISTCHA", "Sinistcha", 1013),
    ("SPECIES_OKIDOGI", "Okidogi", 1014),
    ("SPECIES_MUNKIDORI", "Munkidori", 1015),
    ("SPECIES_FEZANDIPITI", "Fezandipiti", 1016),
    ("SPECIES_OGERPON", "Ogerpon", 1017),
    ("SPECIES_ARCHALUDON", "Archaludon", 1018),
    ("SPECIES_HYDRAPPLE", "Hydrapple", 1019),
    ("SPECIES_GOUGING_FIRE", "Gouging Fire", 1020),
    ("SPECIES_RAGING_BOLT", "Raging Bolt", 1021),
    ("SPECIES_IRON_BOULDER", "Iron Boulder", 1022),
    ("SPECIES_IRON_CROWN", "Iron Crown", 1023),
    ("SPECIES_TERAPAGOS", "Terapagos", 1024),
    ("SPECIES_PECHARUNT", "Pecharunt", 1025),
]
all_abilities: list[tuple[str, str]] = [
    ("ABILITY_STENCH", "Stench"),
    ("ABILITY_DRIZZLE", "Drizzle"),
    ("ABILITY_SPEED_BOOST", "Speed Boost"),
    ("ABILITY_BATTLE_ARMOR", "Battle Armor"),
    ("ABILITY_STURDY", "Sturdy"),
    ("ABILITY_DAMP", "Damp"),
    ("ABILITY_LIMBER", "Limber"),
    ("ABILITY_SAND_VEIL", "Sand Veil"),
    ("ABILITY_STATIC", "Static"),
    ("ABILITY_VOLT_ABSORB", "Volt Absorb"),
    ("ABILITY_WATER_ABSORB", "Water Absorb"),
    ("ABILITY_OBLIVIOUS", "Oblivious"),
    ("ABILITY_CLOUD_NINE", "Cloud Nine"),
    ("ABILITY_COMPOUND_EYES", "Compoundeyes"),
    ("ABILITY_INSOMNIA", "Insomnia"),
    ("ABILITY_COLOR_CHANGE", "Color Change"),
    ("ABILITY_IMMUNITY", "Immunity"),
    ("ABILITY_FLASH_FIRE", "Flash Fire"),
    ("ABILITY_SHIELD_DUST", "Shield Dust"),
    ("ABILITY_OWN_TEMPO", "Own Tempo"),
    ("ABILITY_SUCTION_CUPS", "Suction Cups"),
    ("ABILITY_INTIMIDATE", "Intimidate"),
    ("ABILITY_SHADOW_TAG", "Shadow Tag"),
    ("ABILITY_ROUGH_SKIN", "Rough Skin"),
    ("ABILITY_WONDER_GUARD", "Wonder Guard"),
    ("ABILITY_LEVITATE", "Levitate"),
    ("ABILITY_EFFECT_SPORE", "Effect Spore"),
    ("ABILITY_SYNCHRONIZE", "Synchronize"),
    ("ABILITY_CLEAR_BODY", "Clear Body"),
    ("ABILITY_NATURAL_CURE", "Natural Cure"),
    ("ABILITY_LIGHTNING_ROD", "Lightningrod"),
    ("ABILITY_SERENE_GRACE", "Serene Grace"),
    ("ABILITY_SWIFT_SWIM", "Swift Swim"),
    ("ABILITY_CHLOROPHYLL", "Chlorophyll"),
    ("ABILITY_ILLUMINATE", "Illuminate"),
    ("ABILITY_TRACE", "Trace"),
    ("ABILITY_HUGE_POWER", "Huge Power"),
    ("ABILITY_POISON_POINT", "Poison Point"),
    ("ABILITY_INNER_FOCUS", "Inner Focus"),
    ("ABILITY_MAGMA_ARMOR", "Magma Armor"),
    ("ABILITY_WATER_VEIL", "Water Veil"),
    ("ABILITY_MAGNET_PULL", "Magnet Pull"),
    ("ABILITY_SOUNDPROOF", "Soundproof"),
    ("ABILITY_RAIN_DISH", "Rain Dish"),
    ("ABILITY_SAND_STREAM", "Sand Stream"),
    ("ABILITY_PRESSURE", "Pressure"),
    ("ABILITY_THICK_FAT", "Thick Fat"),
    ("ABILITY_EARLY_BIRD", "Early Bird"),
    ("ABILITY_FLAME_BODY", "Flame Body"),
    ("ABILITY_RUN_AWAY", "Run Away"),
    ("ABILITY_KEEN_EYE", "Keen Eye"),
    ("ABILITY_HYPER_CUTTER", "Hyper Cutter"),
    ("ABILITY_PICKUP", "Pickup"),
    ("ABILITY_TRUANT", "Truant"),
    ("ABILITY_HUSTLE", "Hustle"),
    ("ABILITY_CUTE_CHARM", "Cute Charm"),
    ("ABILITY_PLUS", "Plus"),
    ("ABILITY_MINUS", "Minus"),
    ("ABILITY_FORECAST", "Forecast"),
    ("ABILITY_STICKY_HOLD", "Sticky Hold"),
    ("ABILITY_SHED_SKIN", "Shed Skin"),
    ("ABILITY_GUTS", "Guts"),
    ("ABILITY_MARVEL_SCALE", "Marvel Scale"),
    ("ABILITY_LIQUID_OOZE", "Liquid Ooze"),
    ("ABILITY_OVERGROW", "Overgrow"),
    ("ABILITY_BLAZE", "Blaze"),
    ("ABILITY_TORRENT", "Torrent"),
    ("ABILITY_SWARM", "Swarm"),
    ("ABILITY_ROCK_HEAD", "Rock Head"),
    ("ABILITY_DROUGHT", "Drought"),
    ("ABILITY_ARENA_TRAP", "Arena Trap"),
    ("ABILITY_VITAL_SPIRIT", "Vital Spirit"),
    ("ABILITY_WHITE_SMOKE", "White Smoke"),
    ("ABILITY_PURE_POWER", "Pure Power"),
    ("ABILITY_SHELL_ARMOR", "Shell Armor"),
    ("ABILITY_AIR_LOCK", "Air Lock"),
    ("ABILITY_TANGLED_FEET", "Tangled Feet"),
    ("ABILITY_MOTOR_DRIVE", "Motor Drive"),
    ("ABILITY_RIVALRY", "Rivalry"),
    ("ABILITY_STEADFAST", "Steadfast"),
    ("ABILITY_SNOW_CLOAK", "Snow Cloak"),
    ("ABILITY_GLUTTONY", "Gluttony"),
    ("ABILITY_ANGER_POINT", "Anger Point"),
    ("ABILITY_UNBURDEN", "Unburden"),
    ("ABILITY_HEATPROOF", "Heatproof"),
    ("ABILITY_SIMPLE", "Simple"),
    ("ABILITY_DRY_SKIN", "Dry Skin"),
    ("ABILITY_DOWNLOAD", "Download"),
    ("ABILITY_IRON_FIST", "Iron Fist"),
    ("ABILITY_POISON_HEAL", "Poison Heal"),
    ("ABILITY_ADAPTABILITY", "Adaptability"),
    ("ABILITY_SKILL_LINK", "Skill Link"),
    ("ABILITY_HYDRATION", "Hydration"),
    ("ABILITY_SOLAR_POWER", "Solar Power"),
    ("ABILITY_QUICK_FEET", "Quick Feet"),
    ("ABILITY_NORMALIZE", "Normalize"),
    ("ABILITY_SNIPER", "Sniper"),
    ("ABILITY_MAGIC_GUARD", "Magic Guard"),
    ("ABILITY_NO_GUARD", "No Guard"),
    ("ABILITY_STALL", "Stall"),
    ("ABILITY_TECHNICIAN", "Technician"),
    ("ABILITY_LEAF_GUARD", "Leaf Guard"),
    ("ABILITY_KLUTZ", "Klutz"),
    ("ABILITY_MOLD_BREAKER", "Mold Breaker"),
    ("ABILITY_SUPER_LUCK", "Super Luck"),
    ("ABILITY_AFTERMATH", "Aftermath"),
    ("ABILITY_ANTICIPATION", "Anticipation"),
    ("ABILITY_FOREWARN", "Forewarn"),
    ("ABILITY_UNAWARE", "Unaware"),
    ("ABILITY_TINTED_LENS", "Tinted Lens"),
    ("ABILITY_FILTER", "Filter"),
    ("ABILITY_SLOW_START", "Slow Start"),
    ("ABILITY_SCRAPPY", "Scrappy"),
    ("ABILITY_STORM_DRAIN", "Storm Drain"),
    ("ABILITY_ICE_BODY", "Ice Body"),
    ("ABILITY_SOLID_ROCK", "Solid Rock"),
    ("ABILITY_SNOW_WARNING", "Snow Warning"),
    ("ABILITY_HONEY_GATHER", "Honey Gather"),
    ("ABILITY_FRISK", "Frisk"),
    ("ABILITY_RECKLESS", "Reckless"),
    ("ABILITY_MULTITYPE", "Multitype"),
    ("ABILITY_FLOWER_GIFT", "Flower Gift"),
    ("ABILITY_BAD_DREAMS", "Bad Dreams"),
    ("ABILITY_PICKPOCKET", "Pickpocket"),
    ("ABILITY_SHEER_FORCE", "Sheer Force"),
    ("ABILITY_CONTRARY", "Contrary"),
    ("ABILITY_UNNERVE", "Unnerve"),
    ("ABILITY_DEFIANT", "Defiant"),
    ("ABILITY_DEFEATIST", "Defeatist"),
    ("ABILITY_CURSED_BODY", "Cursed Body"),
    ("ABILITY_HEALER", "Healer"),
    ("ABILITY_FRIEND_GUARD", "Friend Guard"),
    ("ABILITY_WEAK_ARMOR", "Weak Armor"),
    ("ABILITY_HEAVY_METAL", "Heavy Metal"),
    ("ABILITY_LIGHT_METAL", "Light Metal"),
    ("ABILITY_MULTISCALE", "Multiscale"),
    ("ABILITY_TOXIC_BOOST", "Toxic Boost"),
    ("ABILITY_FLARE_BOOST", "Flare Boost"),
    ("ABILITY_HARVEST", "Harvest"),
    ("ABILITY_TELEPATHY", "Telepathy"),
    ("ABILITY_MOODY", "Moody"),
    ("ABILITY_OVERCOAT", "Overcoat"),
    ("ABILITY_POISON_TOUCH", "Poison Touch"),
    ("ABILITY_REGENERATOR", "Regenerator"),
    ("ABILITY_BIG_PECKS", "Big Pecks"),
    ("ABILITY_SAND_RUSH", "Sand Rush"),
    ("ABILITY_WONDER_SKIN", "Wonder Skin"),
    ("ABILITY_ANALYTIC", "Analytic"),
    ("ABILITY_ILLUSION", "Illusion"),
    ("ABILITY_IMPOSTER", "Imposter"),
    ("ABILITY_INFILTRATOR", "Infiltrator"),
    ("ABILITY_MUMMY", "Mummy"),
    ("ABILITY_MOXIE", "Moxie"),
    ("ABILITY_JUSTIFIED", "Justified"),
    ("ABILITY_RATTLED", "Rattled"),
    ("ABILITY_MAGIC_BOUNCE", "Magic Bounce"),
    ("ABILITY_SAP_SIPPER", "Sap Sipper"),
    ("ABILITY_PRANKSTER", "Prankster"),
    ("ABILITY_SAND_FORCE", "Sand Force"),
    ("ABILITY_IRON_BARBS", "Iron Barbs"),
    ("ABILITY_ZEN_MODE", "Zen Mode"),
    ("ABILITY_VICTORY_STAR", "Victory Star"),
    ("ABILITY_TURBOBLAZE", "Turboblaze"),
    ("ABILITY_TERAVOLT", "Teravolt"),
    ("ABILITY_AROMA_VEIL", "Aroma Veil"),
    ("ABILITY_FLOWER_VEIL", "Flower Veil"),
    ("ABILITY_CHEEK_POUCH", "Cheek Pouch"),
    ("ABILITY_PROTEAN", "Protean"),
    ("ABILITY_FUR_COAT", "Fur Coat"),
    ("ABILITY_MAGICIAN", "Magician"),
    ("ABILITY_BULLETPROOF", "Bulletproof"),
    ("ABILITY_COMPETITIVE", "Competitive"),
    ("ABILITY_STRONG_JAW", "Strong Jaw"),
    ("ABILITY_REFRIGERATE", "Refrigerate"),
    ("ABILITY_SWEET_VEIL", "Sweet Veil"),
    ("ABILITY_STANCE_CHANGE", "Stance Change"),
    ("ABILITY_GALE_WINGS", "Gale Wings"),
    ("ABILITY_MEGA_LAUNCHER", "Mega Launcher"),
    ("ABILITY_GRASS_PELT", "Grass Pelt"),
    ("ABILITY_SYMBIOSIS", "Symbiosis"),
    ("ABILITY_TOUGH_CLAWS", "Tough Claws"),
    ("ABILITY_PIXILATE", "Pixilate"),
    ("ABILITY_GOOEY", "Gooey"),
    ("ABILITY_AERILATE", "Aerilate"),
    ("ABILITY_PARENTAL_BOND", "Parental Bond"),
    ("ABILITY_DARK_AURA", "Dark Aura"),
    ("ABILITY_FAIRY_AURA", "Fairy Aura"),
    ("ABILITY_AURA_BREAK", "Aura Break"),
    ("ABILITY_PRIMORDIAL_SEA", "Primordial Sea"),
    ("ABILITY_DESOLATE_LAND", "Desolate Land"),
    ("ABILITY_DELTA_STREAM", "Delta Stream"),
    ("ABILITY_STAMINA", "Stamina"),
    ("ABILITY_WIMP_OUT", "Wimp Out"),
    ("ABILITY_EMERGENCY_EXIT", "Emergency Exit"),
    ("ABILITY_WATER_COMPACTION", "Water Compaction"),
    ("ABILITY_MERCILESS", "Merciless"),
    ("ABILITY_SHIELDS_DOWN", "Shields Down"),
    ("ABILITY_STAKEOUT", "Stakeout"),
    ("ABILITY_WATER_BUBBLE", "Water Bubble"),
    ("ABILITY_STEELWORKER", "Steelworker"),
    ("ABILITY_BERSERK", "Berserk"),
    ("ABILITY_SLUSH_RUSH", "Slush Rush"),
    ("ABILITY_LONG_REACH", "Long Reach"),
    ("ABILITY_LIQUID_VOICE", "Liquid Voice"),
    ("ABILITY_TRIAGE", "Triage"),
    ("ABILITY_GALVANIZE", "Galvanize"),
    ("ABILITY_SURGE_SURFER", "Surge Surfer"),
    ("ABILITY_SCHOOLING", "Schooling"),
    ("ABILITY_DISGUISE", "Disguise"),
    ("ABILITY_BATTLE_BOND", "Battle Bond"),
    ("ABILITY_POWER_CONSTRUCT", "Power Construct"),
    ("ABILITY_CORROSION", "Corrosion"),
    ("ABILITY_COMATOSE", "Comatose"),
    ("ABILITY_QUEENLY_MAJESTY", "Queenly Majesty"),
    ("ABILITY_INNARDS_OUT", "Innards Out"),
    ("ABILITY_DANCER", "Dancer"),
    ("ABILITY_BATTERY", "Battery"),
    ("ABILITY_FLUFFY", "Fluffy"),
    ("ABILITY_DAZZLING", "Dazzling"),
    ("ABILITY_SOUL_HEART", "Soul Heart"),
    ("ABILITY_TANGLING_HAIR", "Tangling Hair"),
    ("ABILITY_RECEIVER", "Receiver"),
    ("ABILITY_POWER_OF_ALCHEMY", "Power Of Alchemy"),
    ("ABILITY_BEAST_BOOST", "Beast Boost"),
    ("ABILITY_RKS_SYSTEM", "Rks System"),
    ("ABILITY_ELECTRIC_SURGE", "Electric Surge"),
    ("ABILITY_PSYCHIC_SURGE", "Psychic Surge"),
    ("ABILITY_MISTY_SURGE", "Misty Surge"),
    ("ABILITY_GRASSY_SURGE", "Grassy Surge"),
    ("ABILITY_FULL_METAL_BODY", "Full Metal Body"),
    ("ABILITY_SHADOW_SHIELD", "Shadow Shield"),
    ("ABILITY_PRISM_ARMOR", "Prism Armor"),
    ("ABILITY_NEUROFORCE", "Neuroforce"),
    ("ABILITY_INTREPID_SWORD", "Intrepid Sword"),
    ("ABILITY_DAUNTLESS_SHIELD", "Dauntless Shield"),
    ("ABILITY_LIBERO", "Libero"),
    ("ABILITY_BALL_FETCH", "Ball Fetch"),
    ("ABILITY_COTTON_DOWN", "Cotton Down"),
    ("ABILITY_PROPELLER_TAIL", "Propeller Tail"),
    ("ABILITY_MIRROR_ARMOR", "Mirror Armor"),
    ("ABILITY_GULP_MISSILE", "Gulp Missile"),
    ("ABILITY_STALWART", "Stalwart"),
    ("ABILITY_STEAM_ENGINE", "Steam Engine"),
    ("ABILITY_PUNK_ROCK", "Punk Rock"),
    ("ABILITY_SAND_SPIT", "Sand Spit"),
    ("ABILITY_ICE_SCALES", "Ice Scales"),
    ("ABILITY_RIPEN", "Ripen"),
    ("ABILITY_ICE_FACE", "Ice Face"),
    ("ABILITY_POWER_SPOT", "Power Spot"),
    ("ABILITY_MIMICRY", "Mimicry"),
    ("ABILITY_SCREEN_CLEANER", "Screen Cleaner"),
    ("ABILITY_STEELY_SPIRIT", "Steely Spirit"),
    ("ABILITY_PERISH_BODY", "Perish Body"),
    ("ABILITY_WANDERING_SPIRIT", "Wandering Spirit"),
    ("ABILITY_GORILLA_TACTICS", "Gorilla Tactics"),
    ("ABILITY_NEUTRALIZING_GAS", "Neutralizing Gas"),
    ("ABILITY_PASTEL_VEIL", "Pastel Veil"),
    ("ABILITY_HUNGER_SWITCH", "Hunger Switch"),
    ("ABILITY_QUICK_DRAW", "Quick Draw"),
    ("ABILITY_UNSEEN_FIST", "Unseen Fist"),
    ("ABILITY_CURIOUS_MEDICINE", "Curious Medicine"),
    ("ABILITY_TRANSISTOR", "Transistor"),
    ("ABILITY_DRAGONS_MAW", "Dragons Maw"),
    ("ABILITY_CHILLING_NEIGH", "Chilling Neigh"),
    ("ABILITY_GRIM_NEIGH", "Grim Neigh"),
    ("ABILITY_AS_ONE_ICE_RIDER", "As One Ice Rider"),
    ("ABILITY_AS_ONE_SHADOW_RIDER", "As One Shadow Rider"),
    ("ABILITY_LINGERING_AROMA", "Lingering Aroma"),
    ("ABILITY_SEED_SOWER", "Seed Sower"),
    ("ABILITY_THERMAL_EXCHANGE", "Thermal Exchange"),
    ("ABILITY_ANGER_SHELL", "Anger Shell"),
    ("ABILITY_PURIFYING_SALT", "Purifying Salt"),
    ("ABILITY_WELL_BAKED_BODY", "Well Baked Body"),
    ("ABILITY_WIND_RIDER", "Wind Rider"),
    ("ABILITY_GUARD_DOG", "Guard Dog"),
    ("ABILITY_ROCKY_PAYLOAD", "Rocky Payload"),
    ("ABILITY_WIND_POWER", "Wind Power"),
    ("ABILITY_ZERO_TO_HERO", "Zero To Hero"),
    ("ABILITY_COMMANDER", "Commander"),
    ("ABILITY_ELECTROMORPHOSIS", "Electromorphosis"),
    ("ABILITY_PROTOSYNTHESIS", "Protosynthesis"),
    ("ABILITY_QUARK_DRIVE", "Quark Drive"),
    ("ABILITY_GOOD_AS_GOLD", "Good As Gold"),
    ("ABILITY_VESSEL_OF_RUIN", "Vessel Of Ruin"),
    ("ABILITY_SWORD_OF_RUIN", "Sword Of Ruin"),
    ("ABILITY_TABLETS_OF_RUIN", "Tablets Of Ruin"),
    ("ABILITY_BEADS_OF_RUIN", "Beads Of Ruin"),
    ("ABILITY_ORICHALCUM_PULSE", "Orichalcum Pulse"),
    ("ABILITY_HADRON_ENGINE", "Hadron Engine"),
    ("ABILITY_OPPORTUNIST", "Opportunist"),
    ("ABILITY_CUD_CHEW", "Cud Chew"),
    ("ABILITY_SHARPNESS", "Sharpness"),
    ("ABILITY_SUPREME_OVERLORD", "Supreme Overlord"),
    ("ABILITY_COSTAR", "Costar"),
    ("ABILITY_TOXIC_DEBRIS", "Toxic Debris"),
    ("ABILITY_ARMOR_TAIL", "Armor Tail"),
    ("ABILITY_EARTH_EATER", "Earth Eater"),
    ("ABILITY_MYCELIUM_MIGHT", "Mycelium Might"),
    ("ABILITY_HOSPITALITY", "Hospitality"),
    ("ABILITY_MINDS_EYE", "Minds Eye"),
    ("ABILITY_EMBODY_ASPECT_TEAL_MASK", "Embody Aspect Teal Mask"),
    ("ABILITY_EMBODY_ASPECT_HEARTHFLAME_MASK", "Embody Aspect Hearthflame Mask"),
    ("ABILITY_EMBODY_ASPECT_WELLSPRING_MASK", "Embody Aspect Wellspring Mask"),
    ("ABILITY_EMBODY_ASPECT_CORNERSTONE_MASK", "Embody Aspect Cornerstone Mask"),
    ("ABILITY_TOXIC_CHAIN", "Toxic Chain"),
    ("ABILITY_SUPERSWEET_SYRUP", "Supersweet Syrup"),
    ("ABILITY_TERA_SHIFT", "Tera Shift"),
    ("ABILITY_TERA_SHELL", "Tera Shell"),
    ("ABILITY_TERAFORM_ZERO", "Teraform Zero"),
    ("ABILITY_POISON_PUPPETEER", "Poison Puppeteer"),
]
all_moves: list[tuple[str, str]] = [
    ("MOVE_POUND", "Pound"),
    ("MOVE_KARATE_CHOP", "Karate Chop"),
    ("MOVE_DOUBLE_SLAP", "Doubleslap"),
    ("MOVE_COMET_PUNCH", "Comet Punch"),
    ("MOVE_MEGA_PUNCH", "Mega Punch"),
    ("MOVE_PAY_DAY", "Pay Day"),
    ("MOVE_FIRE_PUNCH", "Fire Punch"),
    ("MOVE_ICE_PUNCH", "Ice Punch"),
    ("MOVE_THUNDER_PUNCH", "Thunderpunch"),
    ("MOVE_SCRATCH", "Scratch"),
    ("MOVE_VICE_GRIP", "Vicegrip"),
    ("MOVE_GUILLOTINE", "Guillotine"),
    ("MOVE_RAZOR_WIND", "Razor Wind"),
    ("MOVE_SWORDS_DANCE", "Swords Dance"),
    ("MOVE_CUT", "Cut"),
    ("MOVE_GUST", "Gust"),
    ("MOVE_WING_ATTACK", "Wing Attack"),
    ("MOVE_WHIRLWIND", "Whirlwind"),
    ("MOVE_FLY", "Fly"),
    ("MOVE_BIND", "Bind"),
    ("MOVE_SLAM", "Slam"),
    ("MOVE_VINE_WHIP", "Vine Whip"),
    ("MOVE_STOMP", "Stomp"),
    ("MOVE_DOUBLE_KICK", "Double Kick"),
    ("MOVE_MEGA_KICK", "Mega Kick"),
    ("MOVE_JUMP_KICK", "Jump Kick"),
    ("MOVE_ROLLING_KICK", "Rolling Kick"),
    ("MOVE_SAND_ATTACK", "Sand-Attack"),
    ("MOVE_HEADBUTT", "Headbutt"),
    ("MOVE_HORN_ATTACK", "Horn Attack"),
    ("MOVE_FURY_ATTACK", "Fury Attack"),
    ("MOVE_HORN_DRILL", "Horn Drill"),
    ("MOVE_TACKLE", "Tackle"),
    ("MOVE_BODY_SLAM", "Body Slam"),
    ("MOVE_WRAP", "Wrap"),
    ("MOVE_TAKE_DOWN", "Take Down"),
    ("MOVE_THRASH", "Thrash"),
    ("MOVE_DOUBLE_EDGE", "Double-Edge"),
    ("MOVE_TAIL_WHIP", "Tail Whip"),
    ("MOVE_POISON_STING", "Poison Sting"),
    ("MOVE_TWINEEDLE", "Twineedle"),
    ("MOVE_PIN_MISSILE", "Pin Missile"),
    ("MOVE_LEER", "Leer"),
    ("MOVE_BITE", "Bite"),
    ("MOVE_GROWL", "Growl"),
    ("MOVE_ROAR", "Roar"),
    ("MOVE_SING", "Sing"),
    ("MOVE_SUPERSONIC", "Supersonic"),
    ("MOVE_SONIC_BOOM", "Sonicboom"),
    ("MOVE_DISABLE", "Disable"),
    ("MOVE_ACID", "Acid"),
    ("MOVE_EMBER", "Ember"),
    ("MOVE_FLAMETHROWER", "Flamethrower"),
    ("MOVE_MIST", "Mist"),
    ("MOVE_WATER_GUN", "Water Gun"),
    ("MOVE_HYDRO_PUMP", "Hydro Pump"),
    ("MOVE_SURF", "Surf"),
    ("MOVE_ICE_BEAM", "Ice Beam"),
    ("MOVE_BLIZZARD", "Blizzard"),
    ("MOVE_PSYBEAM", "Psybeam"),
    ("MOVE_BUBBLE_BEAM", "Bubblebeam"),
    ("MOVE_AURORA_BEAM", "Aurora Beam"),
    ("MOVE_HYPER_BEAM", "Hyper Beam"),
    ("MOVE_PECK", "Peck"),
    ("MOVE_DRILL_PECK", "Drill Peck"),
    ("MOVE_SUBMISSION", "Submission"),
    ("MOVE_LOW_KICK", "Low Kick"),
    ("MOVE_COUNTER", "Counter"),
    ("MOVE_SEISMIC_TOSS", "Seismic Toss"),
    ("MOVE_STRENGTH", "Strength"),
    ("MOVE_ABSORB", "Absorb"),
    ("MOVE_MEGA_DRAIN", "Mega Drain"),
    ("MOVE_LEECH_SEED", "Leech Seed"),
    ("MOVE_GROWTH", "Growth"),
    ("MOVE_RAZOR_LEAF", "Razor Leaf"),
    ("MOVE_SOLAR_BEAM", "Solarbeam"),
    ("MOVE_POISON_POWDER", "Poisonpowder"),
    ("MOVE_STUN_SPORE", "Stun Spore"),
    ("MOVE_SLEEP_POWDER", "Sleep Powder"),
    ("MOVE_PETAL_DANCE", "Petal Dance"),
    ("MOVE_STRING_SHOT", "String Shot"),
    ("MOVE_DRAGON_RAGE", "Dragon Rage"),
    ("MOVE_FIRE_SPIN", "Fire Spin"),
    ("MOVE_THUNDER_SHOCK", "Thundershock"),
    ("MOVE_THUNDERBOLT", "Thunderbolt"),
    ("MOVE_THUNDER_WAVE", "Thunder Wave"),
    ("MOVE_THUNDER", "Thunder"),
    ("MOVE_ROCK_THROW", "Rock Throw"),
    ("MOVE_EARTHQUAKE", "Earthquake"),
    ("MOVE_FISSURE", "Fissure"),
    ("MOVE_DIG", "Dig"),
    ("MOVE_TOXIC", "Toxic"),
    ("MOVE_CONFUSION", "Confusion"),
    ("MOVE_PSYCHIC", "Psychic"),
    ("MOVE_HYPNOSIS", "Hypnosis"),
    ("MOVE_MEDITATE", "Meditate"),
    ("MOVE_AGILITY", "Agility"),
    ("MOVE_QUICK_ATTACK", "Quick Attack"),
    ("MOVE_RAGE", "Rage"),
    ("MOVE_TELEPORT", "Teleport"),
    ("MOVE_NIGHT_SHADE", "Night Shade"),
    ("MOVE_MIMIC", "Mimic"),
    ("MOVE_SCREECH", "Screech"),
    ("MOVE_DOUBLE_TEAM", "Double Team"),
    ("MOVE_RECOVER", "Recover"),
    ("MOVE_HARDEN", "Harden"),
    ("MOVE_MINIMIZE", "Minimize"),
    ("MOVE_SMOKESCREEN", "Smokescreen"),
    ("MOVE_CONFUSE_RAY", "Confuse Ray"),
    ("MOVE_WITHDRAW", "Withdraw"),
    ("MOVE_DEFENSE_CURL", "Defense Curl"),
    ("MOVE_BARRIER", "Barrier"),
    ("MOVE_LIGHT_SCREEN", "Light Screen"),
    ("MOVE_HAZE", "Haze"),
    ("MOVE_REFLECT", "Reflect"),
    ("MOVE_FOCUS_ENERGY", "Focus Energy"),
    ("MOVE_BIDE", "Bide"),
    ("MOVE_METRONOME", "Metronome"),
    ("MOVE_MIRROR_MOVE", "Mirror Move"),
    ("MOVE_SELF_DESTRUCT", "Selfdestruct"),
    ("MOVE_EGG_BOMB", "Egg Bomb"),
    ("MOVE_LICK", "Lick"),
    ("MOVE_SMOG", "Smog"),
    ("MOVE_SLUDGE", "Sludge"),
    ("MOVE_BONE_CLUB", "Bone Club"),
    ("MOVE_FIRE_BLAST", "Fire Blast"),
    ("MOVE_WATERFALL", "Waterfall"),
    ("MOVE_CLAMP", "Clamp"),
    ("MOVE_SWIFT", "Swift"),
    ("MOVE_SKULL_BASH", "Skull Bash"),
    ("MOVE_SPIKE_CANNON", "Spike Cannon"),
    ("MOVE_CONSTRICT", "Constrict"),
    ("MOVE_AMNESIA", "Amnesia"),
    ("MOVE_KINESIS", "Kinesis"),
    ("MOVE_SOFT_BOILED", "Softboiled"),
    ("MOVE_HI_JUMP_KICK", "Hi Jump Kick"),
    ("MOVE_GLARE", "Glare"),
    ("MOVE_DREAM_EATER", "Dream Eater"),
    ("MOVE_POISON_GAS", "Poison Gas"),
    ("MOVE_BARRAGE", "Barrage"),
    ("MOVE_LEECH_LIFE", "Leech Life"),
    ("MOVE_LOVELY_KISS", "Lovely Kiss"),
    ("MOVE_SKY_ATTACK", "Sky Attack"),
    ("MOVE_TRANSFORM", "Transform"),
    ("MOVE_BUBBLE", "Bubble"),
    ("MOVE_DIZZY_PUNCH", "Dizzy Punch"),
    ("MOVE_SPORE", "Spore"),
    ("MOVE_FLASH", "Flash"),
    ("MOVE_PSYWAVE", "Psywave"),
    ("MOVE_SPLASH", "Splash"),
    ("MOVE_ACID_ARMOR", "Acid Armor"),
    ("MOVE_CRABHAMMER", "Crabhammer"),
    ("MOVE_EXPLOSION", "Explosion"),
    ("MOVE_FURY_SWIPES", "Fury Swipes"),
    ("MOVE_BONEMERANG", "Bonemerang"),
    ("MOVE_REST", "Rest"),
    ("MOVE_ROCK_SLIDE", "Rock Slide"),
    ("MOVE_HYPER_FANG", "Hyper Fang"),
    ("MOVE_SHARPEN", "Sharpen"),
    ("MOVE_CONVERSION", "Conversion"),
    ("MOVE_TRI_ATTACK", "Tri Attack"),
    ("MOVE_SUPER_FANG", "Super Fang"),
    ("MOVE_SLASH", "Slash"),
    ("MOVE_SUBSTITUTE", "Substitute"),
    ("MOVE_SKETCH", "Sketch"),
    ("MOVE_TRIPLE_KICK", "Triple Kick"),
    ("MOVE_THIEF", "Thief"),
    ("MOVE_SPIDER_WEB", "Spider Web"),
    ("MOVE_MIND_READER", "Mind Reader"),
    ("MOVE_NIGHTMARE", "Nightmare"),
    ("MOVE_FLAME_WHEEL", "Flame Wheel"),
    ("MOVE_SNORE", "Snore"),
    ("MOVE_CURSE", "Curse"),
    ("MOVE_FLAIL", "Flail"),
    ("MOVE_CONVERSION_2", "Conversion 2"),
    ("MOVE_AEROBLAST", "Aeroblast"),
    ("MOVE_COTTON_SPORE", "Cotton Spore"),
    ("MOVE_REVERSAL", "Reversal"),
    ("MOVE_SPITE", "Spite"),
    ("MOVE_POWDER_SNOW", "Powder Snow"),
    ("MOVE_PROTECT", "Protect"),
    ("MOVE_MACH_PUNCH", "Mach Punch"),
    ("MOVE_SCARY_FACE", "Scary Face"),
    ("MOVE_FAINT_ATTACK", "Faint Attack"),
    ("MOVE_SWEET_KISS", "Sweet Kiss"),
    ("MOVE_BELLY_DRUM", "Belly Drum"),
    ("MOVE_SLUDGE_BOMB", "Sludge Bomb"),
    ("MOVE_MUD_SLAP", "Mud-Slap"),
    ("MOVE_OCTAZOOKA", "Octazooka"),
    ("MOVE_SPIKES", "Spikes"),
    ("MOVE_ZAP_CANNON", "Zap Cannon"),
    ("MOVE_FORESIGHT", "Foresight"),
    ("MOVE_DESTINY_BOND", "Destiny Bond"),
    ("MOVE_PERISH_SONG", "Perish Song"),
    ("MOVE_ICY_WIND", "Icy Wind"),
    ("MOVE_DETECT", "Detect"),
    ("MOVE_BONE_RUSH", "Bone Rush"),
    ("MOVE_LOCK_ON", "Lock-On"),
    ("MOVE_OUTRAGE", "Outrage"),
    ("MOVE_SANDSTORM", "Sandstorm"),
    ("MOVE_GIGA_DRAIN", "Giga Drain"),
    ("MOVE_ENDURE", "Endure"),
    ("MOVE_CHARM", "Charm"),
    ("MOVE_ROLLOUT", "Rollout"),
    ("MOVE_FALSE_SWIPE", "False Swipe"),
    ("MOVE_SWAGGER", "Swagger"),
    ("MOVE_MILK_DRINK", "Milk Drink"),
    ("MOVE_SPARK", "Spark"),
    ("MOVE_FURY_CUTTER", "Fury Cutter"),
    ("MOVE_STEEL_WING", "Steel Wing"),
    ("MOVE_MEAN_LOOK", "Mean Look"),
    ("MOVE_ATTRACT", "Attract"),
    ("MOVE_SLEEP_TALK", "Sleep Talk"),
    ("MOVE_HEAL_BELL", "Heal Bell"),
    ("MOVE_RETURN", "Return"),
    ("MOVE_PRESENT", "Present"),
    ("MOVE_FRUSTRATION", "Frustration"),
    ("MOVE_SAFEGUARD", "Safeguard"),
    ("MOVE_PAIN_SPLIT", "Pain Split"),
    ("MOVE_SACRED_FIRE", "Sacred Fire"),
    ("MOVE_MAGNITUDE", "Magnitude"),
    ("MOVE_DYNAMIC_PUNCH", "Dynamicpunch"),
    ("MOVE_MEGAHORN", "Megahorn"),
    ("MOVE_DRAGON_BREATH", "Dragonbreath"),
    ("MOVE_BATON_PASS", "Baton Pass"),
    ("MOVE_ENCORE", "Encore"),
    ("MOVE_PURSUIT", "Pursuit"),
    ("MOVE_RAPID_SPIN", "Rapid Spin"),
    ("MOVE_SWEET_SCENT", "Sweet Scent"),
    ("MOVE_IRON_TAIL", "Iron Tail"),
    ("MOVE_METAL_CLAW", "Metal Claw"),
    ("MOVE_VITAL_THROW", "Vital Throw"),
    ("MOVE_MORNING_SUN", "Morning Sun"),
    ("MOVE_SYNTHESIS", "Synthesis"),
    ("MOVE_MOONLIGHT", "Moonlight"),
    ("MOVE_HIDDEN_POWER", "Hidden Power"),
    ("MOVE_CROSS_CHOP", "Cross Chop"),
    ("MOVE_TWISTER", "Twister"),
    ("MOVE_RAIN_DANCE", "Rain Dance"),
    ("MOVE_SUNNY_DAY", "Sunny Day"),
    ("MOVE_CRUNCH", "Crunch"),
    ("MOVE_MIRROR_COAT", "Mirror Coat"),
    ("MOVE_PSYCH_UP", "Psych Up"),
    ("MOVE_EXTREME_SPEED", "Extremespeed"),
    ("MOVE_ANCIENT_POWER", "Ancientpower"),
    ("MOVE_SHADOW_BALL", "Shadow Ball"),
    ("MOVE_FUTURE_SIGHT", "Future Sight"),
    ("MOVE_ROCK_SMASH", "Rock Smash"),
    ("MOVE_WHIRLPOOL", "Whirlpool"),
    ("MOVE_BEAT_UP", "Beat Up"),
    ("MOVE_FAKE_OUT", "Fake Out"),
    ("MOVE_UPROAR", "Uproar"),
    ("MOVE_STOCKPILE", "Stockpile"),
    ("MOVE_SPIT_UP", "Spit Up"),
    ("MOVE_SWALLOW", "Swallow"),
    ("MOVE_HEAT_WAVE", "Heat Wave"),
    ("MOVE_HAIL", "Hail"),
    ("MOVE_TORMENT", "Torment"),
    ("MOVE_FLATTER", "Flatter"),
    ("MOVE_WILL_O_WISP", "Will-O-Wisp"),
    ("MOVE_MEMENTO", "Memento"),
    ("MOVE_FACADE", "Facade"),
    ("MOVE_FOCUS_PUNCH", "Focus Punch"),
    ("MOVE_SMELLINGSALT", "Smellingsalt"),
    ("MOVE_FOLLOW_ME", "Follow Me"),
    ("MOVE_NATURE_POWER", "Nature Power"),
    ("MOVE_CHARGE", "Charge"),
    ("MOVE_TAUNT", "Taunt"),
    ("MOVE_HELPING_HAND", "Helping Hand"),
    ("MOVE_TRICK", "Trick"),
    ("MOVE_ROLE_PLAY", "Role Play"),
    ("MOVE_WISH", "Wish"),
    ("MOVE_ASSIST", "Assist"),
    ("MOVE_INGRAIN", "Ingrain"),
    ("MOVE_SUPERPOWER", "Superpower"),
    ("MOVE_MAGIC_COAT", "Magic Coat"),
    ("MOVE_RECYCLE", "Recycle"),
    ("MOVE_REVENGE", "Revenge"),
    ("MOVE_BRICK_BREAK", "Brick Break"),
    ("MOVE_YAWN", "Yawn"),
    ("MOVE_KNOCK_OFF", "Knock Off"),
    ("MOVE_ENDEAVOR", "Endeavor"),
    ("MOVE_ERUPTION", "Eruption"),
    ("MOVE_SKILL_SWAP", "Skill Swap"),
    ("MOVE_IMPRISON", "Imprison"),
    ("MOVE_REFRESH", "Refresh"),
    ("MOVE_GRUDGE", "Grudge"),
    ("MOVE_SNATCH", "Snatch"),
    ("MOVE_SECRET_POWER", "Secret Power"),
    ("MOVE_DIVE", "Dive"),
    ("MOVE_ARM_THRUST", "Arm Thrust"),
    ("MOVE_CAMOUFLAGE", "Camouflage"),
    ("MOVE_TAIL_GLOW", "Tail Glow"),
    ("MOVE_LUSTER_PURGE", "Luster Purge"),
    ("MOVE_MIST_BALL", "Mist Ball"),
    ("MOVE_FEATHER_DANCE", "Featherdance"),
    ("MOVE_TEETER_DANCE", "Teeter Dance"),
    ("MOVE_BLAZE_KICK", "Blaze Kick"),
    ("MOVE_MUD_SPORT", "Mud Sport"),
    ("MOVE_ICE_BALL", "Ice Ball"),
    ("MOVE_NEEDLE_ARM", "Needle Arm"),
    ("MOVE_SLACK_OFF", "Slack Off"),
    ("MOVE_HYPER_VOICE", "Hyper Voice"),
    ("MOVE_POISON_FANG", "Poison Fang"),
    ("MOVE_CRUSH_CLAW", "Crush Claw"),
    ("MOVE_BLAST_BURN", "Blast Burn"),
    ("MOVE_HYDRO_CANNON", "Hydro Cannon"),
    ("MOVE_METEOR_MASH", "Meteor Mash"),
    ("MOVE_ASTONISH", "Astonish"),
    ("MOVE_WEATHER_BALL", "Weather Ball"),
    ("MOVE_AROMATHERAPY", "Aromatherapy"),
    ("MOVE_FAKE_TEARS", "Fake Tears"),
    ("MOVE_AIR_CUTTER", "Air Cutter"),
    ("MOVE_OVERHEAT", "Overheat"),
    ("MOVE_ODOR_SLEUTH", "Odor Sleuth"),
    ("MOVE_ROCK_TOMB", "Rock Tomb"),
    ("MOVE_SILVER_WIND", "Silver Wind"),
    ("MOVE_METAL_SOUND", "Metal Sound"),
    ("MOVE_GRASS_WHISTLE", "Grasswhistle"),
    ("MOVE_TICKLE", "Tickle"),
    ("MOVE_COSMIC_POWER", "Cosmic Power"),
    ("MOVE_WATER_SPOUT", "Water Spout"),
    ("MOVE_SIGNAL_BEAM", "Signal Beam"),
    ("MOVE_SHADOW_PUNCH", "Shadow Punch"),
    ("MOVE_EXTRASENSORY", "Extrasensory"),
    ("MOVE_SKY_UPPERCUT", "Sky Uppercut"),
    ("MOVE_SAND_TOMB", "Sand Tomb"),
    ("MOVE_SHEER_COLD", "Sheer Cold"),
    ("MOVE_MUDDY_WATER", "Muddy Water"),
    ("MOVE_BULLET_SEED", "Bullet Seed"),
    ("MOVE_AERIAL_ACE", "Aerial Ace"),
    ("MOVE_ICICLE_SPEAR", "Icicle Spear"),
    ("MOVE_IRON_DEFENSE", "Iron Defense"),
    ("MOVE_BLOCK", "Block"),
    ("MOVE_HOWL", "Howl"),
    ("MOVE_DRAGON_CLAW", "Dragon Claw"),
    ("MOVE_FRENZY_PLANT", "Frenzy Plant"),
    ("MOVE_BULK_UP", "Bulk Up"),
    ("MOVE_BOUNCE", "Bounce"),
    ("MOVE_MUD_SHOT", "Mud Shot"),
    ("MOVE_POISON_TAIL", "Poison Tail"),
    ("MOVE_COVET", "Covet"),
    ("MOVE_VOLT_TACKLE", "Volt Tackle"),
    ("MOVE_MAGICAL_LEAF", "Magical Leaf"),
    ("MOVE_WATER_SPORT", "Water Sport"),
    ("MOVE_CALM_MIND", "Calm Mind"),
    ("MOVE_LEAF_BLADE", "Leaf Blade"),
    ("MOVE_DRAGON_DANCE", "Dragon Dance"),
    ("MOVE_ROCK_BLAST", "Rock Blast"),
    ("MOVE_SHOCK_WAVE", "Shock Wave"),
    ("MOVE_WATER_PULSE", "Water Pulse"),
    ("MOVE_DOOM_DESIRE", "Doom Desire"),
    ("MOVE_PSYCHO_BOOST", "Psycho Boost"),
    ("MOVE_STRUGGLE", "Struggle"),
    ("MOVE_ROOST", "Roost"),
    ("MOVE_GRAVITY", "Gravity"),
    ("MOVE_MIRACLE_EYE", "Miracle Eye"),
    ("MOVE_WAKE_UP_SLAP", "Wake Up Slap"),
    ("MOVE_HAMMER_ARM", "Hammer Arm"),
    ("MOVE_GYRO_BALL", "Gyro Ball"),
    ("MOVE_HEALING_WISH", "Healing Wish"),
    ("MOVE_BRINE", "Brine"),
    ("MOVE_NATURAL_GIFT", "Natural Gift"),
    ("MOVE_FEINT", "Feint"),
    ("MOVE_PLUCK", "Pluck"),
    ("MOVE_TAILWIND", "Tailwind"),
    ("MOVE_ACUPRESSURE", "Acupressure"),
    ("MOVE_METAL_BURST", "Metal Burst"),
    ("MOVE_U_TURN", "U Turn"),
    ("MOVE_CLOSE_COMBAT", "Close Combat"),
    ("MOVE_PAYBACK", "Payback"),
    ("MOVE_ASSURANCE", "Assurance"),
    ("MOVE_EMBARGO", "Embargo"),
    ("MOVE_FLING", "Fling"),
    ("MOVE_PSYCHO_SHIFT", "Psycho Shift"),
    ("MOVE_TRUMP_CARD", "Trump Card"),
    ("MOVE_HEAL_BLOCK", "Heal Block"),
    ("MOVE_WRING_OUT", "Wring Out"),
    ("MOVE_POWER_TRICK", "Power Trick"),
    ("MOVE_GASTRO_ACID", "Gastro Acid"),
    ("MOVE_LUCKY_CHANT", "Lucky Chant"),
    ("MOVE_ME_FIRST", "Me First"),
    ("MOVE_COPYCAT", "Copycat"),
    ("MOVE_POWER_SWAP", "Power Swap"),
    ("MOVE_GUARD_SWAP", "Guard Swap"),
    ("MOVE_PUNISHMENT", "Punishment"),
    ("MOVE_LAST_RESORT", "Last Resort"),
    ("MOVE_WORRY_SEED", "Worry Seed"),
    ("MOVE_SUCKER_PUNCH", "Sucker Punch"),
    ("MOVE_TOXIC_SPIKES", "Toxic Spikes"),
    ("MOVE_HEART_SWAP", "Heart Swap"),
    ("MOVE_AQUA_RING", "Aqua Ring"),
    ("MOVE_MAGNET_RISE", "Magnet Rise"),
    ("MOVE_FLARE_BLITZ", "Flare Blitz"),
    ("MOVE_FORCE_PALM", "Force Palm"),
    ("MOVE_AURA_SPHERE", "Aura Sphere"),
    ("MOVE_ROCK_POLISH", "Rock Polish"),
    ("MOVE_POISON_JAB", "Poison Jab"),
    ("MOVE_DARK_PULSE", "Dark Pulse"),
    ("MOVE_NIGHT_SLASH", "Night Slash"),
    ("MOVE_AQUA_TAIL", "Aqua Tail"),
    ("MOVE_SEED_BOMB", "Seed Bomb"),
    ("MOVE_AIR_SLASH", "Air Slash"),
    ("MOVE_X_SCISSOR", "X Scissor"),
    ("MOVE_BUG_BUZZ", "Bug Buzz"),
    ("MOVE_DRAGON_PULSE", "Dragon Pulse"),
    ("MOVE_DRAGON_RUSH", "Dragon Rush"),
    ("MOVE_POWER_GEM", "Power Gem"),
    ("MOVE_DRAIN_PUNCH", "Drain Punch"),
    ("MOVE_VACUUM_WAVE", "Vacuum Wave"),
    ("MOVE_FOCUS_BLAST", "Focus Blast"),
    ("MOVE_ENERGY_BALL", "Energy Ball"),
    ("MOVE_BRAVE_BIRD", "Brave Bird"),
    ("MOVE_EARTH_POWER", "Earth Power"),
    ("MOVE_SWITCHEROO", "Switcheroo"),
    ("MOVE_GIGA_IMPACT", "Giga Impact"),
    ("MOVE_NASTY_PLOT", "Nasty Plot"),
    ("MOVE_BULLET_PUNCH", "Bullet Punch"),
    ("MOVE_AVALANCHE", "Avalanche"),
    ("MOVE_ICE_SHARD", "Ice Shard"),
    ("MOVE_SHADOW_CLAW", "Shadow Claw"),
    ("MOVE_THUNDER_FANG", "Thunder Fang"),
    ("MOVE_ICE_FANG", "Ice Fang"),
    ("MOVE_FIRE_FANG", "Fire Fang"),
    ("MOVE_SHADOW_SNEAK", "Shadow Sneak"),
    ("MOVE_MUD_BOMB", "Mud Bomb"),
    ("MOVE_PSYCHO_CUT", "Psycho Cut"),
    ("MOVE_ZEN_HEADBUTT", "Zen Headbutt"),
    ("MOVE_MIRROR_SHOT", "Mirror Shot"),
    ("MOVE_FLASH_CANNON", "Flash Cannon"),
    ("MOVE_ROCK_CLIMB", "Rock Climb"),
    ("MOVE_DEFOG", "Defog"),
    ("MOVE_TRICK_ROOM", "Trick Room"),
    ("MOVE_DRACO_METEOR", "Draco Meteor"),
    ("MOVE_DISCHARGE", "Discharge"),
    ("MOVE_LAVA_PLUME", "Lava Plume"),
    ("MOVE_LEAF_STORM", "Leaf Storm"),
    ("MOVE_POWER_WHIP", "Power Whip"),
    ("MOVE_ROCK_WRECKER", "Rock Wrecker"),
    ("MOVE_CROSS_POISON", "Cross Poison"),
    ("MOVE_GUNK_SHOT", "Gunk Shot"),
    ("MOVE_IRON_HEAD", "Iron Head"),
    ("MOVE_MAGNET_BOMB", "Magnet Bomb"),
    ("MOVE_STONE_EDGE", "Stone Edge"),
    ("MOVE_CAPTIVATE", "Captivate"),
    ("MOVE_STEALTH_ROCK", "Stealth Rock"),
    ("MOVE_GRASS_KNOT", "Grass Knot"),
    ("MOVE_CHATTER", "Chatter"),
    ("MOVE_JUDGMENT", "Judgment"),
    ("MOVE_BUG_BITE", "Bug Bite"),
    ("MOVE_CHARGE_BEAM", "Charge Beam"),
    ("MOVE_WOOD_HAMMER", "Wood Hammer"),
    ("MOVE_AQUA_JET", "Aqua Jet"),
    ("MOVE_ATTACK_ORDER", "Attack Order"),
    ("MOVE_DEFEND_ORDER", "Defend Order"),
    ("MOVE_HEAL_ORDER", "Heal Order"),
    ("MOVE_HEAD_SMASH", "Head Smash"),
    ("MOVE_DOUBLE_HIT", "Double Hit"),
    ("MOVE_ROAR_OF_TIME", "Roar Of Time"),
    ("MOVE_SPACIAL_REND", "Spacial Rend"),
    ("MOVE_LUNAR_DANCE", "Lunar Dance"),
    ("MOVE_CRUSH_GRIP", "Crush Grip"),
    ("MOVE_MAGMA_STORM", "Magma Storm"),
    ("MOVE_DARK_VOID", "Dark Void"),
    ("MOVE_SEED_FLARE", "Seed Flare"),
    ("MOVE_OMINOUS_WIND", "Ominous Wind"),
    ("MOVE_SHADOW_FORCE", "Shadow Force"),
    ("MOVE_HONE_CLAWS", "Hone Claws"),
    ("MOVE_WIDE_GUARD", "Wide Guard"),
    ("MOVE_GUARD_SPLIT", "Guard Split"),
    ("MOVE_POWER_SPLIT", "Power Split"),
    ("MOVE_WONDER_ROOM", "Wonder Room"),
    ("MOVE_PSYSHOCK", "Psyshock"),
    ("MOVE_VENOSHOCK", "Venoshock"),
    ("MOVE_AUTOTOMIZE", "Autotomize"),
    ("MOVE_RAGE_POWDER", "Rage Powder"),
    ("MOVE_TELEKINESIS", "Telekinesis"),
    ("MOVE_MAGIC_ROOM", "Magic Room"),
    ("MOVE_SMACK_DOWN", "Smack Down"),
    ("MOVE_STORM_THROW", "Storm Throw"),
    ("MOVE_FLAME_BURST", "Flame Burst"),
    ("MOVE_SLUDGE_WAVE", "Sludge Wave"),
    ("MOVE_QUIVER_DANCE", "Quiver Dance"),
    ("MOVE_HEAVY_SLAM", "Heavy Slam"),
    ("MOVE_SYNCHRONOISE", "Synchronoise"),
    ("MOVE_ELECTRO_BALL", "Electro Ball"),
    ("MOVE_SOAK", "Soak"),
    ("MOVE_FLAME_CHARGE", "Flame Charge"),
    ("MOVE_COIL", "Coil"),
    ("MOVE_LOW_SWEEP", "Low Sweep"),
    ("MOVE_ACID_SPRAY", "Acid Spray"),
    ("MOVE_FOUL_PLAY", "Foul Play"),
    ("MOVE_SIMPLE_BEAM", "Simple Beam"),
    ("MOVE_ENTRAINMENT", "Entrainment"),
    ("MOVE_AFTER_YOU", "After You"),
    ("MOVE_ROUND", "Round"),
    ("MOVE_ECHOED_VOICE", "Echoed Voice"),
    ("MOVE_CHIP_AWAY", "Chip Away"),
    ("MOVE_CLEAR_SMOG", "Clear Smog"),
    ("MOVE_STORED_POWER", "Stored Power"),
    ("MOVE_QUICK_GUARD", "Quick Guard"),
    ("MOVE_ALLY_SWITCH", "Ally Switch"),
    ("MOVE_SCALD", "Scald"),
    ("MOVE_SHELL_SMASH", "Shell Smash"),
    ("MOVE_HEAL_PULSE", "Heal Pulse"),
    ("MOVE_HEX", "Hex"),
    ("MOVE_SKY_DROP", "Sky Drop"),
    ("MOVE_SHIFT_GEAR", "Shift Gear"),
    ("MOVE_CIRCLE_THROW", "Circle Throw"),
    ("MOVE_INCINERATE", "Incinerate"),
    ("MOVE_QUASH", "Quash"),
    ("MOVE_ACROBATICS", "Acrobatics"),
    ("MOVE_REFLECT_TYPE", "Reflect Type"),
    ("MOVE_RETALIATE", "Retaliate"),
    ("MOVE_FINAL_GAMBIT", "Final Gambit"),
    ("MOVE_BESTOW", "Bestow"),
    ("MOVE_INFERNO", "Inferno"),
    ("MOVE_WATER_PLEDGE", "Water Pledge"),
    ("MOVE_FIRE_PLEDGE", "Fire Pledge"),
    ("MOVE_GRASS_PLEDGE", "Grass Pledge"),
    ("MOVE_VOLT_SWITCH", "Volt Switch"),
    ("MOVE_STRUGGLE_BUG", "Struggle Bug"),
    ("MOVE_BULLDOZE", "Bulldoze"),
    ("MOVE_FROST_BREATH", "Frost Breath"),
    ("MOVE_DRAGON_TAIL", "Dragon Tail"),
    ("MOVE_WORK_UP", "Work Up"),
    ("MOVE_ELECTROWEB", "Electroweb"),
    ("MOVE_WILD_CHARGE", "Wild Charge"),
    ("MOVE_DRILL_RUN", "Drill Run"),
    ("MOVE_DUAL_CHOP", "Dual Chop"),
    ("MOVE_HEART_STAMP", "Heart Stamp"),
    ("MOVE_HORN_LEECH", "Horn Leech"),
    ("MOVE_SACRED_SWORD", "Sacred Sword"),
    ("MOVE_RAZOR_SHELL", "Razor Shell"),
    ("MOVE_HEAT_CRASH", "Heat Crash"),
    ("MOVE_LEAF_TORNADO", "Leaf Tornado"),
    ("MOVE_STEAMROLLER", "Steamroller"),
    ("MOVE_COTTON_GUARD", "Cotton Guard"),
    ("MOVE_NIGHT_DAZE", "Night Daze"),
    ("MOVE_PSYSTRIKE", "Psystrike"),
    ("MOVE_TAIL_SLAP", "Tail Slap"),
    ("MOVE_HURRICANE", "Hurricane"),
    ("MOVE_HEAD_CHARGE", "Head Charge"),
    ("MOVE_GEAR_GRIND", "Gear Grind"),
    ("MOVE_SEARING_SHOT", "Searing Shot"),
    ("MOVE_TECHNO_BLAST", "Techno Blast"),
    ("MOVE_RELIC_SONG", "Relic Song"),
    ("MOVE_SECRET_SWORD", "Secret Sword"),
    ("MOVE_GLACIATE", "Glaciate"),
    ("MOVE_BOLT_STRIKE", "Bolt Strike"),
    ("MOVE_BLUE_FLARE", "Blue Flare"),
    ("MOVE_FIERY_DANCE", "Fiery Dance"),
    ("MOVE_FREEZE_SHOCK", "Freeze Shock"),
    ("MOVE_ICE_BURN", "Ice Burn"),
    ("MOVE_SNARL", "Snarl"),
    ("MOVE_ICICLE_CRASH", "Icicle Crash"),
    ("MOVE_V_CREATE", "V Create"),
    ("MOVE_FUSION_FLARE", "Fusion Flare"),
    ("MOVE_FUSION_BOLT", "Fusion Bolt"),
    ("MOVE_FLYING_PRESS", "Flying Press"),
    ("MOVE_MAT_BLOCK", "Mat Block"),
    ("MOVE_BELCH", "Belch"),
    ("MOVE_ROTOTILLER", "Rototiller"),
    ("MOVE_STICKY_WEB", "Sticky Web"),
    ("MOVE_FELL_STINGER", "Fell Stinger"),
    ("MOVE_PHANTOM_FORCE", "Phantom Force"),
    ("MOVE_TRICK_OR_TREAT", "Trick Or Treat"),
    ("MOVE_NOBLE_ROAR", "Noble Roar"),
    ("MOVE_ION_DELUGE", "Ion Deluge"),
    ("MOVE_PARABOLIC_CHARGE", "Parabolic Charge"),
    ("MOVE_FORESTS_CURSE", "Forests Curse"),
    ("MOVE_PETAL_BLIZZARD", "Petal Blizzard"),
    ("MOVE_FREEZE_DRY", "Freeze Dry"),
    ("MOVE_DISARMING_VOICE", "Disarming Voice"),
    ("MOVE_PARTING_SHOT", "Parting Shot"),
    ("MOVE_TOPSY_TURVY", "Topsy Turvy"),
    ("MOVE_DRAINING_KISS", "Draining Kiss"),
    ("MOVE_CRAFTY_SHIELD", "Crafty Shield"),
    ("MOVE_FLOWER_SHIELD", "Flower Shield"),
    ("MOVE_GRASSY_TERRAIN", "Grassy Terrain"),
    ("MOVE_MISTY_TERRAIN", "Misty Terrain"),
    ("MOVE_ELECTRIFY", "Electrify"),
    ("MOVE_PLAY_ROUGH", "Play Rough"),
    ("MOVE_FAIRY_WIND", "Fairy Wind"),
    ("MOVE_MOONBLAST", "Moonblast"),
    ("MOVE_BOOMBURST", "Boomburst"),
    ("MOVE_FAIRY_LOCK", "Fairy Lock"),
    ("MOVE_KINGS_SHIELD", "Kings Shield"),
    ("MOVE_PLAY_NICE", "Play Nice"),
    ("MOVE_CONFIDE", "Confide"),
    ("MOVE_DIAMOND_STORM", "Diamond Storm"),
    ("MOVE_STEAM_ERUPTION", "Steam Eruption"),
    ("MOVE_HYPERSPACE_HOLE", "Hyperspace Hole"),
    ("MOVE_WATER_SHURIKEN", "Water Shuriken"),
    ("MOVE_MYSTICAL_FIRE", "Mystical Fire"),
    ("MOVE_SPIKY_SHIELD", "Spiky Shield"),
    ("MOVE_AROMATIC_MIST", "Aromatic Mist"),
    ("MOVE_EERIE_IMPULSE", "Eerie Impulse"),
    ("MOVE_VENOM_DRENCH", "Venom Drench"),
    ("MOVE_POWDER", "Powder"),
    ("MOVE_GEOMANCY", "Geomancy"),
    ("MOVE_MAGNETIC_FLUX", "Magnetic Flux"),
    ("MOVE_HAPPY_HOUR", "Happy Hour"),
    ("MOVE_ELECTRIC_TERRAIN", "Electric Terrain"),
    ("MOVE_DAZZLING_GLEAM", "Dazzling Gleam"),
    ("MOVE_CELEBRATE", "Celebrate"),
    ("MOVE_HOLD_HANDS", "Hold Hands"),
    ("MOVE_BABY_DOLL_EYES", "Baby Doll Eyes"),
    ("MOVE_NUZZLE", "Nuzzle"),
    ("MOVE_HOLD_BACK", "Hold Back"),
    ("MOVE_INFESTATION", "Infestation"),
    ("MOVE_POWER_UP_PUNCH", "Power Up Punch"),
    ("MOVE_OBLIVION_WING", "Oblivion Wing"),
    ("MOVE_THOUSAND_ARROWS", "Thousand Arrows"),
    ("MOVE_THOUSAND_WAVES", "Thousand Waves"),
    ("MOVE_LANDS_WRATH", "Lands Wrath"),
    ("MOVE_LIGHT_OF_RUIN", "Light Of Ruin"),
    ("MOVE_ORIGIN_PULSE", "Origin Pulse"),
    ("MOVE_PRECIPICE_BLADES", "Precipice Blades"),
    ("MOVE_DRAGON_ASCENT", "Dragon Ascent"),
    ("MOVE_HYPERSPACE_FURY", "Hyperspace Fury"),
    ("MOVE_SHORE_UP", "Shore Up"),
    ("MOVE_FIRST_IMPRESSION", "First Impression"),
    ("MOVE_BANEFUL_BUNKER", "Baneful Bunker"),
    ("MOVE_SPIRIT_SHACKLE", "Spirit Shackle"),
    ("MOVE_DARKEST_LARIAT", "Darkest Lariat"),
    ("MOVE_SPARKLING_ARIA", "Sparkling Aria"),
    ("MOVE_ICE_HAMMER", "Ice Hammer"),
    ("MOVE_FLORAL_HEALING", "Floral Healing"),
    ("MOVE_HIGH_HORSEPOWER", "High Horsepower"),
    ("MOVE_STRENGTH_SAP", "Strength Sap"),
    ("MOVE_SOLAR_BLADE", "Solar Blade"),
    ("MOVE_LEAFAGE", "Leafage"),
    ("MOVE_SPOTLIGHT", "Spotlight"),
    ("MOVE_TOXIC_THREAD", "Toxic Thread"),
    ("MOVE_LASER_FOCUS", "Laser Focus"),
    ("MOVE_GEAR_UP", "Gear Up"),
    ("MOVE_THROAT_CHOP", "Throat Chop"),
    ("MOVE_POLLEN_PUFF", "Pollen Puff"),
    ("MOVE_ANCHOR_SHOT", "Anchor Shot"),
    ("MOVE_PSYCHIC_TERRAIN", "Psychic Terrain"),
    ("MOVE_LUNGE", "Lunge"),
    ("MOVE_FIRE_LASH", "Fire Lash"),
    ("MOVE_POWER_TRIP", "Power Trip"),
    ("MOVE_BURN_UP", "Burn Up"),
    ("MOVE_SPEED_SWAP", "Speed Swap"),
    ("MOVE_SMART_STRIKE", "Smart Strike"),
    ("MOVE_PURIFY", "Purify"),
    ("MOVE_REVELATION_DANCE", "Revelation Dance"),
    ("MOVE_CORE_ENFORCER", "Core Enforcer"),
    ("MOVE_TROP_KICK", "Trop Kick"),
    ("MOVE_INSTRUCT", "Instruct"),
    ("MOVE_BEAK_BLAST", "Beak Blast"),
    ("MOVE_CLANGING_SCALES", "Clanging Scales"),
    ("MOVE_DRAGON_HAMMER", "Dragon Hammer"),
    ("MOVE_BRUTAL_SWING", "Brutal Swing"),
    ("MOVE_AURORA_VEIL", "Aurora Veil"),
    ("MOVE_SHELL_TRAP", "Shell Trap"),
    ("MOVE_FLEUR_CANNON", "Fleur Cannon"),
    ("MOVE_PSYCHIC_FANGS", "Psychic Fangs"),
    ("MOVE_STOMPING_TANTRUM", "Stomping Tantrum"),
    ("MOVE_SHADOW_BONE", "Shadow Bone"),
    ("MOVE_ACCELEROCK", "Accelerock"),
    ("MOVE_LIQUIDATION", "Liquidation"),
    ("MOVE_PRISMATIC_LASER", "Prismatic Laser"),
    ("MOVE_SPECTRAL_THIEF", "Spectral Thief"),
    ("MOVE_SUNSTEEL_STRIKE", "Sunsteel Strike"),
    ("MOVE_MOONGEIST_BEAM", "Moongeist Beam"),
    ("MOVE_TEARFUL_LOOK", "Tearful Look"),
    ("MOVE_ZING_ZAP", "Zing Zap"),
    ("MOVE_NATURES_MADNESS", "Natures Madness"),
    ("MOVE_MULTI_ATTACK", "Multi Attack"),
    ("MOVE_MIND_BLOWN", "Mind Blown"),
    ("MOVE_PLASMA_FISTS", "Plasma Fists"),
    ("MOVE_PHOTON_GEYSER", "Photon Geyser"),
    ("MOVE_ZIPPY_ZAP", "Zippy Zap"),
    ("MOVE_SPLISHY_SPLASH", "Splishy Splash"),
    ("MOVE_FLOATY_FALL", "Floaty Fall"),
    ("MOVE_PIKA_PAPOW", "Pika Papow"),
    ("MOVE_BOUNCY_BUBBLE", "Bouncy Bubble"),
    ("MOVE_BUZZY_BUZZ", "Buzzy Buzz"),
    ("MOVE_SIZZLY_SLIDE", "Sizzly Slide"),
    ("MOVE_GLITZY_GLOW", "Glitzy Glow"),
    ("MOVE_BADDY_BAD", "Baddy Bad"),
    ("MOVE_SAPPY_SEED", "Sappy Seed"),
    ("MOVE_FREEZY_FROST", "Freezy Frost"),
    ("MOVE_SPARKLY_SWIRL", "Sparkly Swirl"),
    ("MOVE_VEEVEE_VOLLEY", "Veevee Volley"),
    ("MOVE_DOUBLE_IRON_BASH", "Double Iron Bash"),
    ("MOVE_DYNAMAX_CANNON", "Dynamax Cannon"),
    ("MOVE_SNIPE_SHOT", "Snipe Shot"),
    ("MOVE_JAW_LOCK", "Jaw Lock"),
    ("MOVE_STUFF_CHEEKS", "Stuff Cheeks"),
    ("MOVE_NO_RETREAT", "No Retreat"),
    ("MOVE_TAR_SHOT", "Tar Shot"),
    ("MOVE_MAGIC_POWDER", "Magic Powder"),
    ("MOVE_DRAGON_DARTS", "Dragon Darts"),
    ("MOVE_TEATIME", "Teatime"),
    ("MOVE_OCTOLOCK", "Octolock"),
    ("MOVE_BOLT_BEAK", "Bolt Beak"),
    ("MOVE_FISHIOUS_REND", "Fishious Rend"),
    ("MOVE_COURT_CHANGE", "Court Change"),
    ("MOVE_CLANGOROUS_SOUL", "Clangorous Soul"),
    ("MOVE_BODY_PRESS", "Body Press"),
    ("MOVE_DECORATE", "Decorate"),
    ("MOVE_DRUM_BEATING", "Drum Beating"),
    ("MOVE_SNAP_TRAP", "Snap Trap"),
    ("MOVE_PYRO_BALL", "Pyro Ball"),
    ("MOVE_BEHEMOTH_BLADE", "Behemoth Blade"),
    ("MOVE_BEHEMOTH_BASH", "Behemoth Bash"),
    ("MOVE_AURA_WHEEL", "Aura Wheel"),
    ("MOVE_BREAKING_SWIPE", "Breaking Swipe"),
    ("MOVE_BRANCH_POKE", "Branch Poke"),
    ("MOVE_OVERDRIVE", "Overdrive"),
    ("MOVE_APPLE_ACID", "Apple Acid"),
    ("MOVE_GRAV_APPLE", "Grav Apple"),
    ("MOVE_SPIRIT_BREAK", "Spirit Break"),
    ("MOVE_STRANGE_STEAM", "Strange Steam"),
    ("MOVE_LIFE_DEW", "Life Dew"),
    ("MOVE_OBSTRUCT", "Obstruct"),
    ("MOVE_FALSE_SURRENDER", "False Surrender"),
    ("MOVE_METEOR_ASSAULT", "Meteor Assault"),
    ("MOVE_ETERNABEAM", "Eternabeam"),
    ("MOVE_STEEL_BEAM", "Steel Beam"),
    ("MOVE_EXPANDING_FORCE", "Expanding Force"),
    ("MOVE_STEEL_ROLLER", "Steel Roller"),
    ("MOVE_SCALE_SHOT", "Scale Shot"),
    ("MOVE_METEOR_BEAM", "Meteor Beam"),
    ("MOVE_SHELL_SIDE_ARM", "Shell Side Arm"),
    ("MOVE_MISTY_EXPLOSION", "Misty Explosion"),
    ("MOVE_GRASSY_GLIDE", "Grassy Glide"),
    ("MOVE_RISING_VOLTAGE", "Rising Voltage"),
    ("MOVE_TERRAIN_PULSE", "Terrain Pulse"),
    ("MOVE_SKITTER_SMACK", "Skitter Smack"),
    ("MOVE_BURNING_JEALOUSY", "Burning Jealousy"),
    ("MOVE_LASH_OUT", "Lash Out"),
    ("MOVE_POLTERGEIST", "Poltergeist"),
    ("MOVE_CORROSIVE_GAS", "Corrosive Gas"),
    ("MOVE_COACHING", "Coaching"),
    ("MOVE_FLIP_TURN", "Flip Turn"),
    ("MOVE_TRIPLE_AXEL", "Triple Axel"),
    ("MOVE_DUAL_WINGBEAT", "Dual Wingbeat"),
    ("MOVE_SCORCHING_SANDS", "Scorching Sands"),
    ("MOVE_JUNGLE_HEALING", "Jungle Healing"),
    ("MOVE_WICKED_BLOW", "Wicked Blow"),
    ("MOVE_SURGING_STRIKES", "Surging Strikes"),
    ("MOVE_THUNDER_CAGE", "Thunder Cage"),
    ("MOVE_DRAGON_ENERGY", "Dragon Energy"),
    ("MOVE_FREEZING_GLARE", "Freezing Glare"),
    ("MOVE_FIERY_WRATH", "Fiery Wrath"),
    ("MOVE_THUNDEROUS_KICK", "Thunderous Kick"),
    ("MOVE_GLACIAL_LANCE", "Glacial Lance"),
    ("MOVE_ASTRAL_BARRAGE", "Astral Barrage"),
    ("MOVE_EERIE_SPELL", "Eerie Spell"),
    ("MOVE_DIRE_CLAW", "Dire Claw"),
    ("MOVE_PSYSHIELD_BASH", "Psyshield Bash"),
    ("MOVE_POWER_SHIFT", "Power Shift"),
    ("MOVE_STONE_AXE", "Stone Axe"),
    ("MOVE_SPRINGTIDE_STORM", "Springtide Storm"),
    ("MOVE_MYSTICAL_POWER", "Mystical Power"),
    ("MOVE_RAGING_FURY", "Raging Fury"),
    ("MOVE_WAVE_CRASH", "Wave Crash"),
    ("MOVE_CHLOROBLAST", "Chloroblast"),
    ("MOVE_MOUNTAIN_GALE", "Mountain Gale"),
    ("MOVE_VICTORY_DANCE", "Victory Dance"),
    ("MOVE_HEADLONG_RUSH", "Headlong Rush"),
    ("MOVE_BARB_BARRAGE", "Barb Barrage"),
    ("MOVE_ESPER_WING", "Esper Wing"),
    ("MOVE_BITTER_MALICE", "Bitter Malice"),
    ("MOVE_SHELTER", "Shelter"),
    ("MOVE_TRIPLE_ARROWS", "Triple Arrows"),
    ("MOVE_INFERNAL_PARADE", "Infernal Parade"),
    ("MOVE_CEASELESS_EDGE", "Ceaseless Edge"),
    ("MOVE_BLEAKWIND_STORM", "Bleakwind Storm"),
    ("MOVE_WILDBOLT_STORM", "Wildbolt Storm"),
    ("MOVE_SANDSEAR_STORM", "Sandsear Storm"),
    ("MOVE_LUNAR_BLESSING", "Lunar Blessing"),
    ("MOVE_TAKE_HEART", "Take Heart"),
    ("MOVE_TERA_BLAST", "Tera Blast"),
    ("MOVE_SILK_TRAP", "Silk Trap"),
    ("MOVE_AXE_KICK", "Axe Kick"),
    ("MOVE_LAST_RESPECTS", "Last Respects"),
    ("MOVE_LUMINA_CRASH", "Lumina Crash"),
    ("MOVE_ORDER_UP", "Order Up"),
    ("MOVE_JET_PUNCH", "Jet Punch"),
    ("MOVE_SPICY_EXTRACT", "Spicy Extract"),
    ("MOVE_SPIN_OUT", "Spin Out"),
    ("MOVE_POPULATION_BOMB", "Population Bomb"),
    ("MOVE_ICE_SPINNER", "Ice Spinner"),
    ("MOVE_GLAIVE_RUSH", "Glaive Rush"),
    ("MOVE_REVIVAL_BLESSING", "Revival Blessing"),
    ("MOVE_SALT_CURE", "Salt Cure"),
    ("MOVE_TRIPLE_DIVE", "Triple Dive"),
    ("MOVE_MORTAL_SPIN", "Mortal Spin"),
    ("MOVE_DOODLE", "Doodle"),
    ("MOVE_FILLET_AWAY", "Fillet Away"),
    ("MOVE_KOWTOW_CLEAVE", "Kowtow Cleave"),
    ("MOVE_FLOWER_TRICK", "Flower Trick"),
    ("MOVE_TORCH_SONG", "Torch Song"),
    ("MOVE_AQUA_STEP", "Aqua Step"),
    ("MOVE_RAGING_BULL", "Raging Bull"),
    ("MOVE_MAKE_IT_RAIN", "Make It Rain"),
    ("MOVE_RUINATION", "Ruination"),
    ("MOVE_COLLISION_COURSE", "Collision Course"),
    ("MOVE_ELECTRO_DRIFT", "Electro Drift"),
    ("MOVE_SHED_TAIL", "Shed Tail"),
    ("MOVE_CHILLY_RECEPTION", "Chilly Reception"),
    ("MOVE_TIDY_UP", "Tidy Up"),
    ("MOVE_SNOWSCAPE", "Snowscape"),
    ("MOVE_POUNCE", "Pounce"),
    ("MOVE_TRAILBLAZE", "Trailblaze"),
    ("MOVE_CHILLING_WATER", "Chilling Water"),
    ("MOVE_HYPER_DRILL", "Hyper Drill"),
    ("MOVE_TWIN_BEAM", "Twin Beam"),
    ("MOVE_RAGE_FIST", "Rage Fist"),
    ("MOVE_ARMOR_CANNON", "Armor Cannon"),
    ("MOVE_BITTER_BLADE", "Bitter Blade"),
    ("MOVE_DOUBLE_SHOCK", "Double Shock"),
    ("MOVE_GIGATON_HAMMER", "Gigaton Hammer"),
    ("MOVE_COMEUPPANCE", "Comeuppance"),
    ("MOVE_AQUA_CUTTER", "Aqua Cutter"),
    ("MOVE_BLAZING_TORQUE", "Blazing Torque"),
    ("MOVE_WICKED_TORQUE", "Wicked Torque"),
    ("MOVE_NOXIOUS_TORQUE", "Noxious Torque"),
    ("MOVE_COMBAT_TORQUE", "Combat Torque"),
    ("MOVE_MAGICAL_TORQUE", "Magical Torque"),
    ("MOVE_PSYBLADE", "Psyblade"),
    ("MOVE_HYDRO_STEAM", "Hydro Steam"),
    ("MOVE_BLOOD_MOON", "Blood Moon"),
    ("MOVE_MATCHA_GOTCHA", "Matcha Gotcha"),
    ("MOVE_SYRUP_BOMB", "Syrup Bomb"),
    ("MOVE_IVY_CUDGEL", "Ivy Cudgel"),
    ("MOVE_ELECTRO_SHOT", "Electro Shot"),
    ("MOVE_TERA_STARSTORM", "Tera Starstorm"),
    ("MOVE_FICKLE_BEAM", "Fickle Beam"),
    ("MOVE_BURNING_BULWARK", "Burning Bulwark"),
    ("MOVE_THUNDERCLAP", "Thunderclap"),
    ("MOVE_MIGHTY_CLEAVE", "Mighty Cleave"),
    ("MOVE_TACHYON_CUTTER", "Tachyon Cutter"),
    ("MOVE_HARD_PRESS", "Hard Press"),
    ("MOVE_DRAGON_CHEER", "Dragon Cheer"),
    ("MOVE_ALLURING_VOICE", "Alluring Voice"),
    ("MOVE_TEMPER_FLARE", "Temper Flare"),
    ("MOVE_SUPERCELL_SLAM", "Supercell Slam"),
    ("MOVE_PSYCHIC_NOISE", "Psychic Noise"),
    ("MOVE_UPPER_HAND", "Upper Hand"),
    ("MOVE_MALIGNANT_CHAIN", "Malignant Chain"),
]
all_legendary_pokemon: list[str] = [
    "SPECIES_ARTICUNO",
    "SPECIES_ZAPDOS",
    "SPECIES_MOLTRES",
    "SPECIES_MEWTWO",
    "SPECIES_MEW",
    "SPECIES_RAIKOU",
    "SPECIES_ENTEI",
    "SPECIES_SUICUNE",
    "SPECIES_LUGIA",
    "SPECIES_HO_OH",
    "SPECIES_CELEBI",
    "SPECIES_REGIROCK",
    "SPECIES_REGICE",
    "SPECIES_REGISTEEL",
    "SPECIES_LATIAS",
    "SPECIES_LATIOS",
    "SPECIES_KYOGRE",
    "SPECIES_GROUDON",
    "SPECIES_RAYQUAZA",
    "SPECIES_JIRACHI",
    "SPECIES_DEOXYS",
    "SPECIES_UXIE",
    "SPECIES_MESPRIT",
    "SPECIES_AZELF",
    "SPECIES_DIALGA",
    "SPECIES_PALKIA",
    "SPECIES_HEATRAN",
    "SPECIES_REGIGIGAS",
    "SPECIES_GIRATINA",
    "SPECIES_CRESSELIA",
    "SPECIES_PHIONE",
    "SPECIES_MANAPHY",
    "SPECIES_DARKRAI",
    "SPECIES_SHAYMIN",
    "SPECIES_ARCEUS",
    "SPECIES_VICTINI",
    "SPECIES_COBALION",
    "SPECIES_TERRAKION",
    "SPECIES_VIRIZION",
    "SPECIES_KELDEO",
    "SPECIES_TORNADUS",
    "SPECIES_THUNDURUS",
    "SPECIES_LANDORUS",
    "SPECIES_RESHIRAM",
    "SPECIES_ZEKROM",
    "SPECIES_KYUREM",
    "SPECIES_MELOETTA",
    "SPECIES_GENESECT",
    "SPECIES_XERNEAS",
    "SPECIES_YVELTAL",
    "SPECIES_ZYGARDE",
    "SPECIES_DIANCIE",
    "SPECIES_HOOPA",
    "SPECIES_VOLCANION",
    "SPECIES_TYPE_NULL",
    "SPECIES_SILVALLY",
    "SPECIES_TAPU_KOKO",
    "SPECIES_TAPU_LELE",
    "SPECIES_TAPU_BULU",
    "SPECIES_TAPU_FINI",
    "SPECIES_COSMOG",
    "SPECIES_COSMOEM",
    "SPECIES_SOLGALEO",
    "SPECIES_LUNALA",
    "SPECIES_NIHILEGO",
    "SPECIES_BUZZWOLE",
    "SPECIES_PHEROMOSA",
    "SPECIES_XURKITREE",
    "SPECIES_CELESTEELA",
    "SPECIES_KARTANA",
    "SPECIES_GUZZLORD",
    "SPECIES_NECROZMA",
    "SPECIES_MAGEARNA",
    "SPECIES_MARSHADOW",
    "SPECIES_POIPOLE",
    "SPECIES_NAGANADEL",
    "SPECIES_STAKATAKA",
    "SPECIES_BLACEPHALON",
    "SPECIES_ZERAORA",
    "SPECIES_MELTAN",
    "SPECIES_MELMETAL",
    "SPECIES_ZACIAN",
    "SPECIES_ZAMAZENTA",
    "SPECIES_ETERNATUS",
    "SPECIES_KUBFU",
    "SPECIES_URSHIFU",
    "SPECIES_ZARUDE",
    "SPECIES_REGIELEKI",
    "SPECIES_REGIDRAGO",
    "SPECIES_GLASTRIER",
    "SPECIES_SPECTRIER",
    "SPECIES_CALYREX",
    "SPECIES_ENAMORUS",
    "SPECIES_WO_CHIEN",
    "SPECIES_CHIEN_PAO",
    "SPECIES_TING_LU",
    "SPECIES_CHI_YU",
    "SPECIES_KORAIDON",
    "SPECIES_MIRAIDON",
    "SPECIES_OKIDOGI",
    "SPECIES_MUNKIDORI",
    "SPECIES_FEZANDIPITI",
    "SPECIES_OGERPON",
    "SPECIES_TERAPAGOS",
    "SPECIES_PECHARUNT",
]
