# Base Game Aspirations
# Athletic Aspirations
base_aspiration_basic_trainer = "Basic Trainer (Bodybuilder 1)"
base_aspiration_exercise_demon = "Exercise Demon (Bodybuilder 2)"
base_aspiration_fit_to_a_t = "Fit to a T (Bodybuilder 3)"
base_aspiration_bodybuilder = "Bodybuilder (Bodybuilder 4)"
# Creativity Aspirations
base_aspiration_ill_at_easel = "Ill at Easel (Painter Extraordinaire 1)"
base_aspiration_fine_artist = "Fine Artist (Painter Extraordinaire 2)"
base_aspiration_brushing_with_greatness = "Brushing With Greatness (Painter Extraordinaire 3)"
base_aspiration_painter_extraordinaire = "Painter Extraordinaire (Painter Extraordinaire 4)"
base_aspiration_fledgelinguist = "Fledge-linguist (Bestselling Author 1)"
base_aspiration_competent_wordsmith = "Competent Wordsmith (Bestselling Author 2)"
base_aspiration_novelest_novelist = "Novelest Novelist (Bestselling Author 3)"
base_aspiration_bestselling_author = "Bestselling Author (Bestselling Author 4)"
base_aspiration_tone_deaf = "Tone Deaf (Musical Genius 1)"
base_aspiration_fine_tuned = "Fine Tuned (Musical Genius 2)"
base_aspiration_harmonious = "Harmonious (Musical Genius 3)"
base_aspiration_musical_genius = "Musical Genius (Musical Genius 4)"
# Deviance Aspirations
base_aspiration_mostly_harmless = "Mostly Harmless (Public Enemy / Chief of Mischief 1)"
base_aspiration_neighborhood_nuisance = "Neighborhood Nuisance (Public Enemy 2)"
base_aspiration_criminal_mind = "Criminal Mind (Public Enemy 3)"
base_aspiration_public_enemy = "Public Enemy (Public Enemy 4)"
base_aspiration_artful_trickster = "Artful Trickster (Chief of Mischief 2)"
base_aspiration_professional_prankster = "Professional Prankster (Chief of Mischief 3)"
base_aspiration_chief_of_mischief = "Chief of Mischief (Chief of Mischief 4)"
base_aspiration_villainous_valentine = "Villainous Valentine (Villainous Valentine 1)"
# Family Aspirations (Successful Lineage, Big Happy Family)
base_aspiration_readily_a_parent = "Readily a Parent (Successful Lineage / Big Happy Family 1)"
base_aspiration_caregiver = "Caregiver (Successful Lineage / Big Happy Family 2)"
base_aspiration_trusted_mentor = "Trusted Mentor (Successful Lineage 3)"
base_aspiration_successful_lineage = "Successful Lineage (Successful Lineage 4)"
base_aspiration_loving_guardian = "Loving Guardian (Big Happy Family 3)"
base_aspiration_big_happy_family = "Big Happy Family (Big Happy Family 4)"
# Food Aspirations (Master Chef, Master Mixologist)
base_aspiration_aluminum_chef = "Aluminum Chef (Master Chef 1)"
base_aspiration_captain_cook = "Captain Cook (Master Chef 2)"
base_aspiration_culinary_artist = "Culinary Artist (Master Chef 3)"
base_aspiration_master_chef = "Master Chef (Master Chef 4)"
base_aspiration_bar_tenderfoot = "Bar Tenderfoot (Master Mixologist 1)"
base_aspiration_electric_mixer = "Electric Mixer (Master Mixologist 2)"
base_aspiration_beverage_boss = "Beverage Boss (Master Mixologist 3)"
base_aspiration_master_mixologist = "Master Mixologist (Master Mixologist 4)"
# Fortune Aspirations (Fabulously Wealthy, Mansion Baron)
base_aspiration_going_for_not_broke = "Going for Not Broke (Fabulously Wealthy 1)"
base_aspiration_learning_earning = "Learning Earning (Fabulously Wealthy 2)"
base_aspiration_welloff = "Well-off (Fabulously Wealthy 3)"
base_aspiration_fabulously_wealthy = "Fabulously Wealthy (Fabulously Wealthy 4)"
base_aspiration_estate_of_the_art = "Estate of the Art (Mansion Baron 1)"
base_aspiration_the_great_landscaper = "The Great Landscaper (Mansion Baron 2)"
base_aspiration_home_renovator = "Home Renovator (Mansion Baron 3)"
base_aspiration_mansion_baron = "Mansion Baron (Mansion Baron 4)"
# Knowledge Aspirations (Renaissance Sim, Nerd Brain, Computer Whiz)
base_aspiration_prudent_student = "Prudent Student (Renaissance Sim / Nerd Brain 1"
base_aspiration_jack_of_some_trades = "Jack of Some Trades (Renaissance Sim 2)"
base_aspiration_pantologist = "Pantologist (Renaissance Sim 3)"
base_aspiration_renaissance_sim = "Renaissance Sim (Renaissance Sim 4)"
base_aspiration_erudite = "Erudite (Nerd Brain 2)"
base_aspiration_rocket_scientist = "Rocket Scientist (Nerd Brain 3)"
base_aspiration_nerd_brain = "Nerd Brain (Nerd Brain 4)"
base_aspiration_with_the_program = "With The Program (Computer Whiz 1)"
base_aspiration_technically_adept = "Technically Adept (Computer Whiz 2)"
base_aspiration_computer_geek = "Computer Geek (Computer Whiz 3)"
base_aspiration_computer_whiz = "Computer Whiz (Computer Whiz 4)"
# Love Aspirations (Serial Romantic, Soulmate)
base_aspiration_amore_amateur = "Amore Amateur (Serial Romantic / Soulmate 1)"
base_aspiration_up_to_date = "Up to Date (Serial Romantic 2)"
base_aspiration_romance_juggler = "Romance Juggler (Serial Romantic 3)"
base_aspiration_serial_romantic = "Serial Romantic (Serial Romantic 4)"
base_aspiration_marriage_material = "Marriage Material (Soulmate 2)"
base_aspiration_love_handler = "Love Handler (Soulmate 3)"
base_aspiration_soulmate = "Soulmate (Soulmate 4)"
# Nature Aspirations (Freelance Botanist, The Curator, Angling Ace)
base_aspiration_naturewalker = "Naturewalker (Freelance Botanist 1)"
base_aspiration_garden_variety = "Garden Variety (Freelance Botanist 2)"
base_aspiration_nature_nurturer = "Nature Nurturer (Freelance Botanist 3)"
base_aspiration_freelance_botanist = "Freelance Botanist (Freelance Botanist 4)"
base_aspiration_out_and_about = "Out and About (The Curator 1)"
base_aspiration_gatherer = "Gatherer (The Curator 2)"
base_aspiration_treasure_hunter = "Treasure Hunter (The Curator 3)"
base_aspiration_the_curator = "The Curator (The Curator 4)"
base_aspiration_fish_out_of_water = "Fish out of Water (Angling Ace 1)"
base_aspiration_hooked = "Hooked (Angling Ace 2)"
base_aspiration_reel_smart = "Reel Smart (Angling Ace 3)"
base_aspiration_angling_ace = "Angling Ace (Angling Ace 4)"
# Popularity Aspirations (Joke Star, Party Animal, Friend of the World, Neighborhood Confidante)
base_aspiration_practical_joker = "Practical Joker (Joke Star 1)"
base_aspiration_standup_startup = "Stand-up Start-up (Joke Star 2)"
base_aspiration_funny = "Funny (Joke Star 3)"
base_aspiration_joke_star = "Joke Star (Joke Star 4)"
base_aspiration_new_in_town = "New in Town (Party Animal / Friend of the World 1)"
base_aspiration_welcoming_host = "Welcoming Host (Party Animal 2)"
base_aspiration_sir_gala_had = "Sir Gala Head (Party Animal 3)"
base_aspiration_party_animal = "Party Animal (Party Animal 4)"
base_aspiration_well_liked = "Well liked (Friend of the World 2)"
base_aspiration_super_friend = "Super Friend (Friend of the World 3)"
base_aspiration_friend_of_the_world = "Friend of the World (Friend of the World 4)"
base_aspiration_neighborly_advisor = "Neighborly Advisor (Neighborhood Confidante 1)"

# DLC Aspirations
cnd_friendoftheanimals_aspiration = "Friend of the Animals Aspiration"
sne_extremesportsenthusiast_aspiration = "Extreme Sports Enthusiast Aspiration"
sne_mtkomorebisightseer_aspiration = "Mt. Komorebi Sightseer Aspiration"
gf_masteractor_aspiration = "Master Actor / Actress Aspiration"
gf_worldfamouscelebrity_aspiration = "World-Famous Celebrity Aspiration"
el_mastermaker_aspiration = "Master Maker Aspiration"
el_ecoinnovator_aspiration = "Eco Innovator Aspiration"
nks_lordoftheknits_aspiration = "Lord / Lady of the Knits Aspiration"
vamp_vampirefamily_aspiration = "Vampire Family Aspiration"
vamp_mastervampire_aspiration = "Master Vampire Aspiration"
vamp_goodvampire_aspiration = "Good Vampire Aspiration"
ph_superparent_aspiration = "Super Parent Aspiration"
ja_archaeologyscholar_aspiration = "Archaeology Scholar Aspiration"
ja_jungleexplorer_aspiration = "Jungle Explorer Aspiration"
rom_spellcraftnsorcery_aspiration = "Spellcraft and Sorcery Aspiration"
rom_purveyorofpotions_aspiration = "Purveyor of Potions Aspiration"
du_academic_aspiration = "Academic Aspiration"
cl_citynative_aspiration = "City Native Aspiration"
sv_strangervillemystery_aspiration = "Strangerville Mystery Aspiration"
il_beachlife_aspiration = "Beach Life Aspiration"
btd_perfectlypristine_aspiration = "Perfectly Pristine Aspiration"
btd_fabulouslyfilthy_aspiration = "Fabulously Filthy Aspiration"
or_outdoorenthusiast_aspiration = "Outdoor Enthusiast Aspiration"
cl_countrycaretaker_aspiration = "Country Caretaker Aspiration"
gt_leaderofthepack_aspiration = "Leader of the Pack Aspiration"
jtb_hopevsorder_aspiration = "Hope VS Order Aspiration"
jtb_paragonofhope_aspiration = "Paragon of Hope Aspiration"
jtb_enforceroforder_aspiration = "Enforcer of Order Aspiration"
jtb_galacticprivateer_aspiration = "Galactic Privateer Aspiration"
sd_innerpeace_aspiration = "Inner Peace Aspiration"
sd_selfcarespecialist_aspiration = "Self-Care Specialist Aspiration"
sd_zenguru_aspiration = "Zen Guru Aspiration"
ww_werewolfinitiate_aspiration = "Werewolf Initiate Aspiration"
ww_lonewolf_aspiration = "Lone Wolf Aspiration"
ww_emissaryofthecollective_aspiration = "Emissary of the Collective Aspiration"
ww_wildfangrenegade_aspiration = "Wildfang Renegate Aspiration"
ww_cureseeker_aspiration = "Cureseeker Aspiration"
