# Base game careers
# Astronaut
base_career_astronaut_2 = "Module Cleaner (Astronaut 2)"
base_career_astronaut_3 = "Technician (Astronaut 3)"
base_career_astronaut_4 = "Command Center Lead (Astronaut 4)"
base_career_astronaut_5 = "Low-Orbit Specialist (Astronaut 5)"
base_career_astronaut_6 = "Space Cadet (Astronaut 6)"
base_career_astronaut_7 = "Astronaut (Astronaut 7)"
base_career_astronaut_8A = "Planet Patrol (Astronaut / Space Ranger 8)"
base_career_astronaut_9A = "Sheriff of the Stars (Astronaut / Space Ranger 9)"
base_career_astronaut_10A = "Space Ranger (Astronaut / Space Ranger 10)"
base_career_astronaut_8B = "Moon Mercenary (Astronaut / Interstellar Smuggler 8)"
base_career_astronaut_9B = "Alien Goods Trader (Astronaut / Interstellar Smuggler 9)"
base_career_astronaut_10B = "Interstellar Smuggler (Astronaut / Interstellar Smuggler 10)"
# Athlete
base_career_athlete_2 = "Locker Room Attendant (Athlete 2)"
base_career_athlete_3 = "Team Mascot (Athlete 3)"
base_career_athlete_4 = "Dance Team Captain (Athlete 4)"
base_career_athlete_5A = "Minor Leaguer (Athlete / Professional Athlete 5)"
base_career_athlete_6A = "Rookie (Athlete / Professional Athlete 6)"
base_career_athlete_7A = "Starter (Athlete / Professional Athlete 7)"
base_career_athlete_8A = "All-Star (Athlete / Professional Athlete 8)"
base_career_athlete_9A = "MVP (Athlete / Professional Athlete 9)"
base_career_athlete_10A = "Hall of Famer (Athlete / Professional Athlete 10)"
base_career_athlete_5B = "Personal Trainer (Athlete / Bodybuilder 5)"
base_career_athlete_6B = "Professional Bodybuilder (Athlete / Bodybuilder 6)"
base_career_athlete_7B = "Champion Bodybuilder (Athlete / Bodybuilder 7)"
base_career_athlete_8B = "Trainer to the Stars (Athlete / Bodybuilder 8)"
base_career_athlete_9B = "Celebrity Bodybuilder (Athlete / Bodybuilder 9)"
base_career_athlete_10B = "Mr. / Mrs. Solar System (Athlete / Bodybuilder 10)"
# Business
base_career_business_2 = "Office Assistant (Business 2)"
base_career_business_3 = "Assistant to the Manager (Business 3)"
base_career_business_4 = "Assistant Manager (Business 4)"
base_career_business_5 = "Regional Manager (Business 5)"
base_career_business_6 = "Senior Manager (Business 6)"
base_career_business_7A = "Vice-President (Business / Management 7)"
base_career_business_8A = "President (Business / Management 8)"
base_career_business_9A = "CEO (Business / Management 9)"
base_career_business_10A = "Business Tycoon (Business / Management 10)"
base_career_business_7B = "Futures Trader (Business / Investor 7)"
base_career_business_8B = "Hedge Fund Manager (Business / Investor 8)"
base_career_business_9B = "Corporate Raider (Business / Investor 9)"
base_career_business_10B = "Angel Investor (Business / Investor 10)"
# Criminal
base_career_criminal_2 = "Petty Thief (Criminal 2)"
base_career_criminal_3 = "Ringleader (Criminal 3)"
base_career_criminal_4 = "Felonius Monk (Criminal 4)"
base_career_criminal_5 = "Minor Crimelord (Criminal 5)"
base_career_criminal_6A = "The Muscle (Criminal / Boss 6)"
base_career_criminal_7A = "Getaway Driver (Criminal / Boss 7)"
base_career_criminal_8A = "Safe Cracker (Criminal / Boss 8)"
base_career_criminal_9A = "The Brains (Criminal / Boss 9)"
base_career_criminal_10A = "The Boss (Criminal / Boss 10)"
base_career_criminal_6B = "DigiThief (Criminal / Oracle 6)"
base_career_criminal_7B = "Elite Hacker (Criminal / Oracle 7)"
base_career_criminal_8B = "An0nymous Ghost (Criminal / Oracle 8)"
base_career_criminal_9B = "Net Demon (Criminal / Oracle 9)"
base_career_criminal_10B = "The Oracle (Criminal / Oracle 10)"
# Culinary
base_career_culinary_2 = "Head Dishwasher (Culinary 2)"
base_career_culinary_3 = "Caterer (Culinary 3)"
base_career_culinary_4 = "Mixologist (Culinary 4)"
base_career_culinary_5 = "Line Cook (Culinary 5)"
base_career_culinary_6A = "Head Caterer (Culinary / Chef 6)"
base_career_culinary_7A = "Pastry Chef (Culinary / Chef 7)"
base_career_culinary_8A = "Sous Chef (Culinary / Chef 8)"
base_career_culinary_9A = "Executive Chef (Culinary / Chef 9)"
base_career_culinary_10A = "Celebrity Chef (Culinary / Chef 10)"
base_career_culinary_6B = "Head Mixologist (Culinary / Mixologist 6)"
base_career_culinary_7B = "Juice Boss (Culinary / Mixologist 7)"
base_career_culinary_8B = "Chief Drink Operator (Culinary / Mixologist 8)"
base_career_culinary_9B = "Drinkmaster (Culinary / Mixologist 9)"
base_career_culinary_10B = "Celebrity Mixologist (Culinary / Mixologist 10)"
# Entertainer
base_career_entertainer_2 = "Open Mic Seeker (Entertainer 2)"
base_career_entertainer_3 = "C-Lister (Entertainer 3)"
base_career_entertainer_4 = "Opening Act (Entertainer 4)"
base_career_entertainer_5A = "Jingle Jammer (Entertainer / Musician 5)"
base_career_entertainer_6A = "Serious Musician (Entertainer / Musician 6)"
base_career_entertainer_7A = "Professional Pianist (Entertainer / Musician 7)"
base_career_entertainer_8A = "Symphonic String Player (Entertainer / Musician 8)"
base_career_entertainer_9A = "Instrumental Wonder (Entertainer / Musician 9)"
base_career_entertainer_10A = "Concert Virtuoso (Entertainer / Musician 10)"
base_career_entertainer_5B = "Jokesmith (Entertainer / Comedian 5)"
base_career_entertainer_6B = "Solid Storyteller (Entertainer / Comedian 6)"
base_career_entertainer_7B = "Rising Comedian (Entertainer / Comedian 7)"
base_career_entertainer_8B = "Roast Master (Entertainer / Comedian 8)"
base_career_entertainer_9B = "Stand Up Star (Entertainer / Comedian 9)"
base_career_entertainer_10B = "Show Stopper (Entertainer / Comedian 10)"
# Painter
base_career_painter_2 = "Art Book Collator (Painter 2)"
base_career_painter_3 = "Hungry Artist (Painter 3)"
base_career_painter_4 = "Watercolor Dabbler (Painter 4)"
base_career_painter_5 = "Canvas Creator (Painter 5)"
base_career_painter_6 = "Imaginative Imagist (Painter 6)"
base_career_painter_7A = "Artist en Residence (Painter / Master of the Real 7)"
base_career_painter_8A = "Professional Painter (Painter / Master of the Real 8)"
base_career_painter_9A = "Illustrious Illustrator (Painter / Master of the Real 9)"
base_career_painter_10A = "Master of the Real (Painter / Master of the Real 10)"
base_career_painter_7B = "Color Theory Critic (Painter / Patron of the Arts 7)"
base_career_painter_8B = "Fine-Art Aficionado (Painter / Patron of the Arts 8)"
base_career_painter_9B = "Composition Curator (Painter / Patron of the Arts 9)"
base_career_painter_10B = "Patron of the Arts (Painter / Patron of the Arts 10)"
# Secret Agent
base_career_secret_agent_2 = "Intelligence Researcher (Secret Agent 2)"
base_career_secret_agent_3 = "Agent Handler (Secret Agent 3)"
base_career_secret_agent_4 = "Field Agent (Secret Agent 4)"
base_career_secret_agent_5 = "Lead Detective (Secret Agent 5)"
base_career_secret_agent_6 = "Government Agent (Secret Agent 6)"
base_career_secret_agent_7 = "Secret Agent (Secret Agent 7)"
base_career_secret_agent_8A = "Spy Captain (Secret Agent / Diamond Agent 8)"
base_career_secret_agent_9A = "Shadow Agent (Secret Agent / Diamond Agent 9)"
base_career_secret_agent_10A = "Double Diamond Agent (Secret Agent / Diamond Agent 10)"
base_career_secret_agent_8B = "Double Agent (Secret Agent / Villain 8)"
base_career_secret_agent_9B = "[Redacted] (Secret Agent / Villain 9)"
base_career_secret_agent_10B = "Supreme Villain (Secret Agent / Villain 10)"
base_career_secret_agent_11B = "Triple Agent (Secret Agent / Villain 11)"
# Style Influencer
base_career_style_influencer_2 = "Consignment Commentator (Style Influencer 2)"
base_career_style_influencer_3 = "Wearable Wordsmith (Style Influencer 3)"
base_career_style_influencer_4 = "Ensemble Author (Style Influencer 4)"
base_career_style_influencer_5 = "Culture Columnist (Style Influencer 5)"
base_career_style_influencer_6A = "Dedicated Dresser (Style Influencer / Stylist 6)"
base_career_style_influencer_7A = "Textile Tactician (Style Influencer / Stylist 7)"
base_career_style_influencer_8A = "Wardrobe Wiz (Style Influencer / Stylist 8)"
base_career_style_influencer_9A = "Make-Over Miracle Worker (Style Influencer / Stylist 9)"
base_career_style_influencer_10A = "Persona Re-Imager (Style Influencer / Stylist 10)"
base_career_style_influencer_6B = "Posh Profiler (Style Influencer / Trend Setter 6)"
base_career_style_influencer_7B = "Fashion Figure (Style Influencer / Trend Setter 7)"
base_career_style_influencer_8B = "Best-Self-Helper (Style Influencer / Trend Setter 8)"
base_career_style_influencer_9B = "It Sim (Style Influencer / Trend Setter 9)"
base_career_style_influencer_10B = "Icon O'Class (Style Influencer / Trend Setter 10)"
# Tech Guru
base_career_tech_guru_2 = "Quality Assurance (Tech Guru 2)"
base_career_tech_guru_3 = "Code Monkey (Tech Guru 3)"
base_career_tech_guru_4 = "Ace Engineer (Tech Guru 4)"
base_career_tech_guru_5 = "Project Manager (Tech Guru 5)"
base_career_tech_guru_6 = "Development Captain (Tech Guru 6)"
base_career_tech_guru_7A = "eSports Competitor (Tech Guru / eSport Gamer 7)"
base_career_tech_guru_8A = "Pro Gamer (Tech Guru / eSport Gamer 8)"
base_career_tech_guru_9A = "APM King / Queen (Tech Guru / eSport Gamer 9)"
base_career_tech_guru_10A = "Champion Gamer (Tech Guru / eSport Gamer 10)"
base_career_tech_guru_7B = "The Next Big Thing? (Tech Guru / Start-up Entrepreneur 7)"
base_career_tech_guru_8B = "Independent Consultant (Tech Guru / Start-up Entrepreneur 8)"
base_career_tech_guru_9B = "Dot-Com Pioneer (Tech Guru / Start-up Entrepreneur 9)"
base_career_tech_guru_10B = "Start-up Genius (Tech Guru / Start-up Entrepreneur 10)"

# Writer
base_career_writer_2 = "Blogger (Writer 2)"
base_career_writer_3 = "Freelance Article Writer (Writer 3)"
base_career_writer_4 = "Advice Columnist (Writer 4)"
base_career_writer_5 = "Regular Contributor (Writer 5)"
base_career_writer_6A = "Short Story Writer (Writer / Author 6)"
base_career_writer_7A = "Novelist (Writer / Author 7)"
base_career_writer_8A = "Fan Favorite (Writer / Author 8)"
base_career_writer_9A = "Bestselling Author (Writer / Author 9)"
base_career_writer_10A = "Creator of Worlds (Writer / Author 10)"
base_career_writer_6B = "Page Two Journalist (Writer / Journalist 6)"
base_career_writer_7B = "Front Page Writer (Writer / Journalist 7)"
base_career_writer_8B = "Investigative Journalist (Writer / Journalist 8)"
base_career_writer_9B = "Editor-in-Chief (Writer / Journalist 9)"
base_career_writer_10B = "Scribe of History (Writer / Journalist 10)"


# Base Game Part Time Jobs
base_ptj_babysitter_2 = "Nanny (Babysitter 2)"
base_ptj_babysitter_3 = "Daycare Assistant (Babysitter 3)"

base_ptj_barista_2 = "Bean Blender (Barista 2)"
base_ptj_barista_3 = "Latte Artiste (Barista 3)"

base_ptj_fastfood_employee_2 = "Fry Cook (Fastfood Employee 2)"
base_ptj_fastfood_employee_3 = "Food Service Cashier (Fastfood Employee 3)"

base_ptj_manual_laborer_2 = "Landscaper (Manual Laborer 2)"
base_ptj_manual_laborer_3 = "Backhoe Operator (Manual Laborer 3)"

base_ptj_retail_employee_2 = "Sales Floor Clerk (Retail Employee 2)"
base_ptj_retail_employee_3 = "Customer Support (Retail Employee 3)"


# DLC careers
gtw_detective_career = "Detective Career"
gtw_doctor_career = "Doctor Career"
gtw_scientist_career = "Scientist Career"
cl_critic_career = "Critic Career"
cl_politician_career = "Polititian Career"
cl_socialmedia_career = "Social Media Career"
se_gardening_career = "Gardening Career"
gf_actor_career = "Actor/Actress Career"
sv_military_career = "Military Career"
il_conservationist_career = "Conservationist Career"
du_education_career = "Education Career"
du_engineer_career = "Engineer Career"
du_law_career = "Law Career"
el_civildesigner_career = "Civil Designer Career"
sne_salaryperson_career = "Salary Person Career"
dhd_interiordecorator_career = "Interior Decorator Career"

# DLC Part Time Jobs
il_diver_ptj = "Diver Part Time Job"
il_fisherman_ptj = "Fisherman Part Time Job"
il_lifeguard_ptj = "Lifeguard Part Time Job"
hsy_simfluencer_ptj = "Simfluencer Part Time Job"
hsy_videogamestreamer_ptj = "Video Game Streamer Part Time Job"
